// Spanish translations for the dialogue system, keyed by the SAME stable line ids as
// js/dialogue-data.js (the English source, generated from dialogue_lines.xlsx). Any id missing
// here falls back to the English workbook text — so this file may lag the workbook safely.
// dialogue.js picks these up through Dialogue._pack() when I18n.locale === 'es'.
// Tone: the player↔agent relationship is close and personal, so these use informal "tú"
// throughout (the business mail and agency screens stay neutral).
const DIALOGUE_ES = {
    // --- player spoken lines (DIALOGUE_DATA[sheet][*].text, by id) ---
    lines: {
        // Complaint
        C001: "Jefe, necesito minutos. Entreno bien toda la semana, llega el sábado y me toca mirar desde el banquillo.",
        C002: "¿Podemos hablar? No vine al {club} para calentar banquillo. Algo tiene que cambiar.",
        C003: "No te pido milagros, {agent}. Te pido una oportunidad justa de estar en el once.",
        C004: "Estoy harto de mirar desde fuera, {agent}. Si el míster no me pone, búscame a alguien que sí lo haga.",
        C005: "Mira mis datos de entrenamiento y mira luego quién juega por delante de mí. No cuadra, y quiero saber qué opinas.",
        C006: "La gente no deja de preguntarme por qué no juego. No tengo respuesta. Eso es un problema para los dos.",
        C007: "Entre nosotros, no veo que el {club} vaya a ninguna parte. Necesito saber que tienes un plan para mí.",
        C008: "Este no es el proyecto que me vendieron, {agent}. El vestuario está apagado.",
        C009: "Le he dado todo a este club y ya no estoy seguro de que sea mutuo.",
        C010: "Nunca pensé que diría esto, pero el club ha cambiado. No es el sitio por el que firmé.",
        C011: "Aquí ya he visto todo lo que hay que ver. Necesito un reto nuevo antes de quedarme estancado.",
        C012: "Últimamente hay algo raro en el club. No quiero dramas, solo quiero que se arregle.",
        C013: "¿Has visto lo que cobra el fichaje nuevo? Le estoy rindiendo mejor por la mitad de dinero.",
        C014: "Mi contrato ya no se corresponde con lo que aporto. ¿Cuándo lo arreglamos?",
        C015: "No me gusta hablar de dinero, {agent}, pero alguien tiene que hacerlo. Mi salario va por detrás del vestuario.",
        C016: "Los números no engañan, {agent}. Los míos suben y mi salario no. Arréglalo.",
        C017: "Me da hasta vergüenza sacar el tema, pero los compañeros dicen que cobro poco. ¿Tienen razón?",
        C018: "¿Un jugador de mi perfil con este salario? Queda mal. Y ES malo.",
        C019: "¿Sinceramente? No sé nada de ti a menos que haya un incendio. Eso no es lo que yo firmé.",
        C020: "Necesito saber que sigues de mi lado, {agent}. Últimamente he tenido mis dudas.",
        C021: "¿Dónde has estado? Otros agentes llaman a sus jugadores cada semana. Yo recibo silencio.",
        C022: "Llevo mucho tiempo contigo, {agent}. Solo dime que eso todavía significa algo.",
        C023: "Ya hemos pasado la fase de hablar, {agent}. Hazme jugar o sácame de aquí. Esas son las opciones.",
        C024: "Cada semana en ese banquillo me cuesta dinero y carrera. Quiero una solución ya, no otra charla.",
        C025: "¡Basta! Pediré yo mismo el traspaso si es lo que hace falta para jugar al fútbol.",
        C026: "Voy en serio. Empieza a buscarme una salida, o haré público que quiero irme.",
        C027: "Tengo clara mi decisión sobre este sitio. Lo que necesito de ti es un plan, esta semana.",
        C028: "La última vez que hablamos no pasó nada. Consígueme un contrato decente o buscaré a quien pueda.",
        C029: "Tuviste tu oportunidad de arreglar mi contrato en silencio. Ahora se va a oír.",
        C030: "He estado hablando con otras agencias, {agent}. Dame una buena razón para quedarme.",
        C031: "Por mi parte, este es tu último aviso. Demuéstrame que mi carrera todavía te importa.",
        C032: "Gracias por escucharme. Ayuda más de lo que crees.",
        C033: "Vale. Me siento mejor habiéndolo dicho. Veamos cómo van las próximas semanas.",
        C034: "Siempre has sabido cuándo toca solo escuchar. Te lo agradezco, {agent}.",
        C035: "Perdona por soltártelo todo así. Pero sí, gracias.",
        C036: "Bien. Ya he dicho lo mío. Tú no lo olvides.",
        C037: "De acuerdo. Te voy a tomar la palabra, {agent}.",
        C038: "Eso es lo que necesitaba oír. No me falles.",
        C039: "Trato hecho. Nunca me has dejado colgado, así que me fío.",
        C040: "Bien. Ponlo por escrito si hace falta. Voy a ir contando las semanas.",
        C041: "Tu palabra siempre me ha bastado. No me hagas arrepentirme.",
        C042: "Vaya. No esperaba esa respuesta. Pero puede que tengas razón.",
        C043: "Es duro oírlo, pero es honesto. Vale. Bajaré la cabeza y a trabajar.",
        C044: "Es un análisis justo. Puedo trabajar con eso. Gracias por ser claro conmigo.",
        C045: "Tienes razón con los números. Me centraré en lo que puedo controlar.",
        C046: "¿En serio? Vengo a ti con un problema y me dices que el problema SOY YO.",
        C047: "Vaya. Bien saber de qué lado estás. Esta conversación se ha terminado.",
        C048: "¡Qué cara tienes! ¿De qué lado estás exactamente?",
        C049: "No. NO. No estás en posición de sermonearme. Arréglalo o busco a alguien que lo haga.",
        C050: "Claro. «Ya se arreglará solo». Esa me la han contado antes.",
        C051: "Bueno, ya veremos. Pero no voy a esperar eternamente, {agent}.",
        C052: "Hm. Eso no es una respuesta, ¿verdad?",

        // Gifts
        G001: "Ah, qué detalle. Las cosas pequeñas también cuentan. Gracias, {agent}.",
        G002: "¡Te has acordado! Gracias, es un detalle precioso.",
        G003: "No tenías por qué hacerlo. Pero gracias, de verdad.",
        G004: "Mono. La intención es lo que cuenta, supongo.",
        G005: "Eso sí es un regalo de verdad. Gracias, en serio.",
        G006: "Vale, tienes buen gusto. Eso te lo concedo.",
        G007: "Esto es de otro nivel. Espera a que lo vean los compañeros.",
        G008: "Qué detalle tan considerado. Le buscaré un buen sitio en casa.",
        G009: "Esto es… guau. De verdad que no hacía falta. Gracias, {agent}.",
        G010: "Increíble. No sé qué decir. Gracias.",
        G011: "ASÍ se trata a una estrella. ¡Me encanta!",
        G012: "Es demasiado, {agent}. De verdad. Pero lo voy a guardar como un tesoro.",
        G013: "Después de tantos años todavía me sorprendes. Gracias.",
        G014: "¿Otro ya? Gracias, supongo.",
        G015: "Últimamente me estás consintiendo demasiado. Pierde un poco de brillo, ¿sabes?",
        G016: "¿Dos regalos tan seguidos? Ahora me pregunto cuál es la mala noticia.",
        G017: "¡Ja! Eso me lo quedo.",
        G018: "Dilo más alto la próxima vez, que hay prensa cerca.",
        G019: "Yo solo hago mi trabajo. Pero gracias.",
        G020: "Entendido. Vuelvo al trabajo.",
        G021: "Ese es exactamente mi plan.",
        G022: "Qué poco divertido eres. Pero bueno, vale.",

        // Finals
        F001: "Hoy es de los grandes, {agent}. El vestuario está a mil. Me alegro de que hayas venido.",
        F002: "Así que esto es todo. A noventa minutos de una medalla.",
        F003: "Nunca había jugado una final con mi agente en la grada. Sin presión, entonces.",
        F004: "No me puedo quedar quieto, {agent}. Quiero atravesar esa pared AHORA MISMO.",
        F005: "Me he estudiado al {opponent}. Lo van a decidir las acciones a balón parado, ya verás.",
        F006: "Las finales son mi escenario, {agent}. Hoy se enteran todos.",
        F007: "Pase lo que pase ahí fuera, gracias por venir. Significa mucho.",
        F008: "Hoy está en la grada todo el mundo al que conozco. Simplemente no quiero fallarles.",
        F009: "Por esto juego al fútbol. Por días como hoy.",
        F010: "Ganar esto con ESTE club significaría todo para mí.",
        F011: "Prima por victoria en el contrato, medalla de copa en la estantería. Vamos a por las dos.",
        F012: "Sí. Sí, tienes razón. Respiro hondo. Estoy bien.",
        F013: "Vale. Vale. Cabeza despejada, piernas sueltas. Gracias, {agent}.",
        F014: "De acuerdo. Proceso por encima de emoción. Nos vemos después.",
        F015: "¿Calma? Estoy bien, {agent}. Ahórrate el discurso.",
        F016: "La calma es para el banquillo. Yo estoy hecho para esto.",
        F017: "¡SÍ! ¡Eso es lo que quería oír!",
        F018: "Mírame ahí fuera. El primer gol es para ti.",
        F019: "Tranquilo, tranquilo. Necesito la cabeza despejada, no un grito de guerra.",
        F020: "Te lo agradezco, pero yo me preparo a mi manera.",
        F021: "¡Ja! ESO sí es motivación. Trato hecho.",
        F022: "Ahora hablas mi idioma. Dalo por ganado.",
        F023: "No hace falta que me sobornes, {agent}. Pero vale, trato hecho.",
        F024: "¡LO HEMOS HECHO! ¿Te lo puedes creer? ¡Ven aquí, {agent}!",
        F025: "¡Campeones! ¡Llevo soñando con esto desde que era niño!",
        F026: "¿Has VISTO eso? ¡Van a estar hablando de esto durante años!",
        F027: "Lo hemos conseguido de verdad. Todo el equipo ha estado increíble.",
        F028: "Por este club. Por toda esa gente en la grada. Estoy muy orgulloso, {agent}.",
        F029: "¡SÍÍÍ! ¡Nadie creía en nosotros! ¡NADIE!",
        F030: "¡Más alto, {agent}! ¡Esta noche se celebra!",
        F031: "¡Dilo otra vez para las cámaras!",
        F032: "Ja, gracias. Un poco excesivo delante de todo el mundo, pero gracias.",
        F033: "Siéntate, por favor, que me da vergüenza. Pero gracias.",
        F034: "Eso significa más que cualquier titular. Gracias.",
        F035: "Te lo agradezco. En voz baja es exactamente como me gusta.",
        F036: "¿Unas palabras en privado? ¿Esta noche? ¡Venga, vive un poco!",
        F037: "¡Las copas las paga el agente! ¡ESO es servicio!",
        F038: "Generoso Y listo. Los compañeros se van a acordar de esto.",
        F039: "Tan cerca. Tan, tan cerca. No sé qué decir, {agent}.",
        F040: "Esa va a doler durante mucho tiempo.",
        F041: "No. Simplemente… no digas nada todavía.",
        F042: "Lo siento. Siento que he fallado a todo el mundo ahí fuera.",
        F043: "La afición merecía algo mejor hoy. Eso es lo que me mata.",
        F044: "Gracias por quedarte. La mayoría de la gente te deja solo con esto.",
        F045: "Me alegro de que estés aquí. De verdad.",
        F046: "Te lo agradezco, pero ahora mismo quiero estar un poco solo.",
        F047: "Sí. Te llamo en un par de días. Gracias por entenderlo.",
        F048: "Buena decisión. Esta noche no estoy para nadie.",
        F049: "Claro. Todo el mundo se va después de una derrota. Anotado.",
        F050: "Tienes razón. La próxima temporada empieza mañana. Vamos otra vez.",
        F051: "Correcto. Las derrotas son datos. Saldremos mejores de esta.",
        F052: "¿La próxima temporada? ACABAMOS de perder, {agent}. Lee el ambiente.",
        F090: "Hoy lo hicimos todo bien, {agent}. Simplemente no fue suficiente: el título se ha ido por el otro resultado.",
        F091: "Ganamos y aun así se nos escapó. Tan cerca. No me puedo creer que se haya acabado.",
        F092: "Nuestra parte está hecha, cumplimos. Nos ha matado el partido que no podíamos controlar.",

        // Farewell (retirement)
        W001: "Bueno, {agent}. Esto es todo. Botas colgadas. Gracias por el trabajo de todos estos años.",
        W002: "Entonces es oficial. Retirada. Tuvimos nuestros altibajos, pero sacamos el trabajo adelante.",
        W003: "Qué sensación tan extraña, {agent}. Se acabaron los días de partido. Me alegro de que hayas estado en buena parte del camino.",
        W004: "Así que ese fue el último pitido. Gracias por estos años, {agent}. Te portaste bien conmigo más veces que mal.",
        W005: "¿Sabes? De toda la gente del fútbol, eres uno de los pocos a los que voy a echar de menos de verdad. Qué viaje hemos tenido.",
        W006: "No dejo de pensar en todo lo que pasamos juntos. Contratos, traspasos, todo. Gracias, amigo mío.",
        W007: "Antes de nada: mi partido de homenaje. Primera fila, invitado de honor. No se discute. Has sido familia en todo esto.",
        W008: "Me preguntaron quién importó más en mi carrera. Dije mi familia. Y te nombré a ti en la misma frase, {agent}.",
        W009: "Una carrera de las grandes, sí. Y no habría podido hacer ni la mitad sin ti.",
        W010: "Se acordarán de los goles. Tú solo asegúrate de que escriban bien mi nombre en los libros de récords.",
        W011: "Ha sido una buena obra. Los dos podemos estar satisfechos con eso.",
        W012: "Eso significa más que los trofeos, sinceramente. Gracias por todo.",
        W013: "Para, que me vas a hacer llorar. Gracias. Por todo.",
        W014: "Seguimos juntos, ¿verdad? A través de todo. Eso es raro en este deporte.",
        W015: "¡Me estás haciendo llorar. Me alegro tantísimo de haberte conocido!",
        W016: "¡Significa el mundo para mí que hayas estado ahí en todo momento!",

        // Check-in
        K001: "¡Hola, {agent}! Buen momento, acabo de terminar el entrenamiento. ¿Qué tienes en mente?",
        K002: "Vaya, mira quién es. ¿Todo bien, o esto es negocio?",
        K003: "Tú llamaste, aquí estoy. Eso sí, el café lo pagas tú.",
        K004: "Rápido, que tengo gimnasio. Es broma. Más o menos. ¿Qué pasa?",
        K005: "¿Vienes a ver cómo está tu cliente favorito? Buena jugada.",
        K006: "Siempre se agradece que te pases, {agent}. De verdad.",
        K007: "Pasa, pasa. Da gusto ver una cara conocida.",
        K008: "¿Familia? Ahora mismo estoy solo, sinceramente. El fútbol se lleva todo lo que tengo.",
        K009: "Solo yo, mis botas y una maleta. Por ahora me va bien así.",
        K010: "Mi media naranja me mantiene cuerdo. No podría hacer nada de esto solo.",
        K011: "Los niños son todo, {agent}. Cada partido que juego es por ellos.",
        K012: "Los peques mandan en casa. Lo mejor que me ha pasado en la vida.",
        K013: "¿Últimamente? Ando muy metido en {hobby}. Me mantiene la cabeza tranquila entre partidos.",
        K014: "Hago tiempo para {hobby}. Recuperación para la mente, no solo para las piernas.",
        K015: "Lo de siempre, sinceramente. Entrenar, casa, repetir. Estoy a gusto.",
        K016: "¿Desde niño? El {favclub}. Mi padre me llevó a un partido una vez y ya está, hasta hoy.",
        K017: "Fácil. El {favclub}. Tenía los pósteres, las camisetas, todo.",
        K018: "El {favclub}, siempre. Algunas cosas no cambian, juegues donde juegues.",
        K019: "¡Me encanta el {favclub}! No puedo quedarme quieto cuando juegan.",
        K020: "El {favclub}. Mi abuela tiene el carnet de socia desde hace 52 años, y ha metido a toda la familia en esto.",
        K021: "¿Sinceramente? Algún día quiero {ambition}. Ese es el sueño.",
        K022: "Entre nosotros: quiero {ambition}. Y quiero que lo vea todo el mundo.",
        K023: "Me he marcado un solo objetivo: {ambition}. Todo lo que hago apunta ahí.",
        K024: "Si algún día pudiera {ambition}, sería un logro increíble para mí y para los míos.",
        K025: "Necesito {ambition}. ¡Y siempre quiero estar en la pelea por los títulos!",
        K026: "Quiero {ambition}. Pero lo más importante es tener a mis amigos y a mi familia conmigo en cada paso del camino.",
        K027: "El vestuario está bien. Algún ego grande, pero enséñame uno sin ellos.",
        K028: "Sinceramente, un grupo de tíos excelente. El mejor del que he formado parte.",
        K029: "Hay uno que no deja de quitarme la plaza de aparcamiento. Ya hemos tenido palabras.",
        K030: "Sinceramente, siento que mis compañeros no aprecian lo suficiente mi excelencia…",
        K031: "¡Ja! Es una fiesta la mayor parte del tiempo, ¡y ya sabes que el DJ soy yo!",
        K032: "¡Me siento como en casa aquí! Ahora mismo no veo ningún motivo para irme nunca.",
        K033: "¡Me siento como en casa aquí! Ahora mismo no veo ningún motivo para irme nunca.",
        K034: "Tenemos un par de serpientes de dos caras entre nosotros… Siempre hablando por detrás de los demás.",
        K035: "Ahora mismo nos falta cohesión de verdad… Creo que el entrenador ha montado una plantilla de mercenarios.",
        K036: "A veces miro alrededor y me siento muy agradecido de formar parte de este equipo increíble. Gracias por hacerlo posible para mí.",
        K037: "He hecho muchos amigos en mi tiempo en este club. Me siento afortunado de verdad.",
        K038: "Ja, ¿solo venías a ver cómo estoy? Te lo agradezco. De verdad.",
        K039: "¿Sin agenda? Eso es nuevo viniendo de un agente. Me gusta.",
        K040: "Es muy amable de tu parte. Aquí fuera a veces se está solo, ¿sabes?",
        K041: "¡Me alegro de verte, {agent}! ¿De qué querías hablar?",
        K042: "Hola, ¿cómo estás? ¡Espero que no vengas a pedirme dinero! Es broma, claro. ¿Qué pasa?",
        K043: "Qué bien que te pongas en contacto. ¿De qué querías hablar conmigo?",

        // Moments
        M001: "¡Primeros minutos con el primer equipo, {agent}! ¿Lo has visto? Todavía llevo la camiseta puesta. No me la voy a quitar.",
        M002: "He jugado de verdad. Un partido de verdad con el primer equipo. Sigo esperando que alguien me diga que ha sido un error.",
        M003: "¡PRIMER GOL! ¿Lo has visto? Ya habré visto el vídeo cincuenta veces.",
        M004: "Por fin me ha entrado una. Se siente irreal, sinceramente.",
        M005: "¡TRES! ¡Un triplete, {agent}! ¡Me han dado el balón del partido y todo!",
        M006: "Un triplete. El balón del partido va enmarcado. Puede que las botas también.",
        M007: "{milestone}. Lo acabo de ver en el programa del partido. Cómo pasa el tiempo, ¿eh?",
        M008: "{milestone}. Una cifra bonita. Ahora a por la siguiente.",
        M009: "{milestone}. Y tú estuviste ahí para la mayoría de ellos, {agent}.",
        M010: "¡Mi primer contrato profesional, {agent}! Firmado y todo. Ya es real, ¿verdad?",
        M011: "No dejo de leer el contrato una y otra vez. Yo. Futbolista profesional.",
        M012: "Está hecho, {agent}. El {newclub}. Capítulo nuevo. Gracias por cerrarlo.",
        M013: "¡El {newclub}! Ciudad nueva, liga nueva, todo nuevo. Para esto vivo.",
        M014: "El {newclub}, entonces. Un cambio grande para mí. Confío en que sea el correcto.",
        M015: "Tengo que contarte algo. El {newclub} era MI club de pequeño. Acabas de hacer realidad el sueño de un niño. No lo olvidaré. Nunca.",
        M016: "Sabías lo que el {newclub} significaba para mí. Es lo más grande que nadie ha hecho por mi carrera. Gracias.",
        M017: "¿Recuerdas lo que te dije que quería? ¿{ambition}? … Hecho. Lo hemos conseguido de verdad.",
        M018: "{ambition}. Lo dije y lo hice. Y tú ayudaste, {agent}. Mérito a quien lo merece.",
        M019: "Dicen {weeks} semanas, {agent}. Ahora mismo no puedo ni mirar mis botas.",
        M020: "SABÍA que venía esa entrada. {weeks} semanas. Estoy furioso.",
        M021: "{weeks} semanas de baja. Ya he pedido el plan de recuperación. Aun así escuece.",
        M022: "Ja, gracias. Días como este hacen que todo valga la pena.",
        M023: "¡Por fin alguien lo dice como es!",
        M024: "Vale, vale. Una noche de celebración y luego a la normalidad.",
        M025: "Tienes razón. Cabeza baja, siguiente trabajo.",
        M026: "De acuerdo. Celebrar esta noche, reiniciar mañana.",
        M027: "¿Sin hacer ruido? Vale. Pero me voy a poner el resumen en bucle.",
        M028: "¿Has venido hasta aquí? Eso… significa mucho, {agent}.",
        M029: "No tenías que venir. Me alegro de que lo hayas hecho.",
        M030: "Han llegado las flores. Buen detalle. Mándame también algún partido para ver.",
        M031: "Antes de que te vayas. Te he traído algo. No se discute, ya está pagado. {thing}. Te lo has ganado diez veces.",
        M032: "Mi padre siempre decía: cuida a la gente que te cuida. Así que toma. {thing}. Gracias, {agent}.",
        M033: "Lo he elegido yo mismo. ¡{thing}! Solo lo mejor para mi agente, evidentemente.",
        M034: "No es gran cosa, pero… {thing}. Por todo lo que haces y que nadie ve.",
        M035: "Bien. Cada vez que lo mires, acuérdate de que esto lo hicimos juntos.",
        M036: "Eso es todo lo que quería oír. Nos cuidamos el uno al otro, siempre.",
        M037: "¡Ja! No cambies nunca, {agent}. Nunca.",
        M038: "¿Ves? Por ESTO nos llevamos bien.",
        M039: "Quiero que estés en {occasion}. No como mi agente. Como amigo. Dime que vendrás.",
        M040: "Pronto es {occasion}. Círculo pequeño, solo familia y la gente que importa. Eso te incluye, {agent}.",
        M041: "{occasion}. Va a ser EL evento del verano. Estás en la lista, obviamente.",
        M042: "¿Vienes? Eso significa el mundo. ¡Nos vemos allí!",
        M043: "¿De verdad? Yo… gracias. No sería lo mismo sin ti.",
        M044: "¿No puedes venir? Qué pena. Pero es muy generoso, gracias.",
        M045: "Claro. Agenda apretada, lo entiendo. … Lo entiendo.",
    },

    // --- what the AGENT says when you pick a choice (Dialogue.SAY, keyed "scene:choice") ---
    say: {
        'complaint:listen': "Cuéntame. Sea lo que sea, quiero oírlo, todo.",
        'complaint:promise': "De acuerdo. Esto es lo que voy a hacer al respecto.",
        'complaint:pushback': "Te escucho. Pero déjame ser claro contigo un momento.",
        'complaint:deflect': "No nos adelantemos. Dale un poco de tiempo todavía.",
        'promise:move': "Déjalo en mis manos. Te buscaré la salida correcta: el club adecuado, no un club cualquiera.",
        'promise:newContract': "Te consigo el contrato que mereces en este club. Dame un poco de tiempo.",
        'promise:playingTime': "Voy a hablar en serio con el entrenador sobre tus minutos. Lo arreglamos.",
        'promise:renegotiateRep': "Y yo me llevaré menos para que salga. Así es como te respaldo.",
        'gift:praise': "Te lo has ganado. Todo. Que nadie te diga lo contrario.",
        'gift:modest': "No es nada, de verdad. Solo quería que supieras que estoy atento.",
        'prematch:calm': "Respira. Ya has hecho todo el trabajo. Sal y juega tu partido.",
        'prematch:fireup': "Esta es tu noche. Sal ahí y tómala. No te dejes nada.",
        'prematch:bonus': "Te digo una cosa: ganas este y hay un extra para ti.",
        'bonus:small': "Ganas esta noche y hay un regalo para ti. Te doy mi palabra.",
        'bonus:medium': "Gana esto y te cuidaré como es debido. Eso es una promesa.",
        'bonus:large': "Trae esto a casa y haré que merezca mucho la pena. Palabra.",
        'postwin:toast': "Ven aquí, eso ha sido especial. Vamos a disfrutar esta.",
        'postwin:quiet': "Precioso trabajo. Te dejo volver con los compañeros.",
        'postwin:tab': "Esta noche invito yo a todo. Te lo has ganado con creces.",
        'postloss:sit': "Siéntate conmigo un minuto. Ahora escuece, no lo hará mucho tiempo.",
        'postloss:space': "Te dejo tranquilo. Cabeza alta. Vamos otra vez.",
        'postloss:speech': "Escúchame. Un partido no te define. No se te ocurra olvidarlo.",
        'farewell:career': "Qué carrera has tenido. Deberías estar orgulloso de cada minuto.",
        'farewell:personal': "Olvida el fútbol un segundo: me alegro de haberte conocido.",
        'checkin:q-life': "¿Y cómo van las cosas fuera del campo? ¿Todo bien en casa?",
        'checkin:q-club': "¿Cómo te estás adaptando en el club? ¿Te llevas bien con todos?",
        'checkin:q-ambition': "¿Hasta dónde quieres llevar todo esto? ¿A qué apuntamos de verdad?",
        'checkin:q-room': "¿Con quién andas últimamente en el vestuario?",
        'checkin:q-none': "Hoy sin agenda. Solo quería ver cómo estabas.",
        'moment:praise': "Ha sido un buen momento. Disfrútalo, te lo has ganado.",
        'moment:modest': "Brillante en silencio, eso. Bien jugado.",
        'injury:there': "Voy a verte. No vas a pasar por esto solo.",
        'injury:flowers': "Te mando algo, solo para que sepas que estoy pensando en ti.",
        'thanks:cherish': "Esto significa muchísimo para mí. Me lo quedo, de verdad.",
        'thanks:banter': "No tenías por qué hacerlo, blandengue. Pero gracias, de verdad.",
        'invite:attend': "No me lo perdería por nada del mundo. Estaré allí, en la grada.",
        'invite:gift': "No puedo ir en persona, pero deja que mande algo para marcar el día.",
        'invite:decline': "Esta vez no puedo estar, pero estoy contigo en espíritu, eso ya lo sabes.",
    },

    // --- choice buttons (keyed "scene|choice") ---
    choices: {
        'complaint|listen': { label: "Escucharle", hint: "Seguro. Quiere que le escuchen." },
        'complaint|promise': { label: "Hacerle una promesa", hint: "Abre una promesa con un plazo real." },
        'complaint|pushback': { label: "Rebatirle", hint: "Decirle que se equivoca. Arriesgado, depende del hombre." },
        'complaint|deflect': { label: "Quitarle importancia", hint: "Gana tiempo. Puede que te lo tenga en cuenta." },
        'gift|praise': { label: "Te lo has ganado" },
        'gift|modest': { label: "Cabeza baja y a jugar" },
        'prematch|calm': { label: "Calmarle", hint: "Calmar los nervios antes del partido más importante de su año." },
        'prematch|fireup': { label: "Encenderle", hint: "Hacer que le hierva la sangre." },
        'prematch|bonus': { label: "Prometerle una prima por victoria", hint: "Elige un regalo que recibirá si levantan el trofeo. No cuesta nada si pierden." },
        'postwin|toast': { label: "Brindar por él delante de todos", hint: "Elogio público. A algunos les encanta, a otros les incomoda." },
        'postwin|quiet': { label: "Unas palabras en privado", hint: "Solo vosotros dos, lejos del ruido." },
        'postwin|tab': { label: "Invitar tú esta noche", hint: "Te cuesta dinero, significa mucho." },
        'postloss|sit': { label: "Quedarte con él", hint: "No decir nada. Solo quedarte." },
        'postloss|space': { label: "Darle espacio", hint: "Algunas heridas se cierran a solas." },
        'postloss|speech': { label: "La próxima temporada vamos otra vez", hint: "Directo a lo que viene." },
        'farewell|career': { label: "Por una carrera de las grandes" },
        'farewell|personal': { label: "Por la persona, no solo por el jugador" },
        'checkin|q-life': { label: "Preguntarle por su vida fuera del fútbol" },
        'checkin|q-club': { label: "Preguntarle por su club favorito" },
        'checkin|q-ambition': { label: "Preguntarle por sus ambiciones" },
        'checkin|q-room': { label: "Preguntarle por el vestuario" },
        'checkin|q-none': { label: "Nada en particular", hint: "A veces eso es lo que más dice." },
        'moment|praise': { label: "Celebrarlo con él" },
        'moment|modest': { label: "Sin hacer ruido" },
        'injury|there': { label: "Visitarle en persona" },
        'injury|flowers': { label: "Mandarle flores" },
        'thanks|cherish': { label: "Lo guardaré como un tesoro" },
        'thanks|banter': { label: "Ya era hora de que me pagaras" },
        'invite|attend': { label: "Despejar la agenda, allí estarás", hint: "Un fin de semana de tu tiempo. Importa más que cualquier regalo." },
        'invite|gift': { label: "Mandar un regalo generoso", hint: "No puedes ir, pero el detalle llega." },
        'invite|decline': { label: "Declinar con educación", hint: "Se dará cuenta." },
    },

    // --- discovered "vocabulary": hobbies, keepsakes and occasions, keyed by the English value ---
    // These are stored on the player in English, so they are localised at fill() time. The articles
    // are part of the value, because the lines that use them read "metido en {hobby}" / "para {hobby}".
    vocab: {
        'golf': "el golf",
        'fishing': "la pesca",
        'gaming': "los videojuegos",
        'chess': "el ajedrez",
        'cooking': "la cocina",
        'classic cars': "los coches clásicos",
        'photography': "la fotografía",
        'making music': "hacer música",
        'padel': "el pádel",
        'poker': "el póker",
        'a signed shirt from his debut': "una camiseta firmada de su debut",
        'a watch with a date engraved on the back': "un reloj con una fecha grabada en la parte de atrás",
        'a framed photo of the two of you at his first signing': "una foto enmarcada de los dos en su primera firma",
        'the match ball from his best game, signed by the whole squad': "el balón de su mejor partido, firmado por toda la plantilla",
        'a bottle from a vineyard he part-owns': "una botella de un viñedo del que es copropietario",
        'my wedding': "mi boda",
        "the little one's christening": "el bautizo del pequeño",
        'a gift': "un regalo",
    },

    // --- ambitions: a pronoun-free infinitive phrase, so it reads both as a label and inside a
    // spoken line ("quiero {ambition}", "¿{ambition}? Hecho."). No article before {club}/{fav},
    // because a club name's gender is unknown; the fallbacks carry their own.
    amb: {
        types: {
            league: "jugar algún día en {league}",
            dreamclub: "jugar algún día en {club}",
            boyhood: "terminar donde empezó todo, en {fav}",
            title: "ganar un título de liga",
            cup: "levantar una copa",
            europe: "jugar en Europa",
            goals: "llegar a {target} goles en mi carrera",
            topflight: "jugar en una de las cinco grandes ligas",
            abroad: "jugar en el extranjero",
        },
        dflt: "llegar a lo más alto",
        favFallback: "el club de mi infancia",
        leagueFallback: "una liga más grande",
        clubFallback: "un gran club",
    },

    // --- milestone labels, frozen into the line when the moment is queued (the player is speaking) ---
    mile: {
        apps: "{n} partidos",
        goals: "{n} goles en mi carrera",
    },

    // --- the cash thank-you gift, filled into {thing} ---
    envelope: "un sobre. Dentro: €{amt} para la agencia",
};
if (typeof module !== 'undefined' && module.exports) module.exports = { DIALOGUE_ES };
