// Italian translations for the dialogue system, keyed by the SAME stable line ids as
// js/dialogue-data.js (the English source, generated from dialogue_lines.xlsx). Any id missing
// here falls back to the English workbook text — so this file may lag the workbook safely.
// dialogue.js picks these up through Dialogue._pack() when I18n.locale === 'it'.
//
// Informal "tu" both ways, as in the German, Spanish, French and Portuguese packs. This is spoken
// conversation between an agent and a player who know each other well; the written correspondence
// in js/i18n-it.js stays on formal "Lei". At a low bond the client still addresses you as
// "Sig. Mercer" while using "tu" — the same small tension the other packs ship with, unavoidable
// because a line's pronoun cannot vary with the bond level.
const DIALOGUE_IT = {
    // --- player spoken lines (DIALOGUE_DATA[sheet][*].text, by id) ---
    lines: {
        // Complaint
        C001: "Capo, mi servono minuti. Mi alleno bene tutta la settimana, poi arriva sabato e guardo dalla panchina.",
        C002: "Possiamo parlare? Non sono venuto al {club} per stare in panchina. Qualcosa deve cambiare.",
        C003: "Non chiedo miracoli, {agent}. Chiedo una possibilità vera di stare nell'undici.",
        C004: "Sono stufo di guardare da fuori, {agent}. Se il mister non mi fa giocare, trovami qualcuno che lo faccia!",
        C005: "Guarda i miei numeri in allenamento, e poi guarda chi gioca davanti a me. Non torna, e voglio la tua opinione.",
        C006: "La gente continua a chiedermi perché non gioco. Non ho una risposta. È un problema per entrambi.",
        C007: "Tra noi, non vedo il {club} andare da nessuna parte. Ho bisogno di sapere che hai un piano per me.",
        C008: "Questo non è il progetto che mi hanno venduto, {agent}. Lo spogliatoio è spento.",
        C009: "Ho dato tutto a questo club e non sono più sicuro che sia reciproco.",
        C010: "Non pensavo di dirlo mai, ma il club è cambiato. Non è più il posto per cui ho firmato.",
        C011: "Qui ho visto tutto quello che c'era da vedere. Mi serve una nuova sfida prima di spegnermi.",
        C012: "C'è qualcosa che non va al club ultimamente. Non voglio drammi, voglio solo che si sistemi.",
        C013: "Hai visto quanto prende il nuovo acquisto? Sto rendendo più di lui per metà dei soldi.",
        C014: "Il mio contratto non corrisponde più a quello che porto. Quando lo sistemiamo?",
        C015: "Non mi piace parlare di soldi, {agent}, ma qualcuno deve farlo. Il mio ingaggio è indietro rispetto allo spogliatoio.",
        C016: "I numeri non mentono, {agent}. I miei salgono e il mio ingaggio no. Sistemalo.",
        C017: "Mi imbarazza anche tirarlo fuori, ma i ragazzi dicono che sono sottopagato. Hanno ragione?",
        C018: "Un giocatore del mio profilo con questo ingaggio? Fa brutta figura. E FA male.",
        C019: "Sinceramente? Ti sento solo quando c'è un incendio. Non è per questo che ho firmato.",
        C020: "Ho bisogno di sapere che sei ancora dalla mia parte, {agent}. Ultimamente ho avuto dei dubbi.",
        C021: "Dove sei stato? Gli altri agenti chiamano i loro giocatori ogni settimana. Io ricevo silenzio.",
        C022: "Sono rimasto con te per tanto tempo, {agent}. Dimmi solo che questo significa ancora qualcosa.",
        C023: "Abbiamo superato la fase del parlare, {agent}. Fammi giocare o portami via. Sono queste le opzioni.",
        C024: "Ogni settimana su quella panchina mi costa. Voglio una soluzione adesso, non un'altra chiacchierata.",
        C025: "Basta! Presento io stesso una richiesta di trasferimento se serve questo per giocare a calcio.",
        C026: "Faccio sul serio. Comincia a cercarmi una via d'uscita, o rendo pubblico che voglio andarmene.",
        C027: "La mia decisione su questo posto è presa. Quello che mi serve da te è un piano, questa settimana.",
        C028: "L'ultima volta che abbiamo parlato non è successo niente. Trovami un contratto decente o trovo qualcuno che ci riesca.",
        C029: "Hai avuto la tua occasione di sistemare il mio contratto in silenzio. Adesso si farà rumore.",
        C030: "Ho parlato con altre agenzie, {agent}. Dammi un buon motivo per restare.",
        C031: "Per quanto mi riguarda, questo è il tuo ultimo avvertimento. Dimostrami che la mia carriera ti interessa ancora.",
        C032: "Grazie per avermi ascoltato. Aiuta più di quanto pensi.",
        C033: "Va bene. Mi sento meglio dopo averlo detto. Vediamo come vanno le prossime settimane.",
        C034: "Hai sempre saputo quando bisognava solo ascoltare. Lo apprezzo, {agent}.",
        C035: "Scusa se ti ho scaricato tutto addosso così. Ma sì, grazie.",
        C036: "Bene. Ho detto la mia. Tu non dimenticarlo.",
        C037: "D'accordo. Ti prendo in parola, {agent}.",
        C038: "Era quello che avevo bisogno di sentire. Non deludermi.",
        C039: "Affare fatto. Non mi hai mai lasciato a piedi, quindi mi fido.",
        C040: "Bene. Mettilo per scritto se serve. Conterò le settimane.",
        C041: "La tua parola mi è sempre bastata. Non farmene pentire.",
        C042: "Toh. Non mi aspettavo questa risposta. Ma forse hai ragione.",
        C043: "È dura da sentire, ma è onesta. Va bene. Metto la testa giù e lavoro.",
        C044: "È un'analisi giusta. Posso lavorarci. Grazie per essere stato diretto con me.",
        C045: "Hai ragione sui numeri. Mi concentro su quello che posso controllare.",
        C046: "Davvero? Vengo da te con un problema e mi dici che il problema sono IO?",
        C047: "Bene. Buono a sapersi da che parte stai. Questa conversazione è finita.",
        C048: "Hai un bel coraggio! Ma da che parte stai, alla fine?",
        C049: "No. NO. Non sta a te farmi la predica. Sistemalo o trovo qualcuno che lo faccia.",
        C050: "Certo. «Si sistemerà da sé.» Questa l'ho già sentita.",
        C051: "Va bene, vedremo. Ma non aspetto per sempre, {agent}.",
        C052: "Hm. Questa non è proprio una risposta, vero?",

        // Gifts
        G001: "Ah, che bel pensiero. Contano anche le piccole cose. Grazie, {agent}.",
        G002: "Te ne sei ricordato! Grazie, è un gesto bellissimo.",
        G003: "Non dovevi. Ma grazie, davvero.",
        G004: "Carino. È il pensiero che conta, suppongo.",
        G005: "Questo sì che è un regalo. Grazie, sul serio.",
        G006: "Va bene, hai gusto. Questo te lo concedo.",
        G007: "Questa è roba di classe. Aspetta che lo vedano i ragazzi.",
        G008: "È un pensiero davvero delicato. Avrà un bel posto a casa.",
        G009: "Questo è… wow. Non dovevi davvero. Grazie, {agent}.",
        G010: "Incredibile. Non so cosa dire. Grazie.",
        G011: "ECCO come si tratta una stella. Mi piace!",
        G012: "È troppo, {agent}. Davvero. Ma lo terrò come un tesoro.",
        G013: "Dopo tutti questi anni riesci ancora a sorprendermi. Grazie.",
        G014: "Un altro già? Grazie, immagino.",
        G015: "Ultimamente mi stai riempiendo troppo di regali. Perde un po' di valore, sai?",
        G016: "Due regali così vicini? Ora mi chiedo quale sia la brutta notizia.",
        G017: "Ah! Questo me lo prendo.",
        G018: "Dillo più forte la prossima volta, c'è la stampa in giro.",
        G019: "Faccio solo il mio lavoro. Ma grazie.",
        G020: "Ricevuto. Torno al lavoro.",
        G021: "È esattamente il mio piano.",
        G022: "Non sei per niente divertente. Ma va bene.",

        // Finals
        F001: "Oggi è di quelle grandi, {agent}. Lo spogliatoio ribolle. Sono contento che tu sia venuto.",
        F002: "Allora è questa. A novanta minuti da una medaglia.",
        F003: "Non avevo mai giocato una finale con il mio agente in tribuna. Nessuna pressione, allora.",
        F004: "Non riesco a stare fermo, {agent}. Voglio sfondare quel muro ADESSO.",
        F005: "Mi sono studiato il {opponent}. Decideranno i piazzati, vedrai.",
        F006: "Le finali sono il mio palcoscenico, {agent}. Oggi lo capiranno tutti.",
        F007: "Qualunque cosa accada lì fuori, grazie per essere venuto. Significa molto.",
        F008: "Oggi in tribuna c'è tutta la gente che conosco. Solo non voglio deluderli.",
        F009: "È per questo che gioco a calcio. Per giornate come questa.",
        F010: "Vincere questa con QUESTO club significherebbe tutto per me.",
        F011: "Premio partita nel contratto, medaglia di coppa sulla mensola. Prendiamoci entrambe.",
        F012: "Sì. Sì, hai ragione. Respiro profondo. Sto bene.",
        F013: "Ok. Ok. Testa libera, gambe leggere. Grazie, {agent}.",
        F014: "D'accordo. Il metodo prima dell'emozione. Ci vediamo dopo.",
        F015: "Calmo? Sto bene, {agent}. Risparmiati il discorso.",
        F016: "La calma è per la panchina. Io sono fatto per questo.",
        F017: "SÌ. Era quello che volevo sentire!",
        F018: "Guardami bene lì fuori. Il primo gol è per te.",
        F019: "Calma, calma. Mi serve la testa libera, non un grido di guerra.",
        F020: "Lo apprezzo, ma io mi preparo a modo mio.",
        F021: "Ah! QUESTA è motivazione. Affare fatto.",
        F022: "Ora stai parlando la mia lingua. Dalla per vinta.",
        F023: "Non devi comprarmi, {agent}. Ma va bene, affare fatto.",
        F024: "CE L'ABBIAMO FATTA! Ci credi? Vieni qui, {agent}!",
        F025: "Campioni! Lo sogno da quando ero bambino!",
        F026: "L'hai VISTA? Ne parleranno per anni!",
        F027: "Ce l'abbiamo fatta davvero. Tutta la squadra è stata incredibile.",
        F028: "Per questo club. Per tutta quella gente in tribuna. Sono così orgoglioso, {agent}.",
        F029: "SÌÌÌ! Nessuno credeva in noi! NESSUNO!",
        F030: "Più forte, {agent}! Stasera si festeggia!",
        F031: "Ripetilo per le telecamere!",
        F032: "Ah, grazie. Un po' troppo davanti a tutti, ma grazie.",
        F033: "Siediti, per favore, mi stai imbarazzando. Ma grazie.",
        F034: "Questo vale più di qualsiasi titolo sui giornali. Grazie.",
        F035: "Lo apprezzo. In silenzio è esattamente come piace a me.",
        F036: "Due parole in privato? Stasera? Dai, vivi un po'!",
        F037: "Da bere paga l'agente! QUESTO è servizio!",
        F038: "Generoso E furbo. I ragazzi se lo ricorderanno.",
        F039: "Così vicini. Così, così vicini. Non so cosa dire, {agent}.",
        F040: "Questa farà male per tanto tempo.",
        F041: "No. Solo… non dire niente per ora.",
        F042: "Scusa. Ho sentito di aver deluso tutti lì fuori.",
        F043: "I tifosi meritavano di meglio oggi. È questo che mi uccide.",
        F044: "Grazie per essere rimasto. La maggior parte della gente ti lascia solo con questo.",
        F045: "Sono contento che tu sia qui. Davvero.",
        F046: "Lo apprezzo, ma adesso ho voglia di stare un po' da solo.",
        F047: "Sì. Ti chiamo fra un paio di giorni. Grazie per aver capito.",
        F048: "Scelta giusta. Stasera non sono di compagnia.",
        F049: "Già. Tutti se ne vanno dopo una sconfitta. Annotato.",
        F050: "Hai ragione. La prossima stagione inizia domani. Si riparte.",
        F051: "Esatto. Le sconfitte sono dati. Ne usciremo migliori.",
        F052: "La prossima stagione? Abbiamo APPENA perso, {agent}. Leggi l'aria.",
        F090: "Oggi abbiamo fatto tutto bene, {agent}. Solo non è bastato — il titolo è andato per l'altro risultato.",
        F091: "Abbiamo vinto e ci è sfuggito comunque. Così vicini. Non riesco a credere che sia finita.",
        F092: "La nostra parte è fatta, abbiamo risposto. Ci ha ucciso la partita che non potevamo controllare.",

        // Farewell (retirement)
        W001: "Ecco, {agent}. È tutto. Scarpini appesi al chiodo. Grazie per il lavoro di tutti questi anni.",
        W002: "Allora è ufficiale. Ritiro. Abbiamo avuto alti e bassi, ma abbiamo portato a termine il lavoro.",
        W003: "Che sensazione strana, {agent}. Non ci sono più giornate di campionato. Sono contento che tu ci sia stato per buona parte del viaggio.",
        W004: "Allora quello era l'ultimo fischio. Grazie per questi anni, {agent}. Ti sei comportato bene con me più spesso che no.",
        W005: "Sai, di tutte le persone nel calcio, sei uno dei pochi che mi mancherà davvero. Che viaggio abbiamo fatto.",
        W006: "Continuo a pensare a tutto quello che abbiamo passato insieme. Contratti, trasferimenti, tutto. Grazie, amico mio.",
        W007: "Prima di tutto: la mia partita d'addio. Prima fila, ospite d'onore. Non si discute. Sei stato famiglia in tutto questo.",
        W008: "Mi hanno chiesto chi ha contato più nella mia carriera. Ho detto la mia famiglia. E ho detto il tuo nome nella stessa frase, {agent}.",
        W009: "Una carriera da paura, è vero. E non avrei potuto farne metà senza di te.",
        W010: "Si ricorderanno dei gol. Tu assicurati solo che scrivano bene il mio nome nei libri dei record.",
        W011: "È stato un bel percorso. Possiamo essere soddisfatti entrambi.",
        W012: "Questo vale più dei trofei, sinceramente. Grazie di tutto.",
        W013: "Smettila, mi fai commuovere. Grazie. Di tutto.",
        W014: "Siamo rimasti uniti, vero? Attraverso tutto. È una cosa rara in questo ambiente.",
        W015: "Mi stai facendo piangere. Sono così contento di averti incontrato!",
        W016: "Significa tantissimo per me che tu ci sia stato dall'inizio alla fine!",

        // Check-in
        K001: "Ciao {agent}! Tempismo perfetto, ho appena finito l'allenamento. Cosa hai in mente?",
        K002: "Guarda chi si vede. Tutto bene, o si parla di lavoro?",
        K003: "Hai chiamato, sono qui. Il caffè però lo paghi tu.",
        K004: "Fai in fretta, ho la palestra. Scherzo. Più o meno. Che succede?",
        K005: "Vieni a vedere come sta il tuo cliente preferito? Mossa intelligente.",
        K006: "Fa sempre piacere quando passi, {agent}. Davvero.",
        K007: "Entra, entra. Fa bene vedere una faccia conosciuta.",
        K008: "Famiglia? Per adesso ci sono solo io, sinceramente. Il calcio si prende tutto quello che ho.",
        K009: "Solo io, i miei scarpini e una valigia. Per ora mi va bene così.",
        K010: "La mia metà mi tiene con i piedi per terra. Non potrei fare niente di tutto questo da solo.",
        K011: "I bambini sono tutto, {agent}. Ogni partita che gioco è per loro.",
        K012: "I piccoli comandano in casa. La cosa più bella che mi sia capitata.",
        K013: "Ultimamente? Sono in fissa con {hobby}. Mi tiene la testa tranquilla tra le partite.",
        K014: "Mi ritaglio del tempo per {hobby}. Recupero per la testa, non solo per le gambe.",
        K015: "Il solito, sinceramente. Allenamento, casa, si ricomincia. Sto bene.",
        K016: "Da bambino? Il {favclub}. Mio padre mi portò a una partita una volta e fu deciso.",
        K017: "Facile. Il {favclub}. Avevo i poster, le maglie, tutto.",
        K018: "Il {favclub}, sempre. Certe cose non cambiano, dovunque tu giochi.",
        K019: "Adoro il {favclub}! Non riesco a stare fermo quando giocano.",
        K020: "È il {favclub}. Mia nonna ha l'abbonamento da 52 anni, e ci ha tirato dentro tutta la famiglia.",
        K021: "Sinceramente? Un giorno voglio {ambition}. È quello il sogno.",
        K022: "Tra noi: voglio {ambition}. E voglio che lo vedano tutti.",
        K023: "Mi sono fissato un solo obiettivo: {ambition}. Tutto quello che faccio punta lì.",
        K024: "Se un giorno riuscissi a {ambition}, sarebbe un traguardo incredibile per me e per i miei.",
        K025: "Ho bisogno di {ambition}. E voglio sempre essere in corsa per i titoli!",
        K026: "Voglio {ambition}. Ma la cosa più importante è avere gli amici e la famiglia con me a ogni passo.",
        K027: "Lo spogliatoio va bene. Qualche ego grosso, ma fammene vedere uno senza.",
        K028: "Sinceramente, un gruppo di ragazzi eccezionale. Il migliore di cui abbia fatto parte.",
        K029: "C'è uno che continua a prendermi il posto nel parcheggio. Ci siamo già detti qualcosa.",
        K030: "Sinceramente, sento che i miei compagni non apprezzano abbastanza la mia eccellenza…",
        K031: "Ah! È una festa per la maggior parte del tempo, e sai che il DJ sono io!",
        K032: "Mi sento proprio a casa qui! Per adesso non vedo nessun motivo per andarmene.",
        K033: "Mi sento proprio a casa qui! Per adesso non vedo nessun motivo per andarmene.",
        K034: "Abbiamo un paio di serpi a due facce tra noi… Sempre a parlare dietro le spalle degli altri.",
        K035: "Ci manca una vera coesione in questo momento… Credo che l'allenatore abbia messo insieme una rosa di mercenari.",
        K036: "A volte mi guardo attorno e mi sento così fortunato a fare parte di questa squadra incredibile! Grazie per avermelo reso possibile.",
        K037: "Ho fatto tanti amici nel tempo che sono in questo club. Mi sento davvero fortunato.",
        K038: "Ah, solo per sentire come sto? Lo apprezzo. Sinceramente.",
        K039: "Nessun secondo fine? È la prima volta, da parte di un agente. Mi piace.",
        K040: "È gentile da parte tua. A volte qui si sta soli, sai?",
        K041: "Che bello vederti, {agent}! Di cosa volevi parlare?",
        K042: "Ciao, come stai? Spero che non sia venuto a chiedere soldi! Scherzo, ovviamente. Che succede?",
        K043: "È bello che ti sia fatto sentire, di cosa volevi parlarmi?",

        // Moments
        M001: "I miei primi minuti in prima squadra, {agent}! Hai visto? Ho ancora la maglia addosso. Non me la toglierò.",
        M002: "Ho giocato davvero. Una vera partita in prima squadra. Continuo ad aspettare che qualcuno mi dica che è stato un errore.",
        M003: "PRIMO GOL! L'hai visto? Avrò già guardato il video cinquanta volte.",
        M004: "Finalmente è entrata. Sembra irreale, sinceramente.",
        M005: "TRE! Una tripletta, {agent}! Mi hanno dato il pallone della partita e tutto!",
        M006: "Una tripletta. Il pallone della partita va incorniciato. Forse anche gli scarpini.",
        M007: "{milestone}. L'ho appena visto sul programma della partita. Come passa il tempo, eh?",
        M008: "{milestone}. Un bel numero. Ora al prossimo.",
        M009: "{milestone}. E tu c'eri per la maggior parte di questi, {agent}.",
        M010: "Il mio primo contratto da professionista, {agent}! Firmato e tutto. Adesso è reale, vero?",
        M011: "Continuo a rileggere il contratto. Io. Calciatore professionista.",
        M012: "È fatta, {agent}. {newclub}. Nuovo capitolo. Grazie per averlo chiuso.",
        M013: "{newclub}! Città nuova, campionato nuovo, tutto nuovo. È per questo che vivo.",
        M014: "{newclub}, allora. Un grande cambiamento per me. Mi fido che sia quello giusto.",
        M015: "Devo dirti una cosa. Il {newclub} era IL MIO club da bambino. Hai appena realizzato il sogno di un ragazzino. Non lo dimenticherò. Mai.",
        M016: "Sapevi cosa significava per me il {newclub}. È la cosa più grande che qualcuno abbia fatto per la mia carriera. Grazie.",
        M017: "Ti ricordi cosa ti avevo detto di volere? {ambition}? … Fatto. Ce l'abbiamo fatta davvero.",
        M018: "{ambition}. L'ho detto e l'ho fatto. E tu hai contribuito, {agent}. Onore al merito.",
        M019: "Dicono {weeks} settimane, {agent}. Adesso non riesco nemmeno a guardare i miei scarpini.",
        M020: "LO SAPEVO che quell'intervento stava arrivando. {weeks} settimane. Sono furioso.",
        M021: "{weeks} settimane fuori. Ho già chiesto il programma di riabilitazione. Però brucia.",
        M022: "Ah, grazie. Giornate come questa ripagano di tutto.",
        M023: "Finalmente qualcuno lo dice come sta!",
        M024: "Va bene, va bene. Una serata a festeggiare e poi si torna alla normalità.",
        M025: "Hai ragione. Testa bassa, prossimo obiettivo.",
        M026: "D'accordo. Si festeggia stasera, si azzera domani.",
        M027: "Senza far rumore? Va bene. Ma il video me lo guardo in loop.",
        M028: "Sei venuto fin qui? Questo… significa molto, {agent}.",
        M029: "Non dovevi venire. Sono contento che l'hai fatto.",
        M030: "I fiori sono arrivati. Bel pensiero. Mandami anche qualche partita da guardare.",
        M031: "Prima che vai. Ti ho preso una cosa. Non si discute, è già pagata. {thing}. Te la sei meritata dieci volte.",
        M032: "Mio padre diceva sempre: prenditi cura di chi si prende cura di te. Quindi tieni. {thing}. Grazie, {agent}.",
        M033: "L'ho scelta io stesso. {thing}! Solo il meglio per il mio agente, ovviamente.",
        M034: "Non è gran cosa, ma… {thing}. Per tutto quello che fai e che nessuno vede.",
        M035: "Bene. Ogni volta che la guardi, ricordati che questa l'abbiamo fatta insieme.",
        M036: "Era tutto quello che volevo sentire. Ci prendiamo cura l'uno dell'altro, sempre.",
        M037: "Ah! Non cambiare mai, {agent}. Mai.",
        M038: "Vedi, è PER QUESTO che ci troviamo bene.",
        M039: "Voglio che ci sia anche tu per {occasion}. Non come mio agente. Come amico. Dimmi che vieni.",
        M040: "Fra poco è {occasion}. Cerchia ristretta, solo famiglia e le persone che contano. E tu sei dentro, {agent}.",
        M041: "{occasion}. Sarà L'evento dell'estate. Sei sulla lista, ovviamente.",
        M042: "Vieni? Significa tantissimo. Ci vediamo lì!",
        M043: "Davvero? Io… grazie. Non sarebbe la stessa cosa senza di te.",
        M044: "Non ce la fai? Che peccato. Ma è molto generoso, grazie.",
        M045: "Già. Agenda piena, capisco. … Capisco.",
    },

    // --- what the AGENT says when you pick a choice (Dialogue.SAY, keyed "scene:choice") ---
    say: {
        'complaint:listen': "Parlami. Qualunque cosa sia, voglio sentirla, tutta.",
        'complaint:promise': "Bene. Ecco cosa farò a riguardo.",
        'complaint:pushback': "Ti sento. Ma lascia che sia diretto con te un attimo.",
        'complaint:deflect': "Non corriamo troppo. Dagli ancora un po' di tempo.",
        'promise:move': "Lascia fare a me. Ti troverò la sistemazione giusta — il club giusto, non un club qualsiasi.",
        'promise:newContract': "Ti ottengo il contratto che meriti in questo club. Dammi un po' di tempo.",
        'promise:playingTime': "Parlo seriamente con l'allenatore del tuo minutaggio. Lo sistemiamo.",
        'promise:renegotiateRep': "E io prenderò meno dalla mia parte perché accada. È quanto ti sostengo.",
        'gift:praise': "Te lo sei meritato. Tutto. Che nessuno ti dica il contrario.",
        'gift:modest': "Non è niente, davvero. Volevo solo che sapessi che sto attento.",
        'prematch:calm': "Respira. Il lavoro l'hai già fatto tutto. Vai e gioca la tua partita.",
        'prematch:fireup': "Questa è la tua serata. Esci e prenditela — non lasciare niente lì.",
        'prematch:bonus': "Ti dico una cosa: vinci questa, e c'è un extra per te.",
        'bonus:small': "Vinci stasera e c'è un regalo per te. Parola mia.",
        'bonus:medium': "Vinci questa e mi occupo di te come si deve — è una promessa.",
        'bonus:large': "Portala a casa e farò in modo che ne valga davvero la pena. Parola mia.",
        'postwin:toast': "Vieni qui — quella è stata speciale. Godiamoci questa.",
        'postwin:quiet': "Splendido lavoro. Ti lascio tornare dai ragazzi.",
        'postwin:tab': "Stasera pago tutto io. Te lo sei meritato e oltre.",
        'postloss:sit': "Siediti con me un minuto. Adesso brucia — non brucerà per molto.",
        'postloss:space': "Ti lascio in pace. Testa alta. Si riparte.",
        'postloss:speech': "Ascoltami. Una partita non ti definisce. Non ti azzardare a dimenticarlo.",
        'farewell:career': "Che carriera è stata. Dovresti essere fiero di ogni singolo minuto.",
        'farewell:personal': "Dimentica il calcio un secondo — sono solo contento di averti conosciuto.",
        'checkin:q-life': "Allora, come vanno le cose fuori dal campo? Tutto bene a casa?",
        'checkin:q-club': "Come ti stai ambientando al club? Vai d'accordo con tutti?",
        'checkin:q-ambition': "Dove vuoi arrivare con tutto questo? A cosa puntiamo davvero?",
        'checkin:q-room': "Con chi stai in spogliatoio ultimamente?",
        'checkin:q-none': "Nessun secondo fine oggi. Volevo solo vedere come stavi.",
        'moment:praise': "È stato un bel momento. Assaporalo — te lo sei meritato.",
        'moment:modest': "Silenziosamente brillante, quella. Bravo.",
        'injury:there': "Vengo a trovarti. Non passerai da questa cosa da solo.",
        'injury:flowers': "Ti mando qualcosa — solo perché sappia che ti penso.",
        'thanks:cherish': "Questo significa molto per me. Lo terrò, davvero.",
        'thanks:banter': "Non dovevi, sentimentale che sei. Ma grazie, davvero.",
        'invite:attend': "Non me lo perderei per niente al mondo. Sarò lì, in tribuna.",
        'invite:gift': "Non posso esserci di persona, ma lascia che mandi qualcosa per celebrare la giornata.",
        'invite:decline': "Questa volta non posso esserci — ma ti sono vicino, lo sai.",
    },

    // --- choice buttons (keyed "scene|choice") ---
    choices: {
        'complaint|listen': { label: "Ascoltarlo", hint: "Sicuro. Vuole essere ascoltato." },
        'complaint|promise': { label: "Fargli una promessa", hint: "Apre una promessa con una scadenza vera." },
        'complaint|pushback': { label: "Contraddirlo", hint: "Dirgli che sbaglia. Rischioso, dipende dall'uomo." },
        'complaint|deflect': { label: "Minimizzare", hint: "Guadagna tempo. Potrebbe legartela al dito." },
        'gift|praise': { label: "Te lo sei meritato" },
        'gift|modest': { label: "Testa bassa e gioca" },
        'prematch|calm': { label: "Calmarlo", hint: "Placare i nervi prima della partita più importante del suo anno." },
        'prematch|fireup': { label: "Caricarlo", hint: "Fargli ribollire il sangue." },
        'prematch|bonus': { label: "Promettere un premio partita", hint: "Scegli un regalo che riceve se alzano il trofeo. Non costa nulla se perdono." },
        'postwin|toast': { label: "Elogiarlo davanti a tutti", hint: "Lode pubblica. A qualcuno piace, altri si imbarazzano." },
        'postwin|quiet': { label: "Due parole in privato", hint: "Solo voi due, lontano dal rumore." },
        'postwin|tab': { label: "Pagare tu stasera", hint: "Ti costa, significa molto." },
        'postloss|sit': { label: "Restare con lui", hint: "Non dire niente. Solo restare." },
        'postloss|space': { label: "Lasciargli spazio", hint: "Certe ferite si chiudono da sole." },
        'postloss|speech': { label: "La prossima stagione si riparte", hint: "Diretti a quello che viene dopo." },
        'farewell|career': { label: "A una carriera da paura" },
        'farewell|personal': { label: "All'uomo, non solo al giocatore" },
        'checkin|q-life': { label: "Chiedergli della vita fuori dal calcio" },
        'checkin|q-club': { label: "Chiedergli del suo club del cuore" },
        'checkin|q-ambition': { label: "Chiedergli delle sue ambizioni" },
        'checkin|q-room': { label: "Chiedergli dello spogliatoio" },
        'checkin|q-none': { label: "Niente in particolare", hint: "A volte è quello che dice di più." },
        'moment|praise': { label: "Festeggiare con lui" },
        'moment|modest': { label: "Senza far rumore" },
        'injury|there': { label: "Andare a trovarlo" },
        'injury|flowers': { label: "Mandare dei fiori" },
        'thanks|cherish': { label: "La terrò come un tesoro" },
        'thanks|banter': { label: "Era ora che mi ripagassi" },
        'invite|attend': { label: "Liberare l'agenda, ci sarai", hint: "Un fine settimana del tuo tempo. Conta più di qualsiasi regalo." },
        'invite|gift': { label: "Mandare un regalo generoso", hint: "Non puoi andarci, ma il pensiero arriva." },
        'invite|decline': { label: "Rifiutare con garbo", hint: "Se ne accorgerà." },
    },

    // --- discovered "vocabulary": hobbies, keepsakes and occasions, keyed by the English value ---
    // Stored on the player in English, so they are localised at fill() time. Hobbies KEEP their
    // article ("il golf", "i videogiochi"), because the two dialogue lines that use them are full
    // sentences: "in fissa con {hobby}" / "tempo per {hobby}". That forced the UI's terse cd.into
    // off "gli piace {hobby}", which cannot agree in number ("gli piace i videogiochi"), and onto
    // "passione: {hobby}" — Italian needs this where the other languages did not.
    vocab: {
        'golf': "il golf",
        'fishing': "la pesca",
        'gaming': "i videogiochi",
        'chess': "gli scacchi",
        'cooking': "la cucina",
        'classic cars': "le auto d'epoca",
        'photography': "la fotografia",
        'making music': "fare musica",
        'padel': "il padel",
        'poker': "il poker",
        'a signed shirt from his debut': "una maglia autografata del suo debutto",
        'a watch with a date engraved on the back': "un orologio con una data incisa sul retro",
        'a framed photo of the two of you at his first signing': "una foto incorniciata di voi due alla sua prima firma",
        'the match ball from his best game, signed by the whole squad': "il pallone della sua miglior partita, firmato da tutta la rosa",
        'a bottle from a vineyard he part-owns': "una bottiglia da una vigna di cui è comproprietario",
        'my wedding': "il mio matrimonio",
        "the little one's christening": "il battesimo del piccolo",
        'a gift': "un regalo",
    },

    // --- ambitions: a pronoun-free infinitive phrase, so it reads both as a label and inside a
    // spoken line ("voglio {ambition}", "{ambition}? Fatto."). The fallbacks carry whatever article
    // their template needs: "in {league}", "per il {club}" -> bare fallback, "a {fav}".
    amb: {
        types: {
            league: "giocare un giorno in {league}",
            dreamclub: "giocare un giorno per {club}",
            boyhood: "chiudere dove tutto è iniziato, a {fav}",
            title: "vincere uno scudetto",
            cup: "alzare una coppa",
            europe: "giocare in Europa",
            goals: "arrivare a {target} gol in carriera",
            topflight: "giocare in uno dei cinque grandi campionati",
            abroad: "giocare all'estero",
        },
        dflt: "arrivare in cima",
        favFallback: "casa mia",
        leagueFallback: "categorie più alte",
        clubFallback: "un grande club",
    },

    // --- milestone labels, frozen into the line when the moment is queued (the player is speaking) ---
    mile: {
        apps: "{n} presenze",
        goals: "{n} gol in carriera",
    },

    // --- the cash thank-you gift, filled into {thing} ---
    envelope: "una busta. Dentro: €{amt} per l'agenzia",
};
if (typeof module !== 'undefined' && module.exports) module.exports = { DIALOGUE_IT };
