// German translations for the dialogue system, keyed by the SAME stable line ids as
// js/dialogue-data.js (the English source, generated from dialogue_lines.xlsx). Any id missing
// here falls back to the English workbook text — so this file may lag the workbook safely.
// dialogue.js picks these when I18n.locale === 'de' (see Dialogue._deTxt / choiceLabel).
// Tone: the player↔agent relationship is close and personal, so these use informal "du"
// (the business mail/agency text stays formal "Sie").
const DIALOGUE_DE = {
    // --- player spoken lines (DIALOGUE_DATA[sheet][*].text, by id) ---
    lines: {
        // Complaint
        C001: "Boss, ich brauche Spielzeit. Ich trainiere die ganze Woche stark, dann kommt der Samstag und ich schaue von der Bank zu.",
        C002: "Können wir reden? Ich bin nicht zu {club} gekommen, um auf der Bank zu sitzen. Irgendetwas muss sich ändern.",
        C003: "Ich verlange keine Wunder, {agent}. Ich verlange eine faire Chance auf einen Platz in der Elf.",
        C004: "Ich habe genug davon, von draußen zuzusehen, {agent}. Wenn der Trainer mich nicht spielen lässt, dann finde mir jemanden, der es tut!",
        C005: "Sieh dir meine Trainingswerte an und dann, wer vor mir spielt. Das passt nicht zusammen, und ich will deine Einschätzung dazu.",
        C006: "Alle fragen mich ständig, warum ich nicht spiele. Ich habe keine Antwort. Das ist ein Problem für uns beide.",
        C007: "Unter uns: Ich sehe {club} nicht vorankommen. Ich muss wissen, dass du einen Plan für mich hast.",
        C008: "Das ist nicht das Projekt, das man mir verkauft hat, {agent}. Die Kabine wirkt kraftlos.",
        C009: "Ich habe diesem Klub alles gegeben, und ich bin mir nicht mehr sicher, ob das auf Gegenseitigkeit beruht.",
        C010: "Ich hätte nie gedacht, dass ich das mal sage, aber der Klub hat sich verändert. Es ist nicht mehr der Ort, bei dem ich unterschrieben habe.",
        C011: "Ich habe hier alles gesehen, was es zu sehen gibt. Ich brauche eine neue Herausforderung, bevor ich einroste.",
        C012: "In letzter Zeit stimmt etwas nicht beim Klub. Ich will kein Drama, ich will es nur geregelt haben.",
        C013: "Hast du gesehen, was der Neuzugang verdient? Ich bin besser als er, für das halbe Geld.",
        C014: "Mein Vertrag passt nicht mehr zu dem, was ich leiste. Wann bringen wir das in Ordnung?",
        C015: "Ich rede nicht gern über Geld, {agent}, aber irgendjemand muss es. Mein Gehalt hinkt der Kabine hinterher.",
        C016: "Zahlen lügen nicht, {agent}. Meine steigen, mein Gehalt nicht. Regel das.",
        C017: "Es ist mir unangenehm, das überhaupt anzusprechen, aber die Jungs sagen, ich sei unterbezahlt. Haben sie recht?",
        C018: "Ein Spieler meines Formats mit diesem Gehalt? Das sieht schlecht aus. Es IST schlecht.",
        C019: "Ehrlich? Ich höre nur von dir, wenn irgendwo Feuer ist. Dafür habe ich nicht unterschrieben.",
        C020: "Ich muss wissen, dass du weiter hinter mir stehst, {agent}. In letzter Zeit hatte ich meine Zweifel.",
        C021: "Wo warst du?! Andere Berater rufen ihre Spieler jede Woche an. Ich bekomme Funkstille.",
        C022: "Ich halte dir schon lange die Treue, {agent}. Sag mir einfach, dass das noch etwas bedeutet.",
        C023: "Wir sind übers Reden hinaus, {agent}. Bring mich zum Spielen oder bring mich hier weg. Das sind die Optionen.",
        C024: "Jede Woche auf dieser Bank kostet mich etwas. Ich will jetzt eine Lösung, nicht noch ein Gespräch.",
        C025: "Es reicht! Ich stelle selbst einen Transferantrag, wenn es das braucht, um Fußball zu spielen.",
        C026: "Jetzt ist es mir ernst. Fang an, nach einem Ausweg zu suchen, oder ich mache öffentlich, dass ich weg will.",
        C027: "Meine Meinung über diesen Ort steht fest. Was ich von dir brauche, ist ein Plan, diese Woche.",
        C028: "Letztes Mal, als wir geredet haben, ist nichts passiert. Besorg mir einen anständigen Vertrag, oder ich finde jemanden, der es kann.",
        C029: "Du hattest deine Chance, meinen Vertrag in aller Ruhe zu regeln. Jetzt wird es laut.",
        C030: "Ich habe mit anderen Agenturen gesprochen, {agent}. Gib mir einen guten Grund zu bleiben.",
        C031: "Das ist meine letzte Warnung, so viel steht fest. Zeig mir, dass dir meine Karriere noch wichtig ist.",
        C032: "Danke, dass du mir zugehört hast. Das hilft mehr, als du denkst.",
        C033: "Okay. Es geht mir besser, jetzt wo ich es ausgesprochen habe. Schauen wir, wie die nächsten Wochen laufen.",
        C034: "Du wusstest schon immer, wann man einfach nur zuhören muss. Danke, {agent}.",
        C035: "Tut mir leid, dass ich dich so vollgeladen habe. Aber ja, danke.",
        C036: "Gut. Ich habe meinen Standpunkt gesagt. Vergiss ihn nur nicht.",
        C037: "In Ordnung. Ich nehme dich beim Wort, {agent}.",
        C038: "Genau das musste ich hören. Enttäusch mich nicht.",
        C039: "Abgemacht. Du hast mich noch nie hängen lassen, also vertraue ich darauf.",
        C040: "Gut. Bring es notfalls zu Papier. Ich werde die Wochen zählen.",
        C041: "Dein Wort hat mir immer gereicht. Lass mich das nicht bereuen.",
        C042: "Hm. Diese Antwort habe ich nicht erwartet. Aber vielleicht hast du recht.",
        C043: "Das ist schwer zu hören, aber es ist ehrlich. Okay. Ich beiße mich durch.",
        C044: "Das ist eine faire Analyse. Damit kann ich arbeiten. Danke, dass du ehrlich zu mir bist.",
        C045: "Du hast recht mit den Zahlen. Ich konzentriere mich auf das, was ich beeinflussen kann.",
        C046: "Ernsthaft? Ich komme mit einem Problem zu dir, und du sagst mir, ICH sei das Problem?",
        C047: "Wow. Gut zu wissen, wie du stehst. Dieses Gespräch ist beendet.",
        C048: "Du hast vielleicht Nerven! Auf wessen Seite stehst du überhaupt?!",
        C049: "Nein. NEIN. Du hast mir keine Predigt zu halten. Regel es, oder ich finde jemanden, der es tut.",
        C050: "Klar. „Das regelt sich von selbst.“ Das habe ich schon mal gehört.",
        C051: "Sicher, mal sehen. Aber ich warte nicht ewig, {agent}.",
        C052: "Hm. Das ist nicht wirklich eine Antwort, oder?",
        // Gifts
        G001: "Ah, schön. Kleinigkeiten zählen auch. Danke, {agent}.",
        G002: "Du hast daran gedacht! Danke, das ist eine nette Geste.",
        G003: "Das hättest du nicht tun müssen. Aber danke, wirklich.",
        G004: "Niedlich. Der Gedanke zählt, nehme ich an.",
        G005: "Das ist mal ein richtiges Geschenk. Danke, im Ernst.",
        G006: "Okay, du hast Geschmack. Das lasse ich dir.",
        G007: "Das ist erste Klasse. Warte, bis die Jungs das sehen.",
        G008: "Das ist wirklich aufmerksam. Das bekommt zu Hause einen guten Platz.",
        G009: "Das ist... wow. Das hättest du wirklich nicht tun müssen. Danke, {agent}.",
        G010: "Unglaublich. Ich weiß nicht, was ich sagen soll. Danke.",
        G011: "SO behandelt man einen Star. Ich liebe es!",
        G012: "Das ist zu viel, {agent}. Ehrlich. Aber ich werde es in Ehren halten.",
        G013: "Nach all den Jahren überraschst du mich immer noch. Danke.",
        G014: "Schon wieder eins? Danke, schätze ich.",
        G015: "Du verwöhnst mich in letzter Zeit. Das nimmt ihm ein bisschen den Glanz, weißt du.",
        G016: "Zwei Geschenke so kurz hintereinander? Jetzt frage ich mich, was die schlechte Nachricht ist.",
        G017: "Ha! Das nehme ich.",
        G018: "Sag das nächstes Mal lauter, es ist Presse da.",
        G019: "Ich mache nur meinen Job. Aber danke.",
        G020: "Verstanden. Zurück an die Arbeit.",
        G021: "Genau mein Plan.",
        G022: "Du bist ein Spielverderber. Aber gut.",
        // Final
        F001: "Großes Ding heute, {agent}. In der Kabine brodelt es. Schön, dass du gekommen bist.",
        F002: "Das ist es also. Neunzig Minuten von einer Medaille entfernt.",
        F003: "Habe noch nie ein Finale mit meinem Berater auf der Tribüne gespielt. Dann mal kein Druck.",
        F004: "Ich kann nicht still sitzen, {agent}. Ich will JETZT durch diese Wand rennen.",
        F005: "Ich habe {opponent} studiert. Standards werden es entscheiden, pass auf.",
        F006: "Finals sind meine Bühne, {agent}. Heute erfahren es alle.",
        F007: "Was da draußen auch passiert, danke fürs Kommen. Das bedeutet mir viel.",
        F008: "Jeder, den ich kenne, ist heute auf der Tribüne. Ich will sie nur nicht enttäuschen.",
        F009: "Dafür spiele ich Fußball. Für Tage wie diesen.",
        F010: "Das mit DIESEM Klub zu gewinnen, würde mir alles bedeuten.",
        F011: "Siegprämie im Vertrag, Pokalmedaille im Regal. Holen wir uns beides.",
        F012: "Ja. Ja, du hast recht. Tief durchatmen. Mir geht's gut.",
        F013: "Okay. Okay. Kopf klar, Beine locker. Danke, {agent}.",
        F014: "Einverstanden. Prozess vor Emotion. Bis nachher.",
        F015: "Ruhig? Mir geht's gut, {agent}. Spar dir die Rede.",
        F016: "Ruhe ist was für die Bank. Ich bin für sowas gemacht.",
        F017: "JA. Genau das wollte ich hören!",
        F018: "Schau mir da draußen zu. Das erste Tor ist für dich.",
        F019: "Ganz ruhig, ganz ruhig. Ich brauche einen klaren Kopf, keinen Schlachtruf.",
        F020: "Ich weiß es zu schätzen, aber ich bereite mich auf meine eigene Art vor.",
        F021: "Ha! DAS ist mal Motivation. Abgemacht.",
        F022: "Jetzt sprichst du meine Sprache. Betrachte es als gewonnen.",
        F023: "Du musst mich nicht bestechen, {agent}. Aber gut, abgemacht.",
        F090: "Wir haben heute alles richtig gemacht, {agent}. Es hat einfach nicht gereicht — der Titel ist durch das andere Ergebnis weg.",
        F091: "Wir gewinnen und er entgleitet uns trotzdem. So knapp. Ich kann nicht glauben, dass es vorbei ist.",
        F092: "Unseren Teil haben wir erledigt — wir haben unseren Job gemacht. Es ist das Spiel, das wir nicht in der Hand hatten, das uns umgebracht hat.",
        F024: "WIR HABEN ES GESCHAFFT! Kannst du das glauben?! Komm her, {agent}!",
        F025: "Meister! Davon träume ich, seit ich ein Kind bin!",
        F026: "Hast du DAS gesehen?! Davon werden sie noch Jahre reden!",
        F027: "Wir haben es tatsächlich geschafft. Das ganze Team war überragend.",
        F028: "Für diesen Klub. Für alle auf diesen Rängen. Ich bin so stolz, {agent}.",
        F029: "JAAA! Niemand hat an uns geglaubt! NIEMAND!",
        F030: "Lauter, {agent}! Heute Abend wird gefeiert!",
        F031: "Sag es noch mal für die Kameras!",
        F032: "Ha, danke. Ein bisschen viel vor allen Leuten, aber danke.",
        F033: "Setz dich bitte hin, du bringst mich in Verlegenheit. Aber danke.",
        F034: "Das bedeutet mehr als jede Schlagzeile. Danke.",
        F035: "Weiß ich zu schätzen. Ganz leise ist genau, wie ich es mag.",
        F036: "Ein leises Wort? Heute Abend? Komm schon, genieß das Leben!",
        F037: "Drinks gehen auf den Berater! DAS nenne ich Service!",
        F038: "Großzügig UND clever. Die Jungs werden sich daran erinnern.",
        F039: "So knapp. So, so knapp. Ich weiß nicht, was ich sagen soll, {agent}.",
        F040: "Das wird noch lange wehtun.",
        F041: "Nicht. Sag einfach... sag jetzt noch nichts.",
        F042: "Tut mir leid. Ich hatte das Gefühl, ich hätte alle im Stich gelassen da draußen.",
        F043: "Die Fans hätten heute Besseres verdient. Das ist es, was mich fertigmacht.",
        F044: "Danke, dass du geblieben bist. Die meisten lassen einen einfach damit allein.",
        F045: "Ich bin froh, dass du hier bist. Wirklich.",
        F046: "Ich weiß es zu schätzen, aber ich will gerade irgendwie allein sein.",
        F047: "Ja. Ich melde mich in ein paar Tagen. Danke fürs Verständnis.",
        F048: "Gute Entscheidung. Ich bin heute Abend keine gute Gesellschaft.",
        F049: "Klar. Nach einer Niederlage geht immer jeder. Notiert.",
        F050: "Du hast recht. Nächste Saison beginnt morgen. Wir machen weiter.",
        F051: "Korrekt. Niederlagen sind Daten. Wir werden dadurch besser.",
        F052: "Nächste Saison? Wir haben GERADE verloren, {agent}. Lies die Situation.",
        // Farewell
        W001: "Also, {agent}. Das war's. Schuhe an den Nagel gehängt. Danke für die Arbeit über all die Jahre.",
        W002: "Dann ist es offiziell. Der Ruhestand. Wir hatten unsere Höhen und Tiefen, aber wir haben den Job erledigt.",
        W003: "Komisches Gefühl, {agent}. Keine Spieltage mehr. Ich bin froh, dass du einen guten Teil des Weges dabei warst.",
        W004: "Das war also der letzte Pfiff. Danke für die Jahre, {agent}. Du hast öfter richtig an mir gehandelt als nicht.",
        W005: "Weißt du, von allen Leuten im Fußball bist du einer der wenigen, die ich wirklich vermissen werde. Was für eine Reise.",
        W006: "Ich denke ständig an alles, was wir zusammen durchgemacht haben. Verträge, Transfers, alles. Danke, mein Freund.",
        W007: "Vor allem anderen: mein Abschiedsspiel. Erste Reihe, Ehrengast. Keine Widerrede. Du warst durch alles hindurch Familie.",
        W008: "Sie haben mich gefragt, wer in meiner Karriere am wichtigsten war. Ich sagte meine Familie. Und dich nannte ich im selben Atemzug, {agent}.",
        W009: "Eine Wahnsinnskarriere, stimmt. Und die Hälfte davon hätte ich ohne dich nicht geschafft.",
        W010: "Sie werden sich an die Tore erinnern. Sorg nur dafür, dass sie meinen Namen in den Rekordbüchern richtig schreiben.",
        W011: "Es war ein gutes Werk. Damit können wir beide zufrieden sein.",
        W012: "Das bedeutet mehr als die Trophäen, ehrlich. Danke für alles.",
        W013: "Hör auf, du bringst mich noch zum Weinen. Danke. Für alles.",
        W014: "Wir haben zusammengehalten, oder? Durch alles hindurch. Das ist selten in diesem Geschäft.",
        // Checkin
        K001: "Hey {agent}! Gutes Timing, gerade das Training beendet. Was hast du auf dem Herzen?",
        K002: "Na, schau mal, wer da ist. Alles in Ordnung, oder ist das geschäftlich?",
        K003: "Du hast angerufen, ich bin da. Kaffee geht aber auf dich.",
        K004: "Mach's kurz, ich hab gleich Gym. War Spaß. So halb. Was gibt's?",
        K005: "Kommst du deinen Lieblingsklienten besuchen? Kluger Schachzug.",
        K006: "Schön, wenn du vorbeischaust, {agent}. Wirklich.",
        K007: "Komm rein, komm rein. Tut gut, ein bekanntes Gesicht zu sehen.",
        K008: "Familie? Im Moment bin nur ich da, ehrlich. Der Fußball nimmt alles, was ich hab.",
        K009: "Nur ich, meine Schuhe und ein Koffer. Passt mir fürs Erste ganz gut.",
        K010: "Meine bessere Hälfte hält mich bei Verstand. Ich könnte das alles nicht allein.",
        K011: "Die Kinder sind alles, {agent}. Jedes Spiel, das ich spiele, ist für sie.",
        K012: "Die Kleinen bestimmen im Haus. Das Beste, was mir je passiert ist.",
        K013: "In letzter Zeit? Ich bin ganz vertieft in {hobby}. Das beruhigt meinen Kopf zwischen den Spielen.",
        K014: "Ich nehme mir Zeit für {hobby}. Erholung für den Kopf, nicht nur für die Beine.",
        K015: "Das Übliche, ehrlich. Training, Zuhause, von vorn. Ich bin zufrieden.",
        K016: "Seit ich ein Kind war? {favclub}. Mein Vater nahm mich mal mit zu einem Spiel, und das war's.",
        K017: "Einfach. {favclub}. Ich hatte die Poster, die Trikots, alles.",
        K018: "{favclub}, immer. Manche Dinge ändern sich nicht, egal wo man spielt.",
        K019: "Ehrlich? Eines Tages will ich {ambition}. Das ist der Traum.",
        K020: "Unter uns: Ich will {ambition}. Und ich will, dass es alle sehen.",
        K021: "Ich habe mir ein Ziel gesetzt: {ambition}. Alles, was ich tue, zielt darauf ab.",
        K022: "Die Kabine ist gut. Ein paar große Egos, aber zeig mir eine ohne.",
        K023: "Ehrlich, eine tolle Truppe. Die beste, in der ich je war.",
        K024: "Da ist ein Typ, der mir ständig meinen Parkplatz wegschnappt. Wir hatten schon Worte.",
        K025: "Ha, nur mal vorbeischauen? Weiß ich zu schätzen. Ehrlich.",
        K026: "Keine Absicht dahinter? Das ist eine Premiere für einen Berater. Gefällt mir.",
        K027: "Das ist nett von dir. Es wird manchmal einsam hier draußen, weißt du.",
        K028: "Schön, dich zu sehen, {agent}! Worüber wolltest du reden?",
        K029: "Hey, wie geht's? Ich hoffe, du kommst nicht um Geld betteln! Spaß natürlich, was ist los?",
        K030: "Nett, dass du dich meldest. Worüber wolltest du mit mir sprechen?",
        // Moments
        M001: "Erste Minuten bei den Profis, {agent}! Hast du's gesehen? Ich hab das Trikot noch an. Ich zieh's nicht aus.",
        M002: "Ich habe tatsächlich gespielt. Ein echtes Profispiel. Ich warte immer noch darauf, dass jemand sagt, es war ein Versehen.",
        M003: "ERSTES TOR! Hast du's gesehen?! Ich hab den Clip bestimmt schon fünfzigmal geschaut.",
        M004: "Endlich ist er für mich reingegangen. Fühlt sich unwirklich an, ehrlich.",
        M005: "DREI! Ein Hattrick, {agent}! Sie haben mir sogar den Spielball gegeben!",
        M006: "Ein Hattrick. Der Spielball wird gerahmt. Vielleicht die Schuhe auch.",
        M007: "{milestone}. Gerade im Stadionheft gesehen. Wie die Zeit vergeht, oder?",
        M008: "{milestone}. Eine schöne Zahl. Jetzt zur nächsten.",
        M009: "{milestone}. Und du warst bei den meisten dabei, {agent}.",
        M010: "Mein erster Profivertrag, {agent}! Unterschrieben und alles. Jetzt ist es echt, oder?",
        M011: "Ich lese den Vertrag immer und immer wieder. Ich. Ein Profifußballer.",
        M012: "Es ist erledigt, {agent}. {newclub}. Neues Kapitel. Danke, dass du es über die Ziellinie gebracht hast.",
        M013: "{newclub}! Neue Stadt, neue Liga, neu alles. Dafür lebe ich.",
        M014: "{newclub} wird es also. Große Veränderung für mich. Ich vertraue dir, dass es die richtige ist.",
        M015: "Ich muss dir etwas sagen. {newclub} war MEIN Klub als Kind. Du hast gerade einem kleinen Kind seinen Traum erfüllt. Das vergesse ich nie. Niemals.",
        M016: "Du wusstest, was {newclub} mir bedeutet. Das ist das Größte, was je jemand für meine Karriere getan hat. Danke.",
        M017: "Weißt du noch, was ich dir gesagt habe, dass ich will? {ambition}? ...Erledigt. Wir haben es tatsächlich geschafft.",
        M018: "{ambition}. Gesagt, getan. Und du hast geholfen, {agent}. Ehre, wem Ehre gebührt.",
        M019: "Sie sagen {weeks} Wochen, {agent}. Ich kann meine Schuhe gerade nicht mal ansehen.",
        M020: "Ich WUSSTE, dass dieser Zweikampf kommt. {weeks} Wochen. Ich bin außer mir.",
        M021: "{weeks} Wochen raus. Ich hab schon nach dem Reha-Plan gefragt. Tut trotzdem weh.",
        M022: "Ha, danke. Tage wie dieser machen alles wett.",
        M023: "Endlich sagt es mal jemand, wie es ist!",
        M024: "Schon gut, schon gut. Eine Nacht feiern, dann zurück zur Normalität.",
        M025: "Du hast recht. Kopf runter, nächste Aufgabe.",
        M026: "Einverstanden. Heute feiern, morgen neu starten.",
        M027: "Zurückhaltend? Gut. Aber ich lasse die Highlights in Dauerschleife laufen.",
        M028: "Du bist den ganzen Weg hergekommen? Das... bedeutet mir viel, {agent}.",
        M029: "Du hättest nicht kommen müssen. Ich bin froh, dass du es getan hast.",
        M030: "Die Blumen sind angekommen. Nette Geste. Schick mir auch ein paar Spiele zum Anschauen.",
        M031: "Bevor du gehst. Ich hab dir was besorgt. Keine Widerrede, es ist schon bezahlt. {thing}. Du hast es zehnmal verdient.",
        M032: "Mein Vater hat immer gesagt: Kümmere dich um die Leute, die sich um dich kümmern. Also hier. {thing}. Danke, {agent}.",
        M033: "Selbst ausgesucht. {thing}! Nur das Beste für meinen Berater, natürlich.",
        M034: "Es ist nicht viel, aber... {thing}. Für all das, was du tust und das niemand sieht.",
        M035: "Gut. Jedes Mal, wenn du es ansiehst, denk daran, dass wir das zusammen geschafft haben.",
        M036: "Genau das wollte ich hören. Wir passen aufeinander auf, immer.",
        M037: "Ha! Bleib, wie du bist, {agent}. Bleib, wie du bist.",
        M038: "Siehst du, DESHALB verstehen wir uns.",
        M039: "Ich will dich bei {occasion} dabeihaben. Nicht als mein Berater. Als Freund. Sag, dass du kommst.",
        M040: "Bald geht es zu {occasion} — nur kleiner Kreis, Familie und die Menschen, die zählen. Dazu gehörst du, {agent}.",
        M041: "Bei {occasion} — das wird DAS Event des Sommers. Du stehst auf der Liste, natürlich.",
        M042: "Du kommst? Das bedeutet mir die Welt. Wir sehen uns dort!",
        M043: "Wirklich? Ich... danke. Es wäre nicht dasselbe ohne dich.",
        M044: "Du schaffst es nicht? Schade. Aber das ist sehr großzügig, danke.",
        M045: "Klar. Voller Terminkalender, ich versteh's. ...Ich versteh's.",
        M046: "Kennst du {mate} aus meiner Kabine? Ich hab ihm gesagt, du bist der einzige Berater, den man haben sollte. Rechne mit seinem Anruf.",
        M047: "Ich hab mich bei {mate} für dich verbürgt. Blamier mich nicht, ja? Er ist ein guter Kerl.",
        M048: "{mate} hat gefragt, wer meine Karriere managt. Ich gab ihm meine ehrliche Einschätzung: du. Er ist interessiert.",
    },
    // --- what the AGENT says when you pick a choice (Dialogue.SAY, by "scene:choice") ---
    say: {
        'complaint:listen': "Rede mit mir. Was immer es ist, ich will es hören — alles.",
        'complaint:promise': "Also gut. Folgendes werde ich dagegen tun.",
        'complaint:pushback': "Ich verstehe dich. Aber lass mich einen Moment ehrlich zu dir sein.",
        'complaint:deflect': "Lass uns nichts überstürzen. Gib dem Ganzen noch etwas Zeit.",
        'promise:move': "Überlass das mir. Ich finde dir den richtigen Wechsel — den richtigen Klub, nicht irgendeinen.",
        'promise:newContract': "Ich hole dir den Vertrag, den du bei diesem Klub verdienst. Gib mir etwas Zeit.",
        'promise:playingTime': "Ich rede mal in Ruhe mit dem Trainer über deine Einsatzzeiten. Wir kriegen das hin.",
        'promise:renegotiateRep': "Und ich nehme auf meiner Seite weniger, damit es klappt. So sehr stehe ich hinter dir.",
        'gift:praise': "Das hast du dir verdient. Jedes bisschen davon — lass dir von niemandem etwas anderes einreden.",
        'gift:modest': "Es ist nichts, ehrlich. Wollte nur, dass du weißt, dass ich aufpasse.",
        'prematch:calm': "Atme. Die Arbeit hast du längst gemacht. Geh einfach raus und spiel dein Spiel.",
        'prematch:fireup': "Das ist dein Abend. Geh raus und hol ihn dir — lass nichts liegen.",
        'prematch:bonus': "Weißt du was — du gewinnst das hier, und es springt eine Kleinigkeit extra für dich raus.",
        'bonus:small': "Du gewinnst heute Abend, und es gibt ein Geschenk für dich. Mein Wort darauf.",
        'bonus:medium': "Gewinn das, und ich kümmere mich richtig um dich — das ist ein Versprechen.",
        'bonus:large': "Bring das nach Hause, und ich mach's dir mehr als wert, ganz groß. Mein Wort.",
        'postwin:toast': "Komm her — das war etwas Besonderes. Genießen wir das.",
        'postwin:quiet': "Wunderbar gemacht. Ich lass dich zurück zu den Jungs.",
        'postwin:tab': "Heute Abend geht alles auf mich. Du hast es mehr als verdient.",
        'postloss:sit': "Setz dich eine Minute zu mir. Es schmerzt jetzt — nicht mehr lange.",
        'postloss:space': "Ich lass dich in Ruhe. Kopf hoch. Wir machen weiter.",
        'postloss:speech': "Hör mir zu. Ein Spiel definiert dich nicht. Wehe, du vergisst das.",
        'farewell:career': "Was für eine Karriere das war. Du solltest auf jede einzelne Minute stolz sein.",
        'farewell:personal': "Vergiss den Fußball mal kurz — ich bin einfach froh, dass ich dich kennenlernen durfte.",
        'checkin:q-life': "Und wie läuft's abseits des Platzes? Alles gut zu Hause?",
        'checkin:q-club': "Wie lebst du dich beim Klub ein? Kommst du mit allen klar?",
        'checkin:q-ambition': "Wohin soll das alles führen? Worauf zielen wir wirklich ab?",
        'checkin:q-room': "Mit wem hängst du dieser Tage in der Kabine ab?",
        'checkin:q-none': "Heute keine Agenda. Ich wollte nur sehen, wie's dir geht.",
        'moment:praise': "Das war ein echter Moment. Sauge ihn ganz auf — du hast ihn dir verdient.",
        'moment:modest': "Ganz still brillant, das. Gut gespielt.",
        'injury:there': "Ich komme dich besuchen. Da gehst du nicht allein durch.",
        'injury:flowers': "Ich schick dir was rüber — nur damit du weißt, dass ich an dich denke.",
        'thanks:cherish': "Das bedeutet mir sehr viel. Ich behalte es, ehrlich.",
        'thanks:banter': "Das hättest du nicht tun müssen, du Weichei. Aber danke — wirklich.",
        'invite:attend': "Um nichts in der Welt würde ich das verpassen. Ich bin direkt da auf der Tribüne.",
        'invite:gift': "Ich schaff's nicht persönlich, aber lass mich etwas schicken, um den Tag zu würdigen.",
        'invite:decline': "Ich kann dieses Mal nicht dabei sein — aber ich bin in Gedanken bei dir, das weißt du.",
    },
    // --- choice buttons (DIALOGUE_DATA.choices, by "scene|choice") ---
    choices: {
        'complaint|listen': { label: "Ihn anhören", hint: "Sicher. Er will gehört werden." },
        'complaint|promise': { label: "Ein Versprechen geben", hint: "Öffnet ein Versprechen mit echter Frist." },
        'complaint|pushback': { label: "Kontern", hint: "Sag ihm, dass er falsch liegt. Riskant, hängt vom Mann ab." },
        'complaint|deflect': { label: "Herunterspielen", hint: "Verschafft Zeit. Er könnte es übelnehmen." },
        'gift|praise': { label: "Das hast du dir verdient", hint: "" },
        'gift|modest': { label: "Kopf runter und spielen", hint: "" },
        'prematch|calm': { label: "Ihn beruhigen", hint: "Beruhige die Nerven vor dem größten Spiel seines Jahres." },
        'prematch|fireup': { label: "Ihn anheizen", hint: "Bring das Blut in Wallung." },
        'prematch|bonus': { label: "Siegprämie versprechen", hint: "Wähle ein Geschenk, das er bekommt, wenn sie den Pokal holen. Kostet nichts, wenn sie verlieren." },
        'postwin|toast': { label: "Ihn vor allen hochleben lassen", hint: "Öffentliches Lob. Manche lieben es, manchen ist es unangenehm." },
        'postwin|quiet': { label: "Ein leises Wort beiseite", hint: "Nur ihr beide, abseits des Trubels." },
        'postwin|tab': { label: "Heute Abend die Rechnung übernehmen", hint: "Kostet dich was, bedeutet viel." },
        'postloss|sit': { label: "Bei ihm sitzen", hint: "Sag nichts. Bleib einfach." },
        'postloss|space': { label: "Ihm Raum geben", hint: "Manche Wunden heilen allein." },
        'postloss|speech': { label: "Nächste Saison machen wir weiter", hint: "Direkt zu dem, was kommt." },
        'farewell|career': { label: "Auf eine Wahnsinnskarriere", hint: "" },
        'farewell|personal': { label: "Auf den Menschen, nicht nur den Spieler", hint: "" },
        'checkin|q-life': { label: "Nach dem Leben abseits des Fußballs fragen", hint: "" },
        'checkin|q-club': { label: "Nach seinem Lieblingsklub fragen", hint: "" },
        'checkin|q-ambition': { label: "Nach seinen Ambitionen fragen", hint: "" },
        'checkin|q-room': { label: "Nach der Kabine fragen", hint: "" },
        'checkin|q-none': { label: "Nichts Bestimmtes", hint: "Manchmal sagt das am meisten." },
        'moment|praise': { label: "Viel Aufhebens um ihn machen", hint: "" },
        'moment|modest': { label: "Es ruhig angehen", hint: "" },
        'injury|there': { label: "Ihn persönlich besuchen", hint: "" },
        'injury|flowers': { label: "Blumen schicken", hint: "" },
        'thanks|cherish': { label: "Das werde ich in Ehren halten", hint: "" },
        'thanks|banter': { label: "Wurde ja auch mal Zeit, dass du dich revanchierst", hint: "" },
        'invite|attend': { label: "Termine freischaufeln, du bist dabei", hint: "Ein Wochenende deiner Zeit. Es bedeutet mehr als jedes Geschenk." },
        'invite|gift': { label: "Ein großzügiges Geschenk schicken", hint: "Du schaffst es nicht, aber der Gedanke kommt an." },
        'invite|decline': { label: "Höflich absagen", hint: "Er wird es merken." },
    },
    // --- discovered "vocabulary" values (hobbies, keepsakes, occasions), localized at fill time by
    //     English value → German. Occasions are dative to fit "bei/zu {occasion}" (see M039–M041). ---
    vocab: {
        golf: "Golf", fishing: "Angeln", gaming: "Gaming", chess: "Schach", cooking: "Kochen",
        'classic cars': "Oldtimer", photography: "Fotografie", 'making music': "Musikmachen", padel: "Padel", poker: "Poker",
        'a signed shirt from his debut': "ein signiertes Trikot von seinem Debüt",
        'a watch with a date engraved on the back': "eine Uhr mit einem eingravierten Datum auf der Rückseite",
        'a framed photo of the two of you at his first signing': "ein gerahmtes Foto von euch beiden bei seiner ersten Unterschrift",
        'the match ball from his best game, signed by the whole squad': "der Spielball seines besten Spiels, signiert von der ganzen Mannschaft",
        'a bottle from a vineyard he part-owns': "eine Flasche aus einem Weingut, an dem er beteiligt ist",
        'my wedding': "meiner Hochzeit",
        "the little one's christening": "der Taufe des Kleinen",
        'a gift': "ein Geschenk",
    },
    // --- ambition phrases (Dialogue.ambitionText); {league}/{club}/{fav}/{target} filled by the engine.
    //     Fits "Ich will {ambition}" (infinitive) and standalone use. ---
    amb: {
        types: {
            league: "eines Tages in {league} spielen",
            dreamclub: "eines Tages für {club} spielen",
            boyhood: "dort aufhören, wo alles begann, bei {fav}",
            title: "einen Meistertitel gewinnen",
            cup: "einen Pokal holen",
            europe: "international spielen",
            goals: "{target} Karrieretore erreichen",
            topflight: "in einer der Top-5-Ligen spielen",
            abroad: "im Ausland spielen",
        },
        dflt: "es an die Spitze schaffen",
        favFallback: "dem Klub meiner Kindheit",
        leagueFallback: "einer größeren Liga",
        clubFallback: "einem großen Klub",
    },
    // --- milestone labels (Dialogue._mileText); {n} filled by the engine ---
    mile: { apps: "{n} Einsätze", goals: "{n} Karrieretore" },
    // --- the "envelope of cash" thank-you gift (Dialogue moment 'thanks'); {amt} filled by the engine ---
    envelope: "ein Umschlag. Darin: €{amt} für die Agentur",
};
if (typeof module !== 'undefined' && module.exports) module.exports = { DIALOGUE_DE };
