// Portuguese translations for the dialogue system, keyed by the SAME stable line ids as
// js/dialogue-data.js (the English source, generated from dialogue_lines.xlsx). Any id missing
// here falls back to the English workbook text — so this file may lag the workbook safely.
// dialogue.js picks these up through Dialogue._pack() when I18n.locale === 'pt'.
//
// European Portuguese, informal "tu" both ways, as in the German, Spanish and French packs.
// This is spoken conversation between an agent and a player who know each other well; the written
// correspondence in js/i18n-pt.js stays formal. At a low bond the client still addresses you as
// "Sr. Mercer" while using "tu" — the same small tension the other packs ship with, unavoidable
// because a line's pronoun cannot vary with the bond level.
const DIALOGUE_PT = {
    // --- player spoken lines (DIALOGUE_DATA[sheet][*].text, by id) ---
    lines: {
        // Complaint
        C001: "Chefe, preciso de minutos. Treino bem toda a semana, chega o sábado e fico a ver do banco.",
        C002: "Podemos falar? Não vim para o {club} para me sentar num banco. Algo tem de mudar.",
        C003: "Não estou a pedir milagres, {agent}. Estou a pedir uma chance justa de estar no onze.",
        C004: "Estou farto de ver de fora, {agent}. Se o treinador não me põe a jogar, arranja-me alguém que o faça!",
        C005: "Olha para os meus números no treino e depois olha para quem joga à minha frente. Não bate certo, e quero a tua opinião sobre isso.",
        C006: "As pessoas não param de me perguntar porque é que não jogo. Não tenho resposta. Isso é um problema para os dois.",
        C007: "Entre nós, não vejo o {club} a ir a lado nenhum. Preciso de saber que tens um plano para mim.",
        C008: "Este não é o projeto que me venderam, {agent}. O vestiário está apagado.",
        C009: "Dei tudo a este clube e já não tenho a certeza de que seja recíproco.",
        C010: "Nunca pensei que fosse dizer isto, mas o clube mudou. Já não é o sítio pelo qual assinei.",
        C011: "Já vi tudo o que há para ver aqui. Preciso de um novo desafio antes de estagnar.",
        C012: "Há algo que não está bem no clube ultimamente. Não quero drama, só quero que se resolva.",
        C013: "Viste o que o reforço novo recebe? Estou a render mais do que ele por metade do dinheiro.",
        C014: "O meu contrato já não corresponde ao que eu dou. Quando é que resolvemos isso?",
        C015: "Não gosto de falar de dinheiro, {agent}, mas alguém tem de o fazer. O meu salário está atrasado em relação ao vestiário.",
        C016: "Os números não mentem, {agent}. Os meus sobem e o meu salário não. Resolve isso.",
        C017: "Sinto-me desconfortável até por levantar isto, mas os rapazes dizem que ganho pouco. Têm razão?",
        C018: "Um jogador do meu perfil com este salário? Fica mal. E É mau.",
        C019: "Sinceramente? Só sei de ti quando há um incêndio. Não foi para isso que assinei.",
        C020: "Preciso de saber que continuas do meu lado, {agent}. Ultimamente tenho tido dúvidas.",
        C021: "Onde é que tens andado? Outros agentes ligam aos jogadores todas as semanas. Eu recebo silêncio.",
        C022: "Estou contigo há muito tempo, {agent}. Diz-me só que isso ainda significa algo.",
        C023: "Já passámos a fase de falar, {agent}. Põe-me a jogar ou tira-me daqui. São essas as opções.",
        C024: "Cada semana naquele banco custa-me caro. Quero uma solução agora, não outra conversa.",
        C025: "Basta! Eu mesmo apresento um pedido de transferência se for isso que é preciso para jogar futebol.",
        C026: "Estou a falar a sério. Começa a procurar-me uma saída, ou torno público que quero sair.",
        C027: "A minha decisão sobre este sítio está tomada. O que preciso de ti é um plano, esta semana.",
        C028: "A última vez que falámos não aconteceu nada. Consegue-me um contrato decente ou vou encontrar alguém que consiga.",
        C029: "Tiveste a tua chance de resolver o meu contrato em silêncio. Agora vai fazer barulho.",
        C030: "Tenho andado a falar com outras agências, {agent}. Dá-me uma boa razão para ficar.",
        C031: "No que me diz respeito, este é o teu último aviso. Mostra-me que a minha carreira ainda te importa.",
        C032: "Obrigado por me ouvires. Ajuda mais do que imaginas.",
        C033: "Está bem. Sinto-me melhor por ter dito. Vamos ver como correm as próximas semanas.",
        C034: "Sempre soubeste quando era só para ouvir. Agradeço, {agent}.",
        C035: "Desculpa ter-te despejado isto assim. Mas sim, obrigado.",
        C036: "Bem. Já disse o que tinha a dizer. Tu não te esqueças.",
        C037: "Muito bem. Vou cobrar-te a palavra, {agent}.",
        C038: "Era isso que eu precisava de ouvir. Não me falhes.",
        C039: "Combinado. Nunca me deixaste ficar mal, por isso confio.",
        C040: "Bem. Põe por escrito se for preciso. Vou andar a contar as semanas.",
        C041: "A tua palavra sempre me bastou. Não me faças arrepender-me disso.",
        C042: "Hm. Não esperava essa resposta. Mas talvez tenhas razão.",
        C043: "É duro de ouvir, mas é honesto. Está bem. Baixo a cabeça e trabalho.",
        C044: "É uma análise justa. Consigo trabalhar com isso. Obrigado por seres direto comigo.",
        C045: "Tens razão quanto aos números. Vou concentrar-me no que consigo controlar.",
        C046: "A sério? Venho ter contigo com um problema e dizes-me que o problema sou EU?",
        C047: "Ora. Bom saber de que lado estás. Esta conversa acabou.",
        C048: "Tens cá uma lata! De que lado estás tu, afinal?",
        C049: "Não. NÃO. Não te compete dar-me lições. Resolve isso ou encontro quem resolva.",
        C050: "Pois. «Vai resolver-se sozinho.» Já ouvi essa antes.",
        C051: "Está bem, vamos ver. Mas não espero para sempre, {agent}.",
        C052: "Hm. Isso não é bem uma resposta, pois não?",

        // Gifts
        G001: "Ah, que bom. As coisas pequenas também contam. Obrigado, {agent}.",
        G002: "Lembraste-te! Obrigado, é um gesto muito bonito.",
        G003: "Não tinhas de fazer isso. Mas obrigado, a sério.",
        G004: "Fofo. A intenção é o que conta, suponho.",
        G005: "Isso é que é um presente a sério. Obrigado, sinceramente.",
        G006: "Está bem, tens bom gosto. Isso admito.",
        G007: "Isto é de luxo. Espera até os rapazes verem.",
        G008: "É uma atenção muito delicada. Vai ter um bom lugar em casa.",
        G009: "Isto é… uau. Não tinhas mesmo de fazer isso. Obrigado, {agent}.",
        G010: "Inacreditável. Não sei o que dizer. Obrigado.",
        G011: "É ASSIM que se trata uma estrela. Adoro!",
        G012: "É demasiado, {agent}. A sério. Mas vou guardá-lo como um tesouro.",
        G013: "Depois de todos estes anos ainda me surpreendes. Obrigado.",
        G014: "Outro já? Obrigado, suponho.",
        G015: "Andas a mimar-me demasiado ultimamente. Perde um pouco o brilho, sabes?",
        G016: "Dois presentes tão seguidos? Agora estou a perguntar-me qual é a má notícia.",
        G017: "Ha! Aceito.",
        G018: "Diz isso mais alto na próxima vez, está aí imprensa.",
        G019: "Só faço o meu trabalho. Mas obrigado.",
        G020: "Entendido. Volto ao trabalho.",
        G021: "É exatamente esse o meu plano.",
        G022: "Não tens graça nenhuma. Mas está bem.",

        // Finals
        F001: "Hoje é dia grande, {agent}. O vestiário está a ferver. Fico contente por teres vindo.",
        F002: "Então é isto. A noventa minutos de uma medalha.",
        F003: "Nunca tinha jogado uma final com o meu agente nas bancadas. Sem pressão, então.",
        F004: "Não consigo estar quieto, {agent}. Quero atravessar aquela parede JÁ.",
        F005: "Estudei bem o {opponent}. São as bolas paradas que vão decidir, vais ver.",
        F006: "As finais são o meu palco, {agent}. Hoje todos vão perceber.",
        F007: "Aconteça o que acontecer ali fora, obrigado por vires. Significa muito.",
        F008: "Está nas bancadas todo o mundo que eu conheço. Só não quero falhar-lhes.",
        F009: "É por isto que jogo futebol. Por dias como este.",
        F010: "Ganhar isto com ESTE clube significaria tudo para mim.",
        F011: "Prémio de vitória no contrato, medalha de taça na estante. Vamos aos dois.",
        F012: "Sim. Sim, tens razão. Respiro fundo. Estou bem.",
        F013: "Está bem. Está bem. Cabeça limpa, pernas soltas. Obrigado, {agent}.",
        F014: "Concordo. O processo acima da emoção. Até já.",
        F015: "Calma? Estou bem, {agent}. Guarda o discurso.",
        F016: "A calma é para o banco. Eu fui feito para isto.",
        F017: "SIM. Era isso que eu queria ouvir!",
        F018: "Olha bem para mim ali. O primeiro golo é para ti.",
        F019: "Calma, calma. Preciso de cabeça limpa, não de um grito de guerra.",
        F020: "Agradeço, mas eu preparo-me à minha maneira.",
        F021: "Ha! ISSO é que é motivação. Combinado.",
        F022: "Agora estás a falar a minha língua. Dá por ganho.",
        F023: "Não precisas de me comprar, {agent}. Mas está bem, combinado.",
        F024: "CONSEGUIMOS! Dá para acreditar? Vem cá, {agent}!",
        F025: "Campeões! Sonho com isto desde criança!",
        F026: "VISTE aquilo? Vão falar disto durante anos!",
        F027: "Conseguimos mesmo. A equipa toda esteve incrível.",
        F028: "Por este clube. Por toda aquela gente nas bancadas. Estou tão orgulhoso, {agent}.",
        F029: "SIIIM! Ninguém acreditava em nós! NINGUÉM!",
        F030: "Mais alto, {agent}! Hoje festeja-se!",
        F031: "Diz outra vez para as câmaras!",
        F032: "Ha, obrigado. Um pouco demais à frente de todos, mas obrigado.",
        F033: "Senta-te, por favor, estás a deixar-me envergonhado. Mas obrigado.",
        F034: "Isso significa mais do que qualquer manchete. Obrigado.",
        F035: "Agradeço. Em silêncio é exatamente como eu gosto.",
        F036: "Uma palavra em privado? Hoje? Vamos, vive um pouco!",
        F037: "As bebidas são por conta do agente! ISSO é que é serviço!",
        F038: "Generoso E esperto. Os rapazes vão lembrar-se disto.",
        F039: "Tão perto. Tão, tão perto. Não sei o que dizer, {agent}.",
        F040: "Esta vai doer durante muito tempo.",
        F041: "Não. Só… não digas nada por agora.",
        F042: "Desculpa. Senti que falhei a todos ali fora.",
        F043: "Os adeptos mereciam melhor hoje. É isso que me mata.",
        F044: "Obrigado por ficares. A maioria das pessoas deixa-te sozinho com isto.",
        F045: "Fico contente por estares aqui. A sério.",
        F046: "Agradeço, mas apetece-me estar um pouco sozinho agora.",
        F047: "Sim. Ligo-te dentro de dois ou três dias. Obrigado por compreenderes.",
        F048: "Boa decisão. Hoje não estou para companhia.",
        F049: "Pois. Todos se vão embora depois de uma derrota. Fica registado.",
        F050: "Tens razão. A próxima época começa amanhã. Vamos outra vez.",
        F051: "Correto. As derrotas são dados. Vamos sair melhores disto.",
        F052: "A próxima época? ACABÁMOS de perder, {agent}. Lê o ambiente.",
        F090: "Fizemos tudo bem hoje, {agent}. Só não foi suficiente — o título foi-se no outro resultado.",
        F091: "Ganhámos e ainda assim escapou-nos. Tão perto. Não acredito que acabou.",
        F092: "A nossa parte está feita, cumprimos. Foi o jogo que não controlávamos que nos matou.",

        // Farewell (retirement)
        W001: "Pronto, {agent}. É isto. Botas penduradas. Obrigado pelo trabalho ao longo destes anos.",
        W002: "Então é oficial. Retirada. Tivemos altos e baixos, mas cumprimos.",
        W003: "Que sensação estranha, {agent}. Não há mais dias de jogo. Fico contente por teres feito boa parte do caminho comigo.",
        W004: "Então foi o último apito. Obrigado por estes anos, {agent}. Foste correto comigo mais vezes do que não.",
        W005: "Sabes, de toda a gente do futebol, és um dos poucos de quem vou realmente sentir falta. Que percurso tivemos.",
        W006: "Não paro de pensar em tudo o que passámos juntos. Contratos, transferências, tudo. Obrigado, meu amigo.",
        W007: "Antes de tudo: o meu jogo de homenagem. Primeira fila, convidado de honra. Não se discute. Foste família em tudo isto.",
        W008: "Perguntaram-me quem mais contou na minha carreira. Disse a minha família. E disse o teu nome na mesma frase, {agent}.",
        W009: "Uma carreira e meia, é verdade. E não teria feito metade sem ti.",
        W010: "Vão lembrar-se dos golos. Tu só garante que escrevem o meu nome bem nos livros de recordes.",
        W011: "Foi uma boa obra. Podemos ambos ficar satisfeitos com isso.",
        W012: "Isso significa mais do que os troféus, sinceramente. Obrigado por tudo.",
        W013: "Para, vais fazer-me chorar. Obrigado. Por tudo.",
        W014: "Mantivemo-nos juntos, não foi? Em tudo. Isso é raro neste meio.",
        W015: "Estás a fazer-me chorar. Estou tão contente por te ter conhecido!",
        W016: "Significa o mundo para mim que tenhas estado lá em todos os momentos!",

        // Check-in
        K001: "Olá {agent}! Boa altura, acabei agora o treino. O que tens em mente?",
        K002: "Olha quem ele é. Está tudo bem, ou isto é negócio?",
        K003: "Ligaste, estou aqui. Mas o café pagas tu.",
        K004: "Sê rápido, tenho ginásio. Estou a brincar. Mais ou menos. O que se passa?",
        K005: "Vens ver como está o teu cliente preferido? Boa jogada.",
        K006: "É sempre bom quando apareces, {agent}. A sério.",
        K007: "Entra, entra. Dá gosto ver uma cara conhecida.",
        K008: "Família? Por agora sou só eu, sinceramente. O futebol leva tudo o que tenho.",
        K009: "Só eu, as minhas botas e uma mala. Por agora serve-me bem.",
        K010: "A minha melhor metade mantém-me são. Não conseguia fazer nada disto sozinho.",
        K011: "Os filhos são tudo, {agent}. Cada jogo que faço é por eles.",
        K012: "Os pequenos mandam em casa. A melhor coisa que me aconteceu.",
        K013: "Ultimamente? Ando metido em {hobby}. Mantém-me a cabeça tranquila entre jogos.",
        K014: "Arranjo tempo para {hobby}. Recuperação para a cabeça, não só para as pernas.",
        K015: "O de sempre, sinceramente. Treino, casa, repetir. Estou bem.",
        K016: "Desde criança? {favclub}. O meu pai levou-me a um jogo uma vez e ficou decidido.",
        K017: "Fácil. {favclub}. Tinha os pósteres, as camisolas, tudo.",
        K018: "{favclub}, sempre. Há coisas que não mudam, onde quer que se jogue.",
        K019: "Adoro o {favclub}! Não consigo estar quieto quando eles jogam.",
        K020: "É o {favclub}. A minha avó tem bilhete de época há 52 anos, e meteu a família toda nisto.",
        K021: "Sinceramente? Um dia, quero {ambition}. É esse o sonho.",
        K022: "Entre nós: quero {ambition}. E quero que todos o vejam.",
        K023: "Defini um único objetivo: {ambition}. Tudo o que faço aponta para ali.",
        K024: "Se um dia conseguisse {ambition}, seria uma conquista incrível para mim e para os meus.",
        K025: "Preciso de {ambition}. E quero estar sempre na luta pelos títulos!",
        K026: "Quero {ambition}. Mas o mais importante é ter os meus amigos e a minha família comigo em cada passo.",
        K027: "O vestiário está bom. Alguns egos grandes, mas mostra-me um sem eles.",
        K028: "Sinceramente, um grupo excelente. O melhor de que já fiz parte.",
        K029: "Há um que não para de me tirar o lugar de estacionamento. Já tivemos palavras.",
        K030: "Sinceramente, sinto que os meus colegas não valorizam o suficiente a minha excelência…",
        K031: "Ha! É uma festa a maior parte do tempo, e sabes que o DJ sou eu!",
        K032: "Sinto-me muito em casa aqui! Por agora não vejo razão nenhuma para sair.",
        K033: "Sinto-me muito em casa aqui! Por agora não vejo razão nenhuma para sair.",
        K034: "Temos umas cobras de duas caras no meio de nós… Sempre a falar nas costas dos outros.",
        K035: "Falta-nos coesão a sério neste momento… Acho que o treinador juntou um plantel de mercenários.",
        K036: "Às vezes olho em volta e sinto-me tão grato por fazer parte desta equipa incrível! Obrigado por me tornares isto possível.",
        K037: "Fiz muitos amigos no tempo que tenho neste clube. Sinto-me mesmo abençoado.",
        K038: "Ha, só para saber como estou? Agradeço. Sinceramente.",
        K039: "Sem agenda? É a primeira vez, vindo de um agente. Gosto disso.",
        K040: "É simpático da tua parte. Às vezes sente-se solidão aqui, sabes?",
        K041: "Que bom ver-te, {agent}! Sobre o que queres falar?",
        K042: "Olá, como estás? Espero que não venhas pedir dinheiro! Estou a brincar, claro. O que se passa?",
        K043: "É simpático da tua parte entrares em contacto. Sobre o que querias falar comigo?",

        // Moments
        M001: "Os meus primeiros minutos nos seniores, {agent}! Viste? Ainda tenho a camisola vestida. Não a tiro.",
        M002: "Joguei mesmo. Um jogo de seniores a sério. Estou sempre à espera que alguém me diga que foi um erro.",
        M003: "PRIMEIRO GOLO! Viste? Já devo ter visto o vídeo cinquenta vezes.",
        M004: "Finalmente entrou. Parece irreal, sinceramente.",
        M005: "TRÊS! Um hat-trick, {agent}! Deram-me a bola do jogo e tudo!",
        M006: "Um hat-trick. A bola do jogo vai ser emoldurada. As botas talvez também.",
        M007: "{milestone}. Acabei de ver no programa do jogo. Como o tempo passa, não é?",
        M008: "{milestone}. Um número bonito. Agora ao próximo.",
        M009: "{milestone}. E tu estiveste lá na maior parte deles, {agent}.",
        M010: "O meu primeiro contrato profissional, {agent}! Assinado e tudo. Agora é a sério, não é?",
        M011: "Não paro de reler o contrato. Eu. Futebolista profissional.",
        M012: "Está feito, {agent}. {newclub}. Capítulo novo. Obrigado por o fechares.",
        M013: "{newclub}! Cidade nova, campeonato novo, tudo novo. É para isto que eu vivo.",
        M014: "{newclub}, então. Uma grande mudança para mim. Confio que seja a certa.",
        M015: "Tenho de te contar uma coisa. O {newclub} era O MEU clube em criança. Acabaste de realizar o sonho de um menino. Não me vou esquecer disto. Nunca.",
        M016: "Sabias o que o {newclub} significava para mim. É a maior coisa que alguém fez pela minha carreira. Obrigado.",
        M017: "Lembras-te do que eu disse que queria? {ambition}? … Feito. Conseguimos mesmo.",
        M018: "{ambition}. Disse e fiz. E tu ajudaste, {agent}. Honra a quem merece.",
        M019: "Dizem {weeks} semanas, {agent}. Agora não consigo olhar para as minhas botas.",
        M020: "EU SABIA que aquele tackle vinha. {weeks} semanas. Estou furioso.",
        M021: "{weeks} semanas de fora. Já pedi o plano de recuperação. Mas ainda dói.",
        M022: "Ha, obrigado. Dias como este fazem tudo valer a pena.",
        M023: "Finalmente alguém o diz como é!",
        M024: "Está bem, está bem. Uma noite a festejar e depois volta ao normal.",
        M025: "Tens razão. Cabeça baixa, próximo trabalho.",
        M026: "Concordo. Festejar hoje, reiniciar amanhã.",
        M027: "Sem barulho? Está bem. Mas fico com o resumo em repetição.",
        M028: "Vieste até aqui? Isso… significa muito, {agent}.",
        M029: "Não tinhas de vir. Fico contente por teres vindo.",
        M030: "As flores chegaram. Bonito gesto. Manda-me também uns jogos para ver.",
        M031: "Antes de ires. Trouxe-te uma coisa. Não se discute, já está paga. {thing}. Mereceste dez vezes.",
        M032: "O meu pai dizia sempre: cuida de quem cuida de ti. Por isso, toma. {thing}. Obrigado, {agent}.",
        M033: "Escolhi-o eu mesmo. {thing}! Só o melhor para o meu agente, é claro.",
        M034: "Não é grande coisa, mas… {thing}. Por tudo o que fazes e que ninguém vê.",
        M035: "Bem. Cada vez que olhares para isso, lembra-te de que fizemos isto juntos.",
        M036: "Era só isso que eu queria ouvir. Cuidamos um do outro, sempre.",
        M037: "Ha! Nunca mudes, {agent}. Nunca.",
        M038: "Vês, é POR ISTO que nos entendemos.",
        M039: "Quero-te connosco para {occasion}. Não como meu agente. Como amigo. Diz que vens.",
        M040: "É {occasion} em breve. Círculo pequeno, só família e as pessoas que contam. Isso inclui-te, {agent}.",
        M041: "{occasion}. Vai ser O evento do verão. Estás na lista, obviamente.",
        M042: "Vens? Isso significa o mundo. Vemo-nos lá!",
        M043: "A sério? Eu… obrigado. Não seria o mesmo sem ti.",
        M044: "Não podes vir? Que pena. Mas é muito generoso, obrigado.",
        M045: "Pois. Agenda cheia, eu entendo. … Eu entendo.",
    },

    // --- what the AGENT says when you pick a choice (Dialogue.SAY, keyed "scene:choice") ---
    say: {
        'complaint:listen': "Fala comigo. Seja o que for, quero ouvir, tudo.",
        'complaint:promise': "Muito bem. É isto que vou fazer quanto a isso.",
        'complaint:pushback': "Estou a ouvir-te. Mas deixa-me ser direto contigo um momento.",
        'complaint:deflect': "Não nos adiantemos. Dá-lhe mais algum tempo.",
        'promise:move': "Deixa isso comigo. Vou encontrar-te a saída certa — o clube certo, não um clube qualquer.",
        'promise:newContract': "Consigo-te o contrato que mereces neste clube. Dá-me algum tempo.",
        'promise:playingTime': "Vou falar a sério com o treinador sobre os teus minutos. Vamos resolver isto.",
        'promise:renegotiateRep': "E eu fico com menos do meu lado para que aconteça. É assim que te apoio.",
        'gift:praise': "Mereceste isto. Tudo. Que ninguém te diga o contrário.",
        'gift:modest': "Não é nada, a sério. Só queria que soubesses que estou atento.",
        'prematch:calm': "Respira. Já fizeste todo o trabalho. Entra e joga o teu jogo.",
        'prematch:fireup': "Esta noite é tua. Entra e agarra-a — não deixes nada para trás.",
        'prematch:bonus': "Digo-te uma coisa: ganhas este e há um extra para ti.",
        'bonus:small': "Ganhas hoje e há um presente para ti. Palavra.",
        'bonus:medium': "Ganha isto e eu cuido bem de ti — é uma promessa.",
        'bonus:large': "Traz isto para casa e faço com que valha muito a pena. Palavra.",
        'postwin:toast': "Vem cá — aquilo foi especial. Vamos aproveitar esta.",
        'postwin:quiet': "Belíssimo trabalho. Deixo-te voltar para os rapazes.",
        'postwin:tab': "Hoje é tudo por minha conta. Mereceste mais do que isso.",
        'postloss:sit': "Senta-te comigo um minuto. Agora dói — não vai doer muito tempo.",
        'postloss:space': "Deixo-te em paz. Cabeça erguida. Vamos outra vez.",
        'postloss:speech': "Ouve-me. Um jogo não te define. Não te atrevas a esquecer isso.",
        'farewell:career': "Que carreira tiveste. Devias estar orgulhoso de cada minuto.",
        'farewell:personal': "Esquece o futebol um segundo — estou só contente por te ter conhecido.",
        'checkin:q-life': "Então, como vão as coisas fora do campo? Está tudo bem em casa?",
        'checkin:q-club': "Como te estás a adaptar ao clube? Dás-te bem com todos?",
        'checkin:q-ambition': "Até onde queres levar isto? A que é que apontamos, na verdade?",
        'checkin:q-room': "Com quem andas no vestiário ultimamente?",
        'checkin:q-none': "Hoje sem agenda. Só queria ver como estavas.",
        'moment:praise': "Aquele foi um grande momento. Aproveita-o — mereceste.",
        'moment:modest': "Brilhante em silêncio, aquilo. Bem jogado.",
        'injury:there': "Vou visitar-te. Não vais passar por isto sozinho.",
        'injury:flowers': "Mando-te algo — só para saberes que estou a pensar em ti.",
        'thanks:cherish': "Isto significa muito para mim. Vou guardá-lo, a sério.",
        'thanks:banter': "Não tinhas de fazer isso, seu sentimental. Mas obrigado, a sério.",
        'invite:attend': "Não perdia isso por nada. Vou estar lá, nas bancadas.",
        'invite:gift': "Não posso estar lá em pessoa, mas deixa-me mandar algo para marcar o dia.",
        'invite:decline': "Desta vez não posso estar lá — mas estou contigo em pensamento, sabes disso.",
    },

    // --- choice buttons (keyed "scene|choice") ---
    choices: {
        'complaint|listen': { label: "Ouvi-lo", hint: "Seguro. Ele quer ser ouvido." },
        'complaint|promise': { label: "Fazer-lhe uma promessa", hint: "Abre uma promessa com um prazo real." },
        'complaint|pushback': { label: "Contrariá-lo", hint: "Dizer-lhe que está errado. Arriscado, depende do homem." },
        'complaint|deflect': { label: "Desvalorizar", hint: "Ganha tempo. Ele pode levá-lo a mal." },
        'gift|praise': { label: "Mereceste" },
        'gift|modest': { label: "Cabeça baixa e a jogar" },
        'prematch|calm': { label: "Acalmá-lo", hint: "Acalmar os nervos antes do maior jogo do ano dele." },
        'prematch|fireup': { label: "Motivá-lo", hint: "Fazer o sangue ferver." },
        'prematch|bonus': { label: "Prometer um prémio de vitória", hint: "Escolhe um presente que ele recebe se levantarem o troféu. Não custa nada se perderem." },
        'postwin|toast': { label: "Elogiá-lo à frente de todos", hint: "Elogio público. Alguns adoram, outros ficam incomodados." },
        'postwin|quiet': { label: "Uma palavra em privado", hint: "Só os dois, longe do barulho." },
        'postwin|tab': { label: "Pagar a conta esta noite", hint: "Custa-te dinheiro, significa muito." },
        'postloss|sit': { label: "Ficar com ele", hint: "Não dizer nada. Só ficar." },
        'postloss|space': { label: "Dar-lhe espaço", hint: "Algumas feridas fecham-se sozinhas." },
        'postloss|speech': { label: "Vamos outra vez na próxima época", hint: "Direto ao que vem a seguir." },
        'farewell|career': { label: "A uma carreira e meia" },
        'farewell|personal': { label: "Ao homem, não só ao jogador" },
        'checkin|q-life': { label: "Perguntar pela vida fora do futebol" },
        'checkin|q-club': { label: "Perguntar pelo clube favorito dele" },
        'checkin|q-ambition': { label: "Perguntar pelas ambições dele" },
        'checkin|q-room': { label: "Perguntar pelo vestiário" },
        'checkin|q-none': { label: "Nada em particular", hint: "Às vezes é isso que diz mais." },
        'moment|praise': { label: "Festejar com ele" },
        'moment|modest': { label: "Sem fazer barulho" },
        'injury|there': { label: "Visitá-lo em pessoa" },
        'injury|flowers': { label: "Mandar flores" },
        'thanks|cherish': { label: "Vou guardá-lo como um tesouro" },
        'thanks|banter': { label: "Já era tempo de me pagares" },
        'invite|attend': { label: "Libertar a agenda, vais estar lá", hint: "Um fim de semana do teu tempo. Conta mais do que qualquer presente." },
        'invite|gift': { label: "Mandar um presente generoso", hint: "Não podes ir, mas a atenção chega." },
        'invite|decline': { label: "Recusar com educação", hint: "Ele vai notar." },
    },

    // --- discovered "vocabulary": hobbies, keepsakes and occasions, keyed by the English value ---
    // Stored on the player in English, so they are localised at fill() time. The articles are part
    // of the value, because the lines read "metido em {hobby}" / "tempo para {hobby}".
    vocab: {
        'golf': "golfe",
        'fishing': "pesca",
        'gaming': "videojogos",
        'chess': "xadrez",
        'cooking': "cozinha",
        'classic cars': "carros clássicos",
        'photography': "fotografia",
        'making music': "fazer música",
        'padel': "padel",
        'poker': "poker",
        'a signed shirt from his debut': "uma camisola autografada da estreia dele",
        'a watch with a date engraved on the back': "um relógio com uma data gravada nas costas",
        'a framed photo of the two of you at his first signing': "uma fotografia emoldurada dos dois na primeira assinatura dele",
        'the match ball from his best game, signed by the whole squad': "a bola do melhor jogo dele, assinada pelo plantel inteiro",
        'a bottle from a vineyard he part-owns': "uma garrafa de uma vinha de que é coproprietário",
        'my wedding': "o meu casamento",
        "the little one's christening": "o batizado do pequeno",
        'a gift': "um presente",
    },

    // --- ambitions: a pronoun-free infinitive phrase, so it reads both as a label and inside a
    // spoken line ("quero {ambition}", "{ambition}? Feito."). The fallbacks carry whatever article
    // their template needs: "n{league}" is avoided by using "em {league}" with a bare fallback.
    amb: {
        types: {
            league: "jogar um dia em {league}",
            dreamclub: "jogar um dia por {club}",
            boyhood: "acabar onde tudo começou, no {fav}",
            title: "ganhar um título de campeão",
            cup: "levantar uma taça",
            europe: "jogar nas provas europeias",
            goals: "chegar aos {target} golos na carreira",
            topflight: "jogar num dos cinco grandes campeonatos",
            abroad: "jogar no estrangeiro",
        },
        dflt: "chegar ao topo",
        favFallback: "clube da minha infância",
        leagueFallback: "campeonatos maiores",
        clubFallback: "um grande clube",
    },

    // --- milestone labels, frozen into the line when the moment is queued (the player is speaking) ---
    mile: {
        apps: "{n} jogos",
        goals: "{n} golos na carreira",
    },

    // --- the cash thank-you gift, filled into {thing} ---
    envelope: "um envelope. Dentro: €{amt} para a agência",
};
if (typeof module !== 'undefined' && module.exports) module.exports = { DIALOGUE_PT };
