// French translations for the dialogue system, keyed by the SAME stable line ids as
// js/dialogue-data.js (the English source, generated from dialogue_lines.xlsx). Any id missing
// here falls back to the English workbook text — so this file may lag the workbook safely.
// dialogue.js picks these up through Dialogue._pack() when I18n.locale === 'fr'.
//
// Register: informal "tu" both ways, as in German and Spanish. This is spoken conversation
// between an agent and a player who know each other well; the written correspondence in
// js/i18n-fr.js stays on "vous". At a low bond the client still addresses you as "M. Mercer"
// (dlg.addr.mr) while using "tu" — the same small tension German ships with, and unavoidable
// because a line's pronoun cannot vary with the bond level.
const DIALOGUE_FR = {
    // --- player spoken lines (DIALOGUE_DATA[sheet][*].text, by id) ---
    lines: {
        // Complaint
        C001: "Patron, il me faut du temps de jeu. Je m'entraîne bien toute la semaine, et le samedi arrive et je regarde depuis le banc.",
        C002: "On peut parler ? Je ne suis pas venu à {club} pour m'asseoir sur un banc. Il faut que quelque chose change.",
        C003: "Je ne demande pas de miracles, {agent}. Je demande une vraie chance d'être dans le onze.",
        C004: "J'en ai fini de regarder depuis la touche, {agent}. Si l'entraîneur ne me fait pas jouer, trouve-moi quelqu'un qui le fera !",
        C005: "Regarde mes chiffres à l'entraînement, puis regarde qui joue devant moi. Ça ne colle pas, et je veux ton avis là-dessus.",
        C006: "Les gens n'arrêtent pas de me demander pourquoi je ne joue pas. Je n'ai pas de réponse. C'est un problème pour nous deux.",
        C007: "Entre nous, je ne vois pas {club} aller quelque part. J'ai besoin de savoir que tu as un plan pour moi.",
        C008: "Ce n'est pas le projet qu'on m'a vendu, {agent}. Le vestiaire est éteint.",
        C009: "J'ai tout donné à ce club et je ne suis plus sûr que ce soit réciproque.",
        C010: "Je n'aurais jamais pensé dire ça, mais le club a changé. Ce n'est plus l'endroit pour lequel j'ai signé.",
        C011: "J'ai vu tout ce qu'il y avait à voir ici. J'ai besoin d'un nouveau défi avant de m'encroûter.",
        C012: "Il y a quelque chose qui ne va pas au club ces derniers temps. Je ne veux pas de drame, je veux juste que ce soit réglé.",
        C013: "Tu as vu ce que touche la nouvelle recrue ? Je suis meilleur que lui pour la moitié du salaire.",
        C014: "Mon contrat ne correspond plus à ce que j'apporte. On règle ça quand ?",
        C015: "Je n'aime pas parler d'argent, {agent}, mais il faut bien que quelqu'un le fasse. Mon salaire est en retard sur le vestiaire.",
        C016: "Les chiffres ne mentent pas, {agent}. Les miens montent et mon salaire non. Arrange ça.",
        C017: "Ça me gêne même d'en parler, mais les gars disent que je suis sous-payé. Ils ont raison ?",
        C018: "Un joueur de mon profil à ce salaire ? Ça fait mauvais genre. Et c'est vraiment mauvais.",
        C019: "Honnêtement ? Je n'entends parler de toi que quand il y a le feu. Ce n'est pas pour ça que j'ai signé.",
        C020: "J'ai besoin de savoir que tu es toujours dans mon camp, {agent}. Ces derniers temps, j'ai eu des doutes.",
        C021: "Où est-ce que tu étais ? Les autres agents appellent leurs joueurs chaque semaine. Moi j'ai le silence.",
        C022: "Je suis resté avec toi longtemps, {agent}. Dis-moi juste que ça compte encore.",
        C023: "On a passé le stade des discussions, {agent}. Fais-moi jouer ou fais-moi partir. Voilà les options.",
        C024: "Chaque semaine sur ce banc me coûte cher. Je veux une solution maintenant, pas une nouvelle discussion.",
        C025: "Ça suffit ! Je déposerai moi-même une demande de transfert s'il faut ça pour jouer au football.",
        C026: "Je suis sérieux. Commence à me chercher une porte de sortie, ou je rends public le fait que je veux partir.",
        C027: "Ma décision est prise au sujet de cet endroit. Ce qu'il me faut de toi, c'est un plan, cette semaine.",
        C028: "La dernière fois qu'on a parlé, rien ne s'est passé. Obtiens-moi un vrai contrat ou je trouverai quelqu'un qui peut.",
        C029: "Tu as eu ta chance de régler mon contrat en silence. Maintenant ça va faire du bruit.",
        C030: "J'ai discuté avec d'autres agences, {agent}. Donne-moi une bonne raison de rester.",
        C031: "En ce qui me concerne, c'est ton dernier avertissement. Montre-moi que ma carrière te tient encore à cœur.",
        C032: "Merci de m'avoir écouté. Ça aide plus que tu ne crois.",
        C033: "D'accord. Je me sens mieux de l'avoir dit. On verra comment se passent les prochaines semaines.",
        C034: "Tu as toujours su quand il fallait simplement écouter. J'apprécie, {agent}.",
        C035: "Désolé de t'avoir déballé tout ça. Mais oui, merci.",
        C036: "Bien. J'ai dit ce que j'avais à dire. Ne l'oublie pas.",
        C037: "Très bien. Je te prends au mot, {agent}.",
        C038: "C'est ce que j'avais besoin d'entendre. Ne me déçois pas.",
        C039: "Marché conclu. Tu ne m'as jamais laissé tomber, alors je te fais confiance.",
        C040: "Bien. Mets-le par écrit s'il faut. Je vais compter les semaines.",
        C041: "Ta parole m'a toujours suffi. Ne me fais pas le regretter.",
        C042: "Tiens. Je ne m'attendais pas à cette réponse. Mais tu as peut-être raison.",
        C043: "C'est dur à entendre, mais c'est honnête. D'accord. Je baisse la tête et je travaille.",
        C044: "C'est une analyse juste. Je peux travailler avec ça. Merci d'être direct avec moi.",
        C045: "Tu as raison sur les chiffres. Je vais me concentrer sur ce que je peux contrôler.",
        C046: "Sérieusement ? Je viens te voir avec un problème et tu me dis que le problème c'est MOI ?",
        C047: "Eh bien. Content de savoir de quel côté tu es. Cette conversation est terminée.",
        C048: "Tu as du culot ! Tu es du côté de qui, au fond ?",
        C049: "Non. NON. Ce n'est pas à toi de me faire la leçon. Arrange ça ou je trouve quelqu'un qui le fera.",
        C050: "Bien sûr. « Ça va s'arranger tout seul. » On me l'a déjà servie, celle-là.",
        C051: "On verra bien. Mais je n'attendrai pas éternellement, {agent}.",
        C052: "Hm. Ce n'est pas vraiment une réponse, si ?",

        // Gifts
        G001: "Ah, sympa. Les petites choses comptent aussi. Merci, {agent}.",
        G002: "Tu t'en es souvenu ! Merci, c'est une belle attention.",
        G003: "Tu n'étais pas obligé. Mais merci, vraiment.",
        G004: "Mignon. C'est l'intention qui compte, je suppose.",
        G005: "Ça, c'est un vrai cadeau. Merci, sincèrement.",
        G006: "D'accord, tu as du goût. Je te l'accorde.",
        G007: "C'est du grand luxe. Attends que les gars voient ça.",
        G008: "C'est une attention très délicate. Ça aura une belle place à la maison.",
        G009: "C'est… waouh. Tu n'étais vraiment pas obligé. Merci, {agent}.",
        G010: "Incroyable. Je ne sais pas quoi dire. Merci.",
        G011: "VOILÀ comment on traite une star. J'adore !",
        G012: "C'est trop, {agent}. Honnêtement. Mais je vais le garder précieusement.",
        G013: "Après toutes ces années tu me surprends encore. Merci.",
        G014: "Encore un, déjà ? Merci, je suppose.",
        G015: "Tu me gâtes un peu trop ces temps-ci. Ça perd de son éclat, tu sais.",
        G016: "Deux cadeaux aussi rapprochés ? Maintenant je me demande quelle est la mauvaise nouvelle.",
        G017: "Ha ! Je prends.",
        G018: "Dis-le plus fort la prochaine fois, il y a la presse dans le coin.",
        G019: "Je fais juste mon travail. Mais merci.",
        G020: "Compris. Je retourne au travail.",
        G021: "C'est exactement mon plan.",
        G022: "Tu n'es pas drôle. Mais bon, d'accord.",

        // Finals
        F001: "C'est un grand jour, {agent}. Le vestiaire bouillonne. Content que tu sois venu.",
        F002: "Alors c'est ça. À quatre-vingt-dix minutes d'une médaille.",
        F003: "Je n'avais jamais joué une finale avec mon agent en tribunes. Pas de pression, donc.",
        F004: "Je n'arrive pas à rester assis, {agent}. J'ai envie de traverser ce mur TOUT DE SUITE.",
        F005: "J'ai bien étudié {opponent}. Ce sont les coups de pied arrêtés qui vont décider, tu verras.",
        F006: "Les finales, c'est ma scène, {agent}. Aujourd'hui ils vont tous comprendre.",
        F007: "Quoi qu'il arrive là-dehors, merci d'être venu. Ça compte beaucoup.",
        F008: "Tous ceux que je connais sont en tribunes aujourd'hui. Je ne veux juste pas les décevoir.",
        F009: "C'est pour ça que je joue au football. Pour des journées comme celle-ci.",
        F010: "Gagner ça avec CE club signifierait tout pour moi.",
        F011: "Prime de victoire dans le contrat, médaille de coupe sur l'étagère. Prenons les deux.",
        F012: "Oui. Oui, tu as raison. Grande respiration. Ça va.",
        F013: "D'accord. D'accord. Tête claire, jambes légères. Merci, {agent}.",
        F014: "Je suis d'accord. Le processus avant l'émotion. À tout à l'heure.",
        F015: "Calme ? Ça va, {agent}. Garde ton discours.",
        F016: "Le calme, c'est pour le banc. Moi je suis fait pour ça.",
        F017: "OUI. C'est ce que je voulais entendre !",
        F018: "Regarde-moi bien. Le premier but est pour toi.",
        F019: "Doucement, doucement. J'ai besoin d'une tête claire, pas d'un cri de guerre.",
        F020: "J'apprécie, mais je me prépare à ma façon.",
        F021: "Ha ! ÇA, c'est de la motivation. Marché conclu.",
        F022: "Là tu parles mon langage. Considère que c'est gagné.",
        F023: "Tu n'as pas besoin de m'acheter, {agent}. Mais bon, d'accord, marché conclu.",
        F024: "ON L'A FAIT ! Tu te rends compte ? Viens là, {agent} !",
        F025: "Champions ! J'en rêve depuis que je suis gamin !",
        F026: "Tu as VU ça ? On va en parler pendant des années !",
        F027: "On l'a vraiment fait. Toute l'équipe a été incroyable.",
        F028: "Pour ce club. Pour tous ceux qui sont dans ces tribunes. Je suis tellement fier, {agent}.",
        F029: "OUIII ! Personne ne croyait en nous ! PERSONNE !",
        F030: "Plus fort, {agent} ! Ce soir on fête ça !",
        F031: "Répète-le pour les caméras !",
        F032: "Ha, merci. Un peu too much devant tout le monde, mais merci.",
        F033: "Assieds-toi, tu me fais honte. Mais merci.",
        F034: "Ça compte plus que n'importe quel gros titre. Merci.",
        F035: "J'apprécie. En toute discrétion, c'est exactement comme j'aime.",
        F036: "Un mot en privé ? Ce soir ? Allez, vis un peu !",
        F037: "C'est l'agent qui paie la tournée ! ÇA, c'est du service !",
        F038: "Généreux ET malin. Les gars s'en souviendront.",
        F039: "Si près. Tellement, tellement près. Je ne sais pas quoi dire, {agent}.",
        F040: "Celle-là va faire mal pendant longtemps.",
        F041: "Non. Juste… ne dis rien pour l'instant.",
        F042: "Désolé. J'ai eu le sentiment d'avoir laissé tomber tout le monde là-dehors.",
        F043: "Les supporters méritaient mieux aujourd'hui. C'est ça qui me tue.",
        F044: "Merci d'être resté. La plupart des gens te laissent seul avec ça.",
        F045: "Je suis content que tu sois là. Vraiment.",
        F046: "J'apprécie, mais j'ai un peu envie d'être seul là.",
        F047: "Oui. Je t'appelle dans deux ou trois jours. Merci de comprendre.",
        F048: "Bonne décision. Je ne suis pas d'une compagnie agréable ce soir.",
        F049: "Voilà. Tout le monde s'en va après une défaite. C'est noté.",
        F050: "Tu as raison. La saison prochaine commence demain. On y retourne.",
        F051: "Exact. Les défaites sont des données. On en sortira meilleurs.",
        F052: "La saison prochaine ? On VIENT de perdre, {agent}. Lis l'ambiance.",
        F090: "On a tout fait comme il fallait aujourd'hui, {agent}. Ça n'a juste pas suffi : le titre s'est envolé sur l'autre résultat.",
        F091: "On a gagné et ça nous a quand même échappé. Si près. Je n'arrive pas à croire que ce soit fini.",
        F092: "Notre part est faite, on a rempli notre contrat. C'est le match qu'on ne contrôlait pas qui nous a tués.",

        // Farewell (retirement)
        W001: "Voilà, {agent}. C'est fini. Les crampons sont raccrochés. Merci pour le travail de toutes ces années.",
        W002: "C'est officiel alors. La retraite. On a eu nos hauts et nos bas, mais on a fait le travail.",
        W003: "Sensation étrange, {agent}. Plus de jours de match. Je suis content que tu aies fait une bonne partie du chemin avec moi.",
        W004: "Alors c'était le dernier coup de sifflet. Merci pour ces années, {agent}. Tu as été correct avec moi plus souvent qu'autrement.",
        W005: "Tu sais, de tous les gens du football, tu es l'un des rares qui va vraiment me manquer. Quel parcours on a eu.",
        W006: "Je repense sans arrêt à tout ce qu'on a traversé ensemble. Les contrats, les transferts, tout. Merci, mon ami.",
        W007: "Avant tout : mon jubilé. Premier rang, invité d'honneur. Pas de discussion. Tu as été de la famille pendant tout ça.",
        W008: "On m'a demandé qui avait le plus compté dans ma carrière. J'ai dit ma famille. Et je t'ai nommé dans la même phrase, {agent}.",
        W009: "Une sacrée carrière, c'est vrai. Et je n'aurais pas pu en faire la moitié sans toi.",
        W010: "On se souviendra des buts. Assure-toi juste qu'ils écrivent bien mon nom dans les livres de records.",
        W011: "C'était une belle œuvre. On peut être satisfaits tous les deux.",
        W012: "Ça compte plus que les trophées, honnêtement. Merci pour tout.",
        W013: "Arrête, tu vas me faire pleurer. Merci. Pour tout.",
        W014: "On est restés soudés, hein. À travers tout. C'est rare dans ce milieu.",
        W015: "Tu me fais pleurer. Je suis tellement content de t'avoir rencontré !",
        W016: "Ça compte énormément pour moi que tu aies été là du début à la fin !",

        // Check-in
        K001: "Salut {agent} ! Bon timing, je viens de finir l'entraînement. Qu'est-ce qui t'amène ?",
        K002: "Tiens, regarde qui voilà. Tout va bien, ou c'est du business ?",
        K003: "Tu as appelé, je suis là. Le café est pour toi, cela dit.",
        K004: "Fais vite, j'ai une séance de muscu. Je plaisante. À moitié. Qu'est-ce qui se passe ?",
        K005: "Tu viens prendre des nouvelles de ton client préféré ? Bien joué.",
        K006: "C'est toujours agréable quand tu passes, {agent}. Vraiment.",
        K007: "Entre, entre. Ça fait plaisir de voir un visage familier.",
        K008: "La famille ? Il n'y a que moi pour l'instant, honnêtement. Le football prend tout ce que j'ai.",
        K009: "Juste moi, mes crampons et une valise. Ça me convient pour le moment.",
        K010: "Ma moitié me garde sain d'esprit. Je ne pourrais rien faire de tout ça seul.",
        K011: "Les enfants, c'est tout pour moi, {agent}. Chaque match que je joue, c'est pour eux.",
        K012: "Les petits font la loi à la maison. La meilleure chose qui m'est arrivée.",
        K013: "Ces temps-ci ? Je suis à fond dans {hobby}. Ça me garde la tête tranquille entre les matches.",
        K014: "Je prends du temps pour {hobby}. De la récupération pour la tête, pas seulement pour les jambes.",
        K015: "Comme d'habitude, honnêtement. Entraînement, maison, on recommence. Je suis bien.",
        K016: "Depuis tout petit ? {favclub}. Mon père m'a emmené à un match une fois et c'était réglé.",
        K017: "Facile. {favclub}. J'avais les posters, les maillots, tout.",
        K018: "{favclub}, toujours. Il y a des choses qui ne changent pas, où qu'on joue.",
        K019: "J'adore {favclub} ! Je n'arrive pas à rester assis quand ils jouent.",
        K020: "C'est {favclub}. Ma grand-mère est abonnée depuis 52 ans, et elle a embarqué toute la famille avec elle.",
        K021: "Honnêtement ? Un jour, je veux {ambition}. C'est le rêve.",
        K022: "Entre nous : je veux {ambition}. Et je veux que tout le monde le voie.",
        K023: "Je me suis fixé un seul objectif : {ambition}. Tout ce que je fais pointe vers là.",
        K024: "Si un jour je pouvais {ambition}, ce serait un accomplissement incroyable pour moi et pour mes proches.",
        K025: "J'ai besoin de {ambition}. Et je veux toujours être dans la course aux titres !",
        K026: "Je veux {ambition}. Mais le plus important, c'est d'avoir mes amis et ma famille avec moi à chaque étape.",
        K027: "Le vestiaire est bon. Quelques gros egos, mais montre-m'en un sans.",
        K028: "Honnêtement, un très bon groupe. Le meilleur dont j'aie fait partie.",
        K029: "Il y en a un qui n'arrête pas de me prendre ma place de parking. On a eu des mots.",
        K030: "Honnêtement, j'ai l'impression que mes coéquipiers n'apprécient pas assez mon excellence…",
        K031: "Ha ! C'est la fête la plupart du temps, et tu sais que le DJ c'est moi !",
        K032: "Je me sens vraiment chez moi ici ! Je ne vois aucune raison de partir un jour, pour le moment.",
        K033: "Je me sens vraiment chez moi ici ! Je ne vois aucune raison de partir un jour, pour le moment.",
        K034: "On a quelques serpents à deux visages parmi nous… Toujours à parler dans le dos des autres.",
        K035: "Il nous manque une vraie cohésion en ce moment… Je pense que l'entraîneur a assemblé un effectif de mercenaires.",
        K036: "Parfois je regarde autour de moi et je suis tellement reconnaissant de faire partie de cette équipe formidable ! Merci de m'avoir rendu ça possible.",
        K037: "Je me suis fait beaucoup d'amis depuis que je suis dans ce club. Je me sens vraiment chanceux.",
        K038: "Ha, juste pour prendre des nouvelles ? J'apprécie. Sincèrement.",
        K039: "Aucun ordre du jour ? C'est une première pour un agent. J'aime ça.",
        K040: "C'est gentil de ta part. On se sent parfois seul ici, tu sais.",
        K041: "Content de te voir, {agent} ! De quoi voulais-tu parler ?",
        K042: "Salut, comment vas-tu ? J'espère que tu ne viens pas quémander de l'argent ! Je plaisante, bien sûr. Qu'est-ce qui se passe ?",
        K043: "C'est sympa de prendre contact, de quoi voulais-tu me parler ?",

        // Moments
        M001: "Mes premières minutes chez les pros, {agent} ! Tu as vu ? J'ai encore le maillot sur le dos. Je ne l'enlève pas.",
        M002: "J'ai vraiment joué. Un vrai match avec les pros. J'attends encore que quelqu'un me dise que c'était une erreur.",
        M003: "PREMIER BUT ! Tu l'as vu ? J'ai déjà dû regarder la vidéo cinquante fois.",
        M004: "Elle est enfin rentrée. Ça fait irréel, honnêtement.",
        M005: "TROIS ! Un triplé, {agent} ! Ils m'ont donné le ballon du match et tout !",
        M006: "Un triplé. Le ballon du match va être encadré. Les crampons aussi peut-être.",
        M007: "{milestone}. Je viens de le voir dans le programme du match. Comme le temps passe, hein ?",
        M008: "{milestone}. Un joli chiffre. Maintenant au suivant.",
        M009: "{milestone}. Et tu étais là pour la plupart d'entre eux, {agent}.",
        M010: "Mon premier contrat professionnel, {agent} ! Signé et tout. C'est vrai maintenant, non ?",
        M011: "Je relis le contrat encore et encore. Moi. Footballeur professionnel.",
        M012: "C'est fait, {agent}. {newclub}. Nouveau chapitre. Merci de l'avoir bouclé.",
        M013: "{newclub} ! Nouvelle ville, nouveau championnat, tout est nouveau. C'est pour ça que je vis.",
        M014: "{newclub}, alors. Un grand changement pour moi. Je te fais confiance sur le fait que c'est le bon.",
        M015: "Il faut que je te dise quelque chose. {newclub}, c'était MON club quand j'étais gamin. Tu viens de réaliser le rêve d'un gosse. Je ne l'oublierai pas. Jamais.",
        M016: "Tu savais ce que {newclub} représentait pour moi. C'est la plus grande chose que quelqu'un ait faite pour ma carrière. Merci.",
        M017: "Tu te rappelles ce que je t'avais dit vouloir ? {ambition} ? … C'est fait. On l'a vraiment fait.",
        M018: "{ambition}. Je l'ai dit, je l'ai fait. Et tu y es pour quelque chose, {agent}. Il faut rendre à César.",
        M019: "Ils disent {weeks} semaines, {agent}. Je n'arrive même pas à regarder mes crampons là.",
        M020: "Je SAVAIS que ce tacle allait arriver. {weeks} semaines. Je suis furieux.",
        M021: "{weeks} semaines d'arrêt. J'ai déjà demandé le programme de rééducation. Ça pique quand même.",
        M022: "Ha, merci. Des journées comme celle-ci, ça vaut tous les efforts.",
        M023: "Enfin quelqu'un qui le dit comme c'est !",
        M024: "D'accord, d'accord. Une soirée pour fêter ça, puis retour à la normale.",
        M025: "Tu as raison. Tête baissée, au suivant.",
        M026: "Je suis d'accord. On fête ce soir, on remet les compteurs à zéro demain.",
        M027: "En toute discrétion ? D'accord. Mais je garde le résumé en boucle.",
        M028: "Tu es venu jusqu'ici ? Ça… ça compte beaucoup, {agent}.",
        M029: "Tu n'étais pas obligé de venir. Je suis content que tu l'aies fait.",
        M030: "Les fleurs sont arrivées. Belle attention. Envoie-moi aussi quelques matches à regarder.",
        M031: "Avant que tu partes. Je t'ai pris quelque chose. Pas de discussion, c'est déjà payé. {thing}. Tu l'as mérité dix fois.",
        M032: "Mon père disait toujours : prends soin de ceux qui prennent soin de toi. Alors tiens. {thing}. Merci, {agent}.",
        M033: "Je l'ai choisi moi-même. {thing} ! Seulement le meilleur pour mon agent, évidemment.",
        M034: "Ce n'est pas grand-chose, mais… {thing}. Pour tout ce que tu fais et que personne ne voit.",
        M035: "Bien. Chaque fois que tu le regarderas, souviens-toi qu'on a fait ça ensemble.",
        M036: "C'est tout ce que je voulais entendre. On prend soin l'un de l'autre, toujours.",
        M037: "Ha ! Ne change jamais, {agent}. Jamais.",
        M038: "Tu vois, c'est POUR ÇA qu'on s'entend bien.",
        M039: "Je veux t'avoir avec nous pour {occasion}. Pas comme mon agent. Comme un ami. Dis-moi que tu viendras.",
        M040: "C'est bientôt {occasion}. Petit comité seulement, la famille et les gens qui comptent. Ça t'inclut, {agent}.",
        M041: "{occasion}. Ça va être L'événement de l'été. Tu es sur la liste, évidemment.",
        M042: "Tu viens ? Ça compte énormément. On se voit là-bas !",
        M043: "Vraiment ? Je… merci. Ce ne serait pas pareil sans toi.",
        M044: "Tu ne peux pas venir ? Dommage. Mais c'est très généreux, merci.",
        M045: "D'accord. Emploi du temps chargé, je comprends. … Je comprends.",
    },

    // --- what the AGENT says when you pick a choice (Dialogue.SAY, keyed "scene:choice") ---
    say: {
        'complaint:listen': "Parle-moi. Quoi que ce soit, je veux l'entendre, tout.",
        'complaint:promise': "Très bien. Voilà ce que je vais faire à ce sujet.",
        'complaint:pushback': "Je t'entends. Mais laisse-moi être franc une seconde.",
        'complaint:deflect': "Ne brûlons pas les étapes. Laisse encore un peu de temps.",
        'promise:move': "Laisse-moi faire. Je te trouverai le bon point de chute : le bon club, pas n'importe quel club.",
        'promise:newContract': "Je t'obtiens le contrat que tu mérites dans ce club. Donne-moi un peu de temps.",
        'promise:playingTime': "Je vais parler sérieusement à l'entraîneur de ton temps de jeu. On va régler ça.",
        'promise:renegotiateRep': "Et je prendrai moins de mon côté pour que ça se fasse. C'est dire à quel point je te soutiens.",
        'gift:praise': "Tu l'as mérité. Entièrement. Que personne ne te dise le contraire.",
        'gift:modest': "Ce n'est rien, vraiment. Je voulais juste que tu saches que je suis attentif.",
        'prematch:calm': "Respire. Tu as déjà fait tout le travail. Va simplement jouer ton match.",
        'prematch:fireup': "C'est ta soirée. Vas-y et prends-la, ne laisse rien derrière toi.",
        'prematch:bonus': "Je te dis une chose : tu gagnes celui-là, et il y a un petit extra pour toi.",
        'bonus:small': "Tu gagnes ce soir et il y a un cadeau pour toi. Ma parole.",
        'bonus:medium': "Gagne ça et je m'occuperai bien de toi. C'est une promesse.",
        'bonus:large': "Ramène ça à la maison et je ferai en sorte que ça en vaille largement la peine. Ma parole.",
        'postwin:toast': "Viens là, c'était quelque chose. Profitons de celle-là.",
        'postwin:quiet': "Magnifiquement fait. Je te laisse retourner avec les gars.",
        'postwin:tab': "Ce soir, tout est pour moi. Tu l'as plus que mérité.",
        'postloss:sit': "Assieds-toi avec moi une minute. Ça pique maintenant, ça ne durera pas.",
        'postloss:space': "Je te laisse. La tête haute. On y retourne.",
        'postloss:speech': "Écoute-moi. Un match ne te définit pas. Ne t'avise pas de l'oublier.",
        'farewell:career': "Quelle carrière tu as eue. Tu devrais être fier de chaque minute.",
        'farewell:personal': "Oublie le football une seconde : je suis simplement content de t'avoir connu.",
        'checkin:q-life': "Alors, comment ça va en dehors du terrain ? Tout va bien à la maison ?",
        'checkin:q-club': "Comment tu t'adaptes au club ? Tu t'entends bien avec tout le monde ?",
        'checkin:q-ambition': "Jusqu'où veux-tu emmener tout ça ? On vise quoi vraiment ?",
        'checkin:q-room': "Avec qui tu traînes dans le vestiaire ces temps-ci ?",
        'checkin:q-none': "Aucun ordre du jour aujourd'hui. Je voulais juste voir comment tu allais.",
        'moment:praise': "C'était un beau moment. Savoure-le, tu l'as mérité.",
        'moment:modest': "Brillant en silence, ça. Bien joué.",
        'injury:there': "Je viens te voir. Tu ne vas pas traverser ça tout seul.",
        'injury:flowers': "Je t'envoie quelque chose, juste pour que tu saches que je pense à toi.",
        'thanks:cherish': "Ça compte énormément pour moi. Je le garde, vraiment.",
        'thanks:banter': "Tu n'étais pas obligé, gros sentimental. Mais merci, sincèrement.",
        'invite:attend': "Je ne manquerais ça pour rien au monde. Je serai là, en tribunes.",
        'invite:gift': "Je ne peux pas être là en personne, mais laisse-moi envoyer quelque chose pour marquer le jour.",
        'invite:decline': "Je ne peux pas être là cette fois, mais je suis avec toi en pensée, tu le sais.",
    },

    // --- choice buttons (keyed "scene|choice") ---
    choices: {
        'complaint|listen': { label: "L'écouter", hint: "Sans risque. Il veut être entendu." },
        'complaint|promise': { label: "Lui faire une promesse", hint: "Ouvre une promesse avec une véritable échéance." },
        'complaint|pushback': { label: "Le contredire", hint: "Lui dire qu'il a tort. Risqué, cela dépend de l'homme." },
        'complaint|deflect': { label: "Minimiser", hint: "Gagne du temps. Il pourrait t'en tenir rigueur." },
        'gift|praise': { label: "Tu l'as mérité" },
        'gift|modest': { label: "Tête baissée et joue" },
        'prematch|calm': { label: "Le calmer", hint: "Apaiser les nerfs avant le plus grand match de son année." },
        'prematch|fireup': { label: "Le galvaniser", hint: "Faire monter l'adrénaline." },
        'prematch|bonus': { label: "Promettre une prime de victoire", hint: "Choisis un cadeau qu'il recevra s'ils soulèvent le trophée. Ne coûte rien s'ils perdent." },
        'postwin|toast': { label: "Le féliciter devant tout le monde", hint: "Éloge public. Certains adorent, d'autres sont mal à l'aise." },
        'postwin|quiet': { label: "Un mot en privé", hint: "Juste vous deux, loin du bruit." },
        'postwin|tab': { label: "Payer la tournée ce soir", hint: "Ça te coûte, ça compte beaucoup." },
        'postloss|sit': { label: "Rester avec lui", hint: "Ne rien dire. Juste rester." },
        'postloss|space': { label: "Lui laisser de l'espace", hint: "Certaines blessures se referment seules." },
        'postloss|speech': { label: "On y retourne la saison prochaine", hint: "Droit à la suite." },
        'farewell|career': { label: "À une sacrée carrière" },
        'farewell|personal': { label: "À l'homme, pas seulement au joueur" },
        'checkin|q-life': { label: "Lui demander sa vie en dehors du football" },
        'checkin|q-club': { label: "Lui demander quel est son club favori" },
        'checkin|q-ambition': { label: "Lui demander ses ambitions" },
        'checkin|q-room': { label: "Lui demander comment est le vestiaire" },
        'checkin|q-none': { label: "Rien de particulier", hint: "C'est parfois ce qui en dit le plus." },
        'moment|praise': { label: "Le féliciter chaudement" },
        'moment|modest': { label: "En toute discrétion" },
        'injury|there': { label: "Lui rendre visite en personne" },
        'injury|flowers': { label: "Envoyer des fleurs" },
        'thanks|cherish': { label: "Je vais le garder précieusement" },
        'thanks|banter': { label: "Il était temps que tu me rembourses" },
        'invite|attend': { label: "Libérer ton agenda, tu y seras", hint: "Un week-end de ton temps. Cela compte plus que n'importe quel cadeau." },
        'invite|gift': { label: "Envoyer un cadeau généreux", hint: "Tu ne peux pas venir, mais l'attention arrive." },
        'invite|decline': { label: "Décliner poliment", hint: "Il le remarquera." },
    },

    // --- discovered "vocabulary": hobbies, keepsakes and occasions, keyed by the English value ---
    // Stored on the player in English, so they are localised at fill() time. The articles are part
    // of the value, because the lines read "à fond dans {hobby}" / "du temps pour {hobby}".
    vocab: {
        'golf': "le golf",
        'fishing': "la pêche",
        'gaming': "les jeux vidéo",
        'chess': "les échecs",
        'cooking': "la cuisine",
        'classic cars': "les voitures anciennes",
        'photography': "la photographie",
        'making music': "la musique",
        'padel': "le padel",
        'poker': "le poker",
        'a signed shirt from his debut': "un maillot dédicacé de ses débuts",
        'a watch with a date engraved on the back': "une montre avec une date gravée au dos",
        'a framed photo of the two of you at his first signing': "une photo encadrée de vous deux lors de sa première signature",
        'the match ball from his best game, signed by the whole squad': "le ballon de son meilleur match, dédicacé par tout l'effectif",
        'a bottle from a vineyard he part-owns': "une bouteille d'un vignoble dont il est copropriétaire",
        'my wedding': "mon mariage",
        "the little one's christening": "le baptême du petit",
        'a gift': "un cadeau",
    },

    // --- ambitions: a pronoun-free infinitive phrase, so it reads both as a label and inside a
    // spoken line ("je veux {ambition}", "{ambition} ? C'est fait."). The fallbacks carry the
    // article the template needs: "en {league}", "pour {club}", "à {fav}".
    amb: {
        types: {
            league: "jouer un jour en {league}",
            dreamclub: "jouer un jour pour {club}",
            boyhood: "terminer là où tout a commencé, à {fav}",
            title: "gagner un titre de champion",
            cup: "soulever une coupe",
            europe: "jouer en Coupe d'Europe",
            goals: "atteindre {target} buts en carrière",
            topflight: "jouer dans l'un des cinq grands championnats",
            abroad: "jouer à l'étranger",
        },
        dflt: "arriver au sommet",
        favFallback: "mon club d'enfance",
        leagueFallback: "division supérieure",
        clubFallback: "un grand club",
    },

    // --- milestone labels, frozen into the line when the moment is queued (the player is speaking) ---
    mile: {
        apps: "{n} matches",
        goals: "{n} buts en carrière",
    },

    // --- the cash thank-you gift, filled into {thing} ---
    envelope: "une enveloppe. Dedans : €{amt} pour l'agence",
};
if (typeof module !== 'undefined' && module.exports) module.exports = { DIALOGUE_FR };
