// Dutch translations for the dialogue system, keyed by the SAME stable line ids as
// js/dialogue-data.js (the English source, generated from dialogue_lines.xlsx). Any id missing
// here falls back to the English workbook text — so this file may lag the workbook safely.
// dialogue.js picks these up through Dialogue._pack() when I18n.locale === 'nl'.
//
// Informal "je/jij" both ways, as in the German, Spanish, French, Portuguese and Italian packs.
// This is spoken conversation between an agent and a player who know each other well; the written
// correspondence in js/i18n-nl.js stays on formal "u". At a low bond the client still calls you
// "Meneer Mercer" while saying "je" — the same small tension the other packs ship with, unavoidable
// because a line's pronoun cannot vary with the bond level.
const DIALOGUE_NL = {
    // --- player spoken lines (DIALOGUE_DATA[sheet][*].text, by id) ---
    lines: {
        // Complaint
        C001: "Baas, ik heb minuten nodig. Ik train de hele week goed, en dan is het zaterdag en zit ik vanaf de bank te kijken.",
        C002: "Kunnen we praten? Ik ben niet naar {club} gekomen om op de bank te zitten. Er moet iets veranderen.",
        C003: "Ik vraag geen wonderen, {agent}. Ik vraag een eerlijke kans op een basisplaats.",
        C004: "Ik ben het zat om vanaf de zijlijn te kijken, {agent}. Als de trainer me niet laat spelen, zoek dan iemand die dat wel doet!",
        C005: "Kijk naar mijn trainingscijfers, en kijk dan wie er voor me staat. Dat klopt niet, en ik wil weten hoe jij het ziet.",
        C006: "Mensen blijven vragen waarom ik niet speel. Ik heb geen antwoord. Dat is een probleem voor ons beiden.",
        C007: "Onder ons: ik zie {club} nergens heen gaan. Ik moet weten dat je een plan met me hebt.",
        C008: "Dit is niet het project dat ze me hebben verkocht, {agent}. De kleedkamer voelt vlak.",
        C009: "Ik heb deze club alles gegeven en ik weet niet meer zeker of dat nog wederzijds is.",
        C010: "Ik had nooit gedacht dat ik dit zou zeggen, maar de club is veranderd. Dit is niet de plek waar ik voor tekende.",
        C011: "Ik heb hier alles gezien wat er te zien is. Ik heb een nieuwe uitdaging nodig voordat ik vastloop.",
        C012: "Er voelt iets niet goed bij de club de laatste tijd. Ik wil geen drama, ik wil alleen dat het opgelost wordt.",
        C013: "Heb je gezien wat die nieuwe aanwinst verdient? Ik presteer beter dan hij voor de helft van het geld.",
        C014: "Mijn contract past niet meer bij wat ik breng. Wanneer gaan we dat rechtzetten?",
        C015: "Ik praat niet graag over geld, {agent}, maar iemand moet het doen. Mijn salaris loopt achter op de kleedkamer.",
        C016: "Cijfers liegen niet, {agent}. De mijne gaan omhoog en mijn salaris niet. Regel het.",
        C017: "Ik vind het ongemakkelijk om het zelfs te noemen, maar de jongens zeggen dat ik onderbetaald word. Hebben ze gelijk?",
        C018: "Een speler met mijn profiel op dit salaris? Dat ziet er slecht uit. Dat IS slecht.",
        C019: "Eerlijk? Ik hoor je niet tenzij er ergens brand is. Daar heb ik niet voor getekend.",
        C020: "Ik moet weten dat je nog steeds achter me staat, {agent}. De laatste tijd twijfel ik daaraan.",
        C021: "Waar heb jij gezeten?! Andere zaakwaarnemers bellen hun spelers elke week. Ik krijg stilte.",
        C022: "Ik ben je lang trouw gebleven, {agent}. Zeg me alleen dat dat nog iets betekent.",
        C023: "We zijn voorbij het praten, {agent}. Zorg dat ik speel of zorg dat ik wegkom. Dat zijn de opties.",
        C024: "Elke week op die bank kost me iets. Ik wil nu een oplossing, niet weer een gesprek.",
        C025: "Genoeg! Ik dien zelf een transferverzoek in als dat nodig is om te kunnen voetballen.",
        C026: "Ik ben nu serieus. Ga op zoek naar een uitweg, of ik maak openbaar dat ik weg wil.",
        C027: "Over deze plek is mijn besluit gevallen. Wat ik van jou nodig heb is een plan, deze week.",
        C028: "Vorige keer dat we praatten gebeurde er niets. Regel een behoorlijk contract of ik vind iemand die dat kan.",
        C029: "Je had je kans om mijn contract stil te regelen. Nu wordt het luid.",
        C030: "Ik heb met andere bureaus gesproken, {agent}. Geef me één goede reden om te blijven.",
        C031: "Dit is wat mij betreft je laatste waarschuwing. Laat me zien dat mijn carrière je nog iets kan schelen.",
        C032: "Bedankt dat je naar me hebt geluisterd. Dat helpt meer dan je denkt.",
        C033: "Oké. Ik voel me beter nu ik het heb gezegd. We zien hoe de komende weken gaan.",
        C034: "Jij wist altijd wanneer je gewoon moest luisteren. Dat waardeer ik, {agent}.",
        C035: "Sorry dat ik zo bij je heb uitgehuild. Maar ja, bedankt.",
        C036: "Goed. Ik heb gezegd wat ik moest zeggen. Vergeet het alleen niet.",
        C037: "Oké. Ik hou je eraan, {agent}.",
        C038: "Dat is wat ik moest horen. Laat me niet vallen.",
        C039: "Afgesproken. Je hebt me nog nooit laten zitten, dus ik vertrouw erop.",
        C040: "Goed. Zet het op papier als dat moet. Ik ga de weken tellen.",
        C041: "Jouw woord is altijd genoeg voor me geweest. Zorg dat ik daar geen spijt van krijg.",
        C042: "Hm. Dat antwoord had ik niet verwacht. Maar misschien heb je gelijk.",
        C043: "Dat is hard om te horen, maar het is eerlijk. Oké. Ik zet mijn schouders eronder.",
        C044: "Dat is een eerlijke analyse. Daar kan ik mee werken. Bedankt dat je recht voor de raap bent.",
        C045: "Je hebt gelijk over de cijfers. Ik richt me op wat ik zelf in de hand heb.",
        C046: "Serieus? Ik kom bij je met een probleem en jij zegt dat IK het probleem ben?",
        C047: "Wauw. Goed om te weten waar je staat. Dit gesprek is voorbij.",
        C048: "Je hebt wel lef! Aan wiens kant sta jij eigenlijk?!",
        C049: "Nee. NEE. Jij gaat mij niet de les lezen. Los het op of ik vind iemand die dat wel doet.",
        C050: "Juist. 'Het lost zichzelf wel op.' Die heb ik eerder gehoord.",
        C051: "Goed, we zullen zien. Maar ik wacht niet eeuwig, {agent}.",
        C052: "Hm. Dat is niet echt een antwoord, hè.",

        // Gifts
        G001: "Ah, mooi. Kleine dingen tellen ook. Bedankt, {agent}.",
        G002: "Je hebt het onthouden! Bedankt, dat is een mooi gebaar.",
        G003: "Dat had je niet hoeven doen. Maar bedankt, echt.",
        G004: "Leuk. De gedachte telt, neem ik aan.",
        G005: "Dat is nou een echt cadeau. Bedankt, serieus.",
        G006: "Oké, je hebt smaak. Dat geef ik je.",
        G007: "Dit is klasse. Wacht tot de jongens het zien.",
        G008: "Dat is echt attent. Dat krijgt een mooie plek thuis.",
        G009: "Dit is… wauw. Dit had je echt niet hoeven doen. Bedankt, {agent}.",
        G010: "Ongelooflijk. Ik weet niet wat ik moet zeggen. Bedankt.",
        G011: "ZO behandel je een sterspeler. Prachtig!",
        G012: "Het is te veel, {agent}. Echt. Maar ik zal het koesteren.",
        G013: "Na al die jaren verras je me nog steeds. Bedankt.",
        G014: "Alweer een? Bedankt, denk ik.",
        G015: "Je verwent me de laatste tijd. Dan verliest het een beetje zijn glans, weet je.",
        G016: "Twee cadeaus zo kort na elkaar? Nu vraag ik me af wat het slechte nieuws is.",
        G017: "Ha! Die neem ik aan.",
        G018: "Zeg dat volgende keer harder, er is pers in de buurt.",
        G019: "Ik doe alleen mijn werk. Maar bedankt.",
        G020: "Begrepen. Weer aan het werk.",
        G021: "Precies mijn plan.",
        G022: "Jij kan ook niet lachen. Maar goed.",

        // Final (attend the final)
        F001: "Grote dag vandaag, {agent}. De kleedkamer gonst. Mooi dat je bent gekomen.",
        F002: "Dus dit is het. Negentig minuten van een medaille.",
        F003: "Nooit eerder een finale gespeeld met mijn zaakwaarnemer op de tribune. Geen druk dus.",
        F004: "Ik kan niet stilzitten, {agent}. Ik wil NU door die muur heen rennen.",
        F005: "Ik heb {opponent} goed bekeken. Standaardsituaties gaan het beslissen, let op.",
        F006: "Finales zijn mijn podium, {agent}. Vandaag komen ze er allemaal achter.",
        F007: "Wat er ook gebeurt daarbuiten, bedankt dat je bent gekomen. Dat betekent veel.",
        F008: "Iedereen die ik ken zit vandaag op de tribune. Ik wil ze alleen niet laten zakken.",
        F009: "Hierom voetbal ik. Voor zulke dagen.",
        F010: "Dit winnen met DEZE club zou alles voor me betekenen.",
        F011: "Winstpremie in mijn contract, bekermedaille in de kast. Laten we ze allebei pakken.",
        F012: "Ja. Ja, je hebt gelijk. Diep ademhalen. Het komt goed.",
        F013: "Oké. Oké. Hoofd leeg, benen los. Bedankt, {agent}.",
        F014: "Eens. Proces boven emotie. Tot na de wedstrijd.",
        F015: "Rustig? Het gaat prima, {agent}. Bewaar de toespraak.",
        F016: "Rustig is voor de bank. Ik ben hiervoor gemaakt.",
        F017: "JA. Dat wilde ik horen!",
        F018: "Kijk maar naar me daarbuiten. Het eerste doelpunt is voor jou.",
        F019: "Rustig, rustig. Ik heb een helder hoofd nodig, geen strijdkreet.",
        F020: "Ik waardeer het, maar ik bereid me op mijn eigen manier voor.",
        F021: "Ha! DAT is nou motivatie. Afgesproken.",
        F022: "Nu spreek je mijn taal. Beschouw hem als gewonnen.",
        F023: "Je hoeft me niet om te kopen, {agent}. Maar goed, afgesproken.",
        F024: "WE HEBBEN HET GEDAAN! Kun je het geloven?! Kom hier, {agent}!",
        F025: "Kampioen! Hier droom ik al van sinds ik een kind was!",
        F026: "Heb je dat GEZIEN?! Hier gaan ze het jaren over hebben!",
        F027: "We hebben het echt gedaan. Het hele team was ongelooflijk.",
        F028: "Voor deze club. Voor iedereen op die tribunes. Ik ben zo trots, {agent}.",
        F029: "JAAA! Niemand geloofde in ons! NIEMAND!",
        F030: "Harder, {agent}! Vanavond wordt er gefeest!",
        F031: "Zeg het nog eens voor de camera's!",
        F032: "Ha, bedankt. Een beetje veel waar iedereen bij is, maar bedankt.",
        F033: "Ga toch zitten, je maakt me verlegen. Maar bedankt.",
        F034: "Dat betekent meer dan welke kop in de krant ook. Bedankt.",
        F035: "Waardeer ik. In stilte is precies zoals ik het het liefst heb.",
        F036: "Even onder vier ogen? Vanavond? Kom op, leef een beetje!",
        F037: "De zaakwaarnemer betaalt de drankjes! DAT is nou service!",
        F038: "Royaal EN slim. De jongens gaan dit onthouden.",
        F039: "Zo dichtbij. Zo verschrikkelijk dichtbij. Ik weet niet wat ik moet zeggen, {agent}.",
        F040: "Die gaat nog lang pijn doen.",
        F041: "Niet. Zeg… zeg nog even niets.",
        F042: "Sorry. Ik had het gevoel dat ik daarbuiten iedereen heb laten zakken.",
        F043: "De fans hadden vandaag beter verdiend. Dat is wat me sloopt.",
        F044: "Bedankt dat je bent gebleven. De meeste mensen laten je er gewoon alleen mee.",
        F045: "Ik ben blij dat je hier bent. Echt.",
        F046: "Ik waardeer het, maar ik wil nu eigenlijk graag even alleen zijn.",
        F047: "Ja. Ik bel je over een paar dagen. Bedankt voor je begrip.",
        F048: "Goede keuze. Ik ben vanavond geen gezelschap.",
        F049: "Juist. Na een nederlaag gaat iedereen altijd weg. Genoteerd.",
        F050: "Je hebt gelijk. Volgend seizoen begint morgen. We gaan er weer voor.",
        F051: "Correct. Nederlagen zijn data. We worden er beter van.",
        F052: "Volgend seizoen? We hebben NET verloren, {agent}. Voel de sfeer even aan.",
        F090: "We hebben vandaag alles goed gedaan, {agent}. Het was alleen niet genoeg, de titel is weg door die andere uitslag.",
        F091: "We hebben gewonnen en het glipte alsnog weg. Zo dichtbij. Ik kan niet geloven dat het voorbij is.",
        F092: "Ons deel is gedaan, wij hebben geleverd. Het is de wedstrijd waar we geen invloed op hadden die ons de kop heeft gekost.",

        // Farewell (retirement)
        W001: "Nou, {agent}. Dat was het dan. Schoenen aan de wilgen. Bedankt voor het werk door de jaren heen.",
        W002: "Het is dus officieel. Gestopt. We hadden onze ups en downs, maar de klus is geklaard.",
        W003: "Vreemd gevoel, {agent}. Geen wedstrijddagen meer. Ik ben blij dat je een groot deel van de rit mee hebt gemaakt.",
        W004: "Dat was het laatste fluitsignaal. Bedankt voor de jaren, {agent}. Je hebt me vaker goed behandeld dan niet.",
        W005: "Weet je, van alle mensen in het voetbal ben jij een van de weinigen die ik echt ga missen. Wat een rit was het.",
        W006: "Ik blijf denken aan alles wat we samen hebben doorstaan. Contracten, transfers, alles. Bedankt, vriend.",
        W007: "Eerst dit: mijn afscheidswedstrijd. Eerste rij, eregast. Geen discussie. Je was familie door alles heen.",
        W008: "Ze vroegen me wie het belangrijkst was in mijn carrière. Ik zei mijn familie. En in dezelfde adem noemde ik jou, {agent}.",
        W009: "Wat een carrière, dat klopt. En ik had de helft ervan niet zonder jou gekund.",
        W010: "Ze gaan de goals onthouden. Zorg jij er alleen voor dat ze mijn naam goed spellen in de recordboeken.",
        W011: "Het was een mooi oeuvre. Daar mogen we allebei tevreden mee zijn.",
        W012: "Dat betekent eerlijk gezegd meer dan de prijzen. Bedankt voor alles.",
        W013: "Hou op, straks ga ik nog huilen. Bedankt. Voor alles.",
        W014: "We zijn bij elkaar gebleven, hè. Door alles heen. Dat is zeldzaam in dit spel.",
        W015: "Nu maak je me aan het huilen. Ik ben zo blij dat ik jou heb ontmoet!",
        W016: "Het betekent de wereld voor me dat je er de hele tijd bij bent geweest!",

        // Check-in
        K001: "Hé {agent}! Goede timing, training net klaar. Wat heb je op je hart?",
        K002: "Kijk eens wie we daar hebben. Alles goed, of is dit zakelijk?",
        K003: "Je belde, ik ben er. De koffie is wel voor jouw rekening.",
        K004: "Maak het kort, ik moet naar de gym. Grapje. Een beetje. Wat is er?",
        K005: "Kom je even kijken bij je favoriete cliënt? Slimme zet.",
        K006: "Altijd leuk als je langskomt, {agent}. Echt.",
        K007: "Kom binnen, kom binnen. Fijn om een bekend gezicht te zien.",
        K008: "Familie? Eerlijk gezegd ben ik er nu alleen. Voetbal vraagt alles wat ik heb.",
        K009: "Alleen ik, mijn schoenen en een koffer. Past me voorlopig prima.",
        K010: "Mijn betere helft houdt me normaal. Dit had ik nooit alleen gekund.",
        K011: "De kinderen zijn alles, {agent}. Elke wedstrijd die ik speel is voor hen.",
        K012: "De kleintjes zijn de baas in huis. Het mooiste dat me ooit is overkomen.",
        K013: "De laatste tijd? Ik zit helemaal in {hobby}. Houdt mijn hoofd rustig tussen wedstrijden.",
        K014: "Ik maak tijd voor {hobby}. Herstel voor het hoofd, niet alleen voor de benen.",
        K015: "Eerlijk gezegd niks nieuws. Trainen, thuis, herhalen. Ik ben tevreden.",
        K016: "Al sinds ik klein was? {favclub}. Mijn vader nam me een keer mee naar een wedstrijd en dat was dat.",
        K017: "Simpel. {favclub}. Ik had de posters, de shirts, alles.",
        K018: "{favclub}, altijd. Sommige dingen veranderen niet, waar je ook speelt.",
        K019: "Ik hou van {favclub}! Ik kan niet stilzitten als zij spelen.",
        K020: "{favclub}. Mijn oma heeft al 52 jaar een seizoenkaart, en ze heeft de hele familie meegetrokken.",
        K021: "Eerlijk? Ooit wil ik {ambition}. Dat is de droom.",
        K022: "Onder ons: ik wil {ambition}. En ik wil dat iedereen het ziet.",
        K023: "Ik heb mezelf één doel gesteld: {ambition}. Alles wat ik doe wijst daarheen.",
        K024: "Eén ding zou ik nog graag willen: {ambition}. Dat zou geweldig zijn voor mij en mijn vrienden.",
        K025: "Ik moet {ambition}. En ik wil altijd meedoen om de prijzen!",
        K026: "Ik wil {ambition}. Maar het belangrijkste is dat mijn vrienden en familie bij elke stap naast me staan.",
        K027: "Kleedkamer is goed. Paar grote ego's, maar noem me er een zonder.",
        K028: "Eerlijk, geweldige groep jongens. De beste waar ik deel van heb uitgemaakt.",
        K029: "Er is één man die steeds mijn parkeerplek inpikt. Daar hebben we woorden over gehad.",
        K030: "Eerlijk gezegd heb ik het gevoel dat mijn ploeggenoten mijn klasse niet genoeg waarderen…",
        K031: "Ha! Het is meestal één groot feest, en jij weet dat ik de DJ ben!",
        K032: "Ik voel me hier erg thuis! Ik zie op dit moment geen enkele reden om ooit weg te gaan.",
        K033: "Ik voel me hier erg thuis! Ik zie op dit moment geen enkele reden om ooit weg te gaan.",
        K034: "We hebben een stel valse honden tussen ons zitten… Altijd achter de rug van anderen praten.",
        K035: "Er zit nu geen echte teamgeest in… Ik denk dat de trainer een selectie huurlingen heeft samengesteld.",
        K036: "Ik kijk soms om me heen en ben zo dankbaar dat ik deel uitmaak van dit geweldige team! Bedankt dat je dit voor mij mogelijk hebt gemaakt.",
        K037: "Ik heb veel vrienden gemaakt in mijn tijd bij deze club. Ik voel me echt gezegend.",
        K038: "Ha, gewoon even bijpraten? Dat waardeer ik. Echt.",
        K039: "Geen bijbedoelingen? Dat is een primeur voor een zaakwaarnemer. Dat bevalt me.",
        K040: "Dat is aardig van je. Het is hier soms eenzaam, weet je.",
        K041: "Goed je te zien, {agent}! Waar wilde je over praten?",
        K042: "Hé, hoe gaat het? Ik hoop dat je niet om geld komt bedelen! Grapje natuurlijk, wat is er aan de hand?",
        K043: "Aardig dat je contact opneemt, waar wilde je me over spreken?",

        // Career moments
        M001: "Mijn eerste minuten bij de hoofdmacht, {agent}! Heb je het gezien? Ik heb het shirt nog aan. Ik doe het niet uit.",
        M002: "Ik heb echt gespeeld. Een echte wedstrijd bij de hoofdmacht. Ik wacht nog steeds tot iemand zegt dat het een fout was.",
        M003: "EERSTE GOAL! Heb je hem gezien?! Ik heb het fragment al vijftig keer bekeken.",
        M004: "Hij is er eindelijk in gegaan. Voelt onwerkelijk, echt.",
        M005: "DRIE! Een hattrick, {agent}! Ze gaven me de wedstrijdbal en alles!",
        M006: "Een hattrick. De wedstrijdbal wordt ingelijst. De schoenen misschien ook.",
        M007: "{milestone}. Zag het net in het wedstrijdprogramma. De tijd vliegt, hè?",
        M008: "{milestone}. Een mooi getal. Nu op naar het volgende.",
        M009: "{milestone}. En bij de meeste was jij erbij, {agent}.",
        M010: "Mijn eerste profcontract, {agent}! Ondertekend en alles. Dit is nu echt, hè?",
        M011: "Ik blijf het contract steeds opnieuw lezen. Ik. Een profvoetballer.",
        M012: "Het is gelukt, {agent}. {newclub}. Nieuw hoofdstuk. Bedankt dat je het over de lijn hebt getrokken.",
        M013: "{newclub}! Nieuwe stad, nieuwe competitie, alles nieuw. Hier leef ik voor.",
        M014: "{newclub} wordt het dan. Grote verandering voor me. Ik vertrouw erop dat het de juiste is.",
        M015: "Ik moet je iets vertellen. {newclub} was MIJN club toen ik klein was. Je hebt net de droom van een kleine jongen waargemaakt. Dit vergeet ik nooit. Nooit.",
        M016: "Je wist wat {newclub} voor me betekende. Dit is het grootste dat iemand ooit voor mijn carrière heeft gedaan. Bedankt.",
        M017: "Weet je nog wat ik zei dat ik wilde? {ambition}? … Gelukt. We hebben het echt gedaan.",
        M018: "Precies wat ik wilde: {ambition}. Gezegd en gedaan. En jij hebt geholpen, {agent}. Eer wie eer toekomt.",
        M019: "Ze zeggen {weeks} weken, {agent}. Ik kan nu niet eens naar mijn schoenen kijken.",
        M020: "Ik WIST dat die tackle zou komen. {weeks} weken. Ik ben woedend.",
        M021: "{weeks} weken eruit. Ik heb het revalidatieplan al opgevraagd. Het steekt wel, hoor.",
        M022: "Ha, bedankt. Voor zulke dagen doe je het allemaal.",
        M023: "Eindelijk iemand die het zegt zoals het is!",
        M024: "Goed, goed. Eén avondje feest, en dan weer normaal doen.",
        M025: "Je hebt gelijk. Kop naar beneden, volgende klus.",
        M026: "Eens. Vanavond vieren, morgen weer op nul.",
        M027: "Rustig aan? Goed. Maar ik hou de samenvatting op repeat.",
        M028: "Ben je helemaal hierheen gekomen? Dat… betekent veel, {agent}.",
        M029: "Je hoefde niet te komen. Ik ben blij dat je het deed.",
        M030: "De bloemen zijn aangekomen. Mooi gebaar. Stuur me ook wat wedstrijden om te kijken.",
        M031: "Voordat je gaat. Ik heb iets voor je. Geen discussie, het is al betaald: {thing}. Je hebt het tien keer verdiend.",
        M032: "Mijn vader zei altijd: zorg voor de mensen die voor jou zorgen. Dus hier: {thing}. Bedankt, {agent}.",
        M033: "Zelf uitgezocht: {thing}! Alleen het beste voor mijn zaakwaarnemer, natuurlijk.",
        M034: "Het is niet veel, maar… {thing}. Voor alles wat je doet dat niemand ziet.",
        M035: "Goed. Denk er elke keer dat je ernaar kijkt aan dat we dit samen hebben gedaan.",
        M036: "Dat is alles wat ik wilde horen. Wij zorgen voor elkaar, altijd.",
        M037: "Ha! Verander nooit, {agent}. Verander nooit.",
        M038: "Zie je, HIEROM kunnen wij zo goed met elkaar.",
        M039: "Ik wil je erbij hebben op {occasion}. Niet als mijn zaakwaarnemer. Als vriend. Zeg dat je komt.",
        M040: "Het is binnenkort {occasion}. Kleine kring, familie en de mensen die tellen. Daar hoor jij bij, {agent}.",
        M041: "Over {occasion}: dat wordt HET evenement van de zomer. Je staat op de lijst, natuurlijk.",
        M042: "Kom je? Dat betekent de wereld voor me. Tot dan!",
        M043: "Echt? Ik… bedankt. Het zou niet hetzelfde zijn zonder jou.",
        M044: "Kun je niet? Jammer. Maar dat is heel royaal, bedankt.",
        M045: "Juist. Volle agenda, ik snap het. … Ik snap het.",
    },

    // --- what the AGENT says when you pick a choice (Dialogue.SAY, keyed "scene:choice") ---
    say: {
        'complaint:listen': "Vertel het maar. Wat het ook is, ik wil het horen, alles.",
        'complaint:promise': "Goed. Dit ga ik eraan doen.",
        'complaint:pushback': "Ik hoor je. Maar laat me even eerlijk tegen je zijn.",
        'complaint:deflect': "Laten we niet te hard van stapel lopen. Geef het nog even wat tijd.",
        'promise:move': "Laat het aan mij over. Ik vind de juiste plek voor je — de juiste club, niet zomaar een club.",
        'promise:newContract': "Ik regel het contract dat je verdient bij deze club. Geef me even tijd.",
        'promise:playingTime': "Ik ga serieus met de trainer praten over je speeltijd. Dat lossen we op.",
        'promise:renegotiateRep': "En ik neem minder van mijn kant om het mogelijk te maken. Zo sterk sta ik achter je.",
        'gift:praise': "Je hebt het verdiend. Alles. Laat niemand je iets anders vertellen.",
        'gift:modest': "Het is niets, echt. Ik wilde alleen dat je weet dat ik oplet.",
        'prematch:calm': "Haal even diep adem. Het werk heb je al gedaan. Ga daar staan en speel jouw wedstrijd.",
        'prematch:fireup': "Dit is jouw avond. Ga naar buiten en pak hem — laat daar niets liggen.",
        'prematch:bonus': "Ik zeg je dit: win deze, en er is iets extra's voor je.",
        'bonus:small': "Win vanavond en er ligt een cadeau voor je. Mijn woord erop.",
        'bonus:medium': "Win deze en ik zorg goed voor je — dat is een belofte.",
        'bonus:large': "Haal hem binnen en ik zorg dat het echt de moeite waard is. Mijn woord erop.",
        'postwin:toast': "Kom hier — die was speciaal. Laten we hiervan genieten.",
        'postwin:quiet': "Prachtig werk. Ik laat je weer naar de jongens gaan.",
        'postwin:tab': "Vanavond betaal ik alles. Je hebt het meer dan verdiend.",
        'postloss:sit': "Kom even bij me zitten. Nu doet het pijn — dat duurt niet lang.",
        'postloss:space': "Ik laat je met rust. Kop omhoog. We beginnen opnieuw.",
        'postloss:speech': "Luister naar me. Eén wedstrijd bepaalt niet wie je bent. Waag het niet dat te vergeten.",
        'farewell:career': "Wat een carrière was het. Je mag trots zijn op elke minuut.",
        'farewell:personal': "Vergeet het voetbal even — ik ben simpelweg blij dat ik je heb gekend.",
        'checkin:q-life': "Zeg, hoe gaat het buiten het veld? Alles goed thuis?",
        'checkin:q-club': "Hoe bevalt het bij de club? Kun je met iedereen opschieten?",
        'checkin:q-ambition': "Waar wil je hiermee naartoe? Waar gaan we echt voor?",
        'checkin:q-room': "Met wie trek je op in de kleedkamer de laatste tijd?",
        'checkin:q-none': "Geen bijbedoelingen vandaag. Ik wilde alleen weten hoe het met je gaat.",
        'moment:praise': "Dat was een mooi moment. Geniet ervan — je hebt het verdiend.",
        'moment:modest': "Stil briljant, die. Goed gedaan.",
        'injury:there': "Ik kom langs. Je gaat hier niet alleen door.",
        'injury:flowers': "Ik stuur je iets — alleen zodat je weet dat ik aan je denk.",
        'thanks:cherish': "Dit betekent veel voor me. Ik ga het bewaren, echt.",
        'thanks:banter': "Dat had je niet hoeven doen, sentimenteel als je bent. Maar bedankt, echt.",
        'invite:attend': "Dat zou ik voor geen goud missen. Ik ben er, op de tribune.",
        'invite:gift': "Ik kan er niet persoonlijk bij zijn, maar laat me iets sturen om de dag te vieren.",
        'invite:decline': "Deze keer kan ik er niet bij zijn — maar ik denk aan je, dat weet je.",
    },

    // --- choice buttons (keyed "scene|choice") ---
    choices: {
        'complaint|listen': { label: "Naar hem luisteren", hint: "Veilig. Hij wil gehoord worden." },
        'complaint|promise': { label: "Hem iets beloven", hint: "Opent een belofte met een echte deadline." },
        'complaint|pushback': { label: "Hem tegenspreken", hint: "Zeggen dat hij het mis heeft. Riskant, hangt van de man af." },
        'complaint|deflect': { label: "Het afzwakken", hint: "Wint tijd. Kan hij je nadragen." },
        'gift|praise': { label: "Je hebt het verdiend" },
        'gift|modest': { label: "Kop naar beneden en spelen" },
        'prematch|calm': { label: "Hem kalmeren", hint: "De zenuwen sussen voor de belangrijkste wedstrijd van zijn jaar." },
        'prematch|fireup': { label: "Hem opjutten", hint: "Zijn bloed laten koken." },
        'prematch|bonus': { label: "Een winstpremie beloven", hint: "Kies een cadeau dat hij krijgt als ze de beker pakken. Kost niets als ze verliezen." },
        'postwin|toast': { label: "Hem voor iedereen prijzen", hint: "Publieke lof. Sommigen vinden het mooi, anderen schamen zich." },
        'postwin|quiet': { label: "Even onder vier ogen", hint: "Alleen jullie twee, weg van het lawaai." },
        'postwin|tab': { label: "Vanavond betaal jij", hint: "Kost je geld, betekent veel." },
        'postloss|sit': { label: "Bij hem blijven", hint: "Niets zeggen. Alleen blijven." },
        'postloss|space': { label: "Hem ruimte geven", hint: "Sommige wonden genezen vanzelf." },
        'postloss|speech': { label: "Volgend seizoen beginnen we opnieuw", hint: "Rechtstreeks naar wat er komt." },
        'farewell|career': { label: "Op een geweldige carrière" },
        'farewell|personal': { label: "Op de man, niet alleen de speler" },
        'checkin|q-life': { label: "Vragen naar zijn leven buiten het voetbal" },
        'checkin|q-club': { label: "Vragen naar zijn clubliefde" },
        'checkin|q-ambition': { label: "Vragen naar zijn ambities" },
        'checkin|q-room': { label: "Vragen naar de kleedkamer" },
        'checkin|q-none': { label: "Niets in het bijzonder", hint: "Soms zegt dat het meest." },
        'moment|praise': { label: "Met hem vieren" },
        'moment|modest': { label: "Zonder ophef" },
        'injury|there': { label: "Bij hem op bezoek gaan" },
        'injury|flowers': { label: "Bloemen sturen" },
        'thanks|cherish': { label: "Ik ga het koesteren" },
        'thanks|banter': { label: "Het was tijd dat je iets terugdeed" },
        'invite|attend': { label: "Je agenda leegmaken, je gaat", hint: "Een weekend van je tijd. Telt meer dan welk cadeau ook." },
        'invite|gift': { label: "Een royaal cadeau sturen", hint: "Je kunt er niet heen, maar de gedachte komt aan." },
        'invite|decline': { label: "Netjes afzeggen", hint: "Hij gaat het merken." },
    },

    // --- discovered "vocabulary": hobbies, keepsakes and occasions, keyed by the English value ---
    // Stored on the player in English, so they are localised at fill() time. Dutch hobbies need no
    // article in either of the two lines that use them ("Ik zit helemaal in {hobby}" / "Ik maak tijd
    // voor {hobby}"), so they stay bare and the terse UI label "passie: {hobby}" reads correctly too.
    vocab: {
        'golf': "golf",
        'fishing': "vissen",
        'gaming': "gamen",
        'chess': "schaken",
        'cooking': "koken",
        'classic cars': "klassieke auto's",
        'photography': "fotografie",
        'making music': "muziek maken",
        'padel': "padel",
        'poker': "poker",
        'a signed shirt from his debut': "een gesigneerd shirt van zijn debuut",
        'a watch with a date engraved on the back': "een horloge met een datum in de achterkant gegraveerd",
        'a framed photo of the two of you at his first signing': "een ingelijste foto van jullie twee bij zijn eerste contract",
        'the match ball from his best game, signed by the whole squad': "de wedstrijdbal van zijn beste wedstrijd, gesigneerd door de hele selectie",
        'a bottle from a vineyard he part-owns': "een fles van een wijngaard waarvan hij mede-eigenaar is",
        'my wedding': "mijn bruiloft",
        "the little one's christening": "de doop van de kleine",
        'a gift': "een cadeau",
    },

    // --- ambitions: a pronoun-free infinitive phrase, so it reads both as a page label and inside a
    // spoken line ("ik wil {ambition}", "Precies wat ik wilde: {ambition}"). Dutch puts the
    // infinitive last, so no "ooit" lives in the phrase itself — the lines that want it supply it,
    // and no Dutch line wraps the phrase in an "om ... te" frame, which a placeholder cannot satisfy.
    amb: {
        types: {
            league: "in {league} spelen",
            dreamclub: "voor {club} spelen",
            boyhood: "eindigen waar het begon, bij {fav}",
            title: "een landstitel winnen",
            cup: "een beker pakken",
            europe: "in Europa spelen",
            goals: "{target} carrièregoals halen",
            topflight: "in een van de vijf grote competities spelen",
            abroad: "in het buitenland spelen",
        },
        dflt: "helemaal bovenaan komen",
        favFallback: "de club van mijn jeugd",
        leagueFallback: "een hogere competitie",
        clubFallback: "een grote club",
    },

    // --- milestone labels, frozen into the line when the moment is queued (the player is speaking) ---
    mile: {
        apps: "{n} wedstrijden",
        goals: "{n} goals in mijn carrière",
    },

    // --- the cash thank-you gift, filled into {thing} ---
    envelope: "een envelop. Daarin: €{amt} voor het bureau",
};
if (typeof module !== 'undefined' && module.exports) module.exports = { DIALOGUE_NL };
