// GENERATED by scripts/parse-dialogue-xlsx.mjs from dialogue_lines.xlsx. Do not edit by hand:
// edit the workbook, then re-run the parser. See the workbook's "Read me" sheet for the format.
const DIALOGUE_DATA = {
 "complaint": [
  {
   "id": "C001",
   "beat": "open",
   "dim": "time",
   "stage": "1",
   "choice": "",
   "outcome": "",
   "personality": "any",
   "text": "Boss, I need minutes. I train well all week, then Saturday comes and I'm watching from the bench."
  },
  {
   "id": "C002",
   "beat": "open",
   "dim": "time",
   "stage": "1",
   "choice": "",
   "outcome": "",
   "personality": "any",
   "text": "Can we talk? I didn't come to {club} to sit on a bench. Something has to change."
  },
  {
   "id": "C003",
   "beat": "open",
   "dim": "time",
   "stage": "1",
   "choice": "",
   "outcome": "",
   "personality": "any",
   "text": "I'm not asking for miracles, {agent}. I'm asking for a fair shot at the eleven."
  },
  {
   "id": "C004",
   "beat": "open",
   "dim": "time",
   "stage": "1",
   "choice": "",
   "outcome": "",
   "personality": "hothead",
   "text": "I'm done watching from the sidelines, {agent}. If the gaffer won't play me, find me someone who will!"
  },
  {
   "id": "C005",
   "beat": "open",
   "dim": "time",
   "stage": "1",
   "choice": "",
   "outcome": "",
   "personality": "professional",
   "text": "Look at my training numbers, then look at who starts ahead of me. It doesn't add up, and I want your read on it."
  },
  {
   "id": "C006",
   "beat": "open",
   "dim": "time",
   "stage": "1",
   "choice": "",
   "outcome": "",
   "personality": "showman",
   "text": "People keep asking why I'm not playing. I don't have an answer. That's a problem for both of us."
  },
  {
   "id": "C007",
   "beat": "open",
   "dim": "club",
   "stage": "1",
   "choice": "",
   "outcome": "",
   "personality": "any",
   "text": "Between us, I don't see {club} going anywhere. I need to know you have a plan for me."
  },
  {
   "id": "C008",
   "beat": "open",
   "dim": "club",
   "stage": "1",
   "choice": "",
   "outcome": "",
   "personality": "any",
   "text": "This isn't the project they sold me, {agent}. The dressing room feels flat."
  },
  {
   "id": "C009",
   "beat": "open",
   "dim": "club",
   "stage": "1",
   "choice": "",
   "outcome": "",
   "personality": "any",
   "text": "I've given this club everything and I'm not sure it's mutual anymore."
  },
  {
   "id": "C010",
   "beat": "open",
   "dim": "club",
   "stage": "1",
   "choice": "",
   "outcome": "",
   "personality": "loyal",
   "text": "I never thought I'd say this, but the club has changed. It's not the place I signed for."
  },
  {
   "id": "C011",
   "beat": "open",
   "dim": "club",
   "stage": "1",
   "choice": "",
   "outcome": "",
   "personality": "adventurer",
   "text": "I've seen everything there is to see here. I need a new challenge before I go stale."
  },
  {
   "id": "C012",
   "beat": "open",
   "dim": "club",
   "stage": "1",
   "choice": "",
   "outcome": "",
   "personality": "homebody",
   "text": "Something feels off at the club lately. I don't want drama, I just want it fixed."
  },
  {
   "id": "C013",
   "beat": "open",
   "dim": "wage",
   "stage": "1",
   "choice": "",
   "outcome": "",
   "personality": "any",
   "text": "Have you seen what the new signing is on? I'm outperforming him for half the money."
  },
  {
   "id": "C014",
   "beat": "open",
   "dim": "wage",
   "stage": "1",
   "choice": "",
   "outcome": "",
   "personality": "any",
   "text": "My deal doesn't match what I bring anymore. When are we fixing that?"
  },
  {
   "id": "C015",
   "beat": "open",
   "dim": "wage",
   "stage": "1",
   "choice": "",
   "outcome": "",
   "personality": "any",
   "text": "I don't like talking money, {agent}, but somebody has to. My wage is behind the dressing room."
  },
  {
   "id": "C016",
   "beat": "open",
   "dim": "wage",
   "stage": "1",
   "choice": "",
   "outcome": "",
   "personality": "mercenary",
   "text": "Numbers don't lie, {agent}. Mine are up and my wage isn't. Sort it."
  },
  {
   "id": "C017",
   "beat": "open",
   "dim": "wage",
   "stage": "1",
   "choice": "",
   "outcome": "",
   "personality": "humble",
   "text": "I feel awkward even raising this, but the lads say I'm underpaid. Are they right?"
  },
  {
   "id": "C018",
   "beat": "open",
   "dim": "wage",
   "stage": "1",
   "choice": "",
   "outcome": "",
   "personality": "showman",
   "text": "A player of my profile on this wage? It looks bad. It IS bad."
  },
  {
   "id": "C019",
   "beat": "open",
   "dim": "agent",
   "stage": "1",
   "choice": "",
   "outcome": "",
   "personality": "any",
   "text": "Honestly? I don't hear from you unless something's on fire. That's not what I signed up for."
  },
  {
   "id": "C020",
   "beat": "open",
   "dim": "agent",
   "stage": "1",
   "choice": "",
   "outcome": "",
   "personality": "any",
   "text": "I need to know you're still in my corner, {agent}. Lately I've had my doubts."
  },
  {
   "id": "C021",
   "beat": "open",
   "dim": "agent",
   "stage": "1",
   "choice": "",
   "outcome": "",
   "personality": "hothead",
   "text": "Where have you been?! Other agents call their players every week. I get silence."
  },
  {
   "id": "C022",
   "beat": "open",
   "dim": "agent",
   "stage": "1",
   "choice": "",
   "outcome": "",
   "personality": "loyal",
   "text": "I've stuck with you a long time, {agent}. Just tell me that still means something."
  },
  {
   "id": "C023",
   "beat": "open",
   "dim": "time",
   "stage": "2",
   "choice": "",
   "outcome": "",
   "personality": "any",
   "text": "We're past talking, {agent}. Get me playing or get me out. Those are the options."
  },
  {
   "id": "C024",
   "beat": "open",
   "dim": "time",
   "stage": "2",
   "choice": "",
   "outcome": "",
   "personality": "any",
   "text": "Every week on that bench costs me. I want a solution now, not another chat."
  },
  {
   "id": "C025",
   "beat": "open",
   "dim": "time",
   "stage": "2",
   "choice": "",
   "outcome": "",
   "personality": "hothead",
   "text": "Enough! I'll hand in a transfer request myself if that's what it takes to play football."
  },
  {
   "id": "C026",
   "beat": "open",
   "dim": "club",
   "stage": "2",
   "choice": "",
   "outcome": "",
   "personality": "any",
   "text": "I'm serious now. Start looking for a way out, or I'll make it public that I want one."
  },
  {
   "id": "C027",
   "beat": "open",
   "dim": "club",
   "stage": "2",
   "choice": "",
   "outcome": "",
   "personality": "any",
   "text": "My mind is made up about this place. What I need from you is a plan, this week."
  },
  {
   "id": "C028",
   "beat": "open",
   "dim": "wage",
   "stage": "2",
   "choice": "",
   "outcome": "",
   "personality": "any",
   "text": "Last time we talked, nothing happened. Get me a proper deal or I'll find someone who can."
  },
  {
   "id": "C029",
   "beat": "open",
   "dim": "wage",
   "stage": "2",
   "choice": "",
   "outcome": "",
   "personality": "mercenary",
   "text": "You had your chance to fix my contract quietly. Now it gets loud."
  },
  {
   "id": "C030",
   "beat": "open",
   "dim": "agent",
   "stage": "2",
   "choice": "",
   "outcome": "",
   "personality": "any",
   "text": "I've been talking to other agencies, {agent}. Give me one good reason to stay."
  },
  {
   "id": "C031",
   "beat": "open",
   "dim": "agent",
   "stage": "2",
   "choice": "",
   "outcome": "",
   "personality": "any",
   "text": "This is your last warning as far as I'm concerned. Show me you still care about my career."
  },
  {
   "id": "C032",
   "beat": "reply",
   "dim": "any",
   "stage": "any",
   "choice": "listen",
   "outcome": "good",
   "personality": "any",
   "text": "Thanks for hearing me out. It helps more than you think."
  },
  {
   "id": "C033",
   "beat": "reply",
   "dim": "any",
   "stage": "any",
   "choice": "listen",
   "outcome": "good",
   "personality": "any",
   "text": "Okay. I feel better having said it. Let's see how the next weeks go."
  },
  {
   "id": "C034",
   "beat": "reply",
   "dim": "any",
   "stage": "any",
   "choice": "listen",
   "outcome": "good",
   "personality": "any",
   "text": "You always did know when to just listen. Appreciate it, {agent}."
  },
  {
   "id": "C035",
   "beat": "reply",
   "dim": "any",
   "stage": "any",
   "choice": "listen",
   "outcome": "good",
   "personality": "humble",
   "text": "Sorry for unloading on you like that. But yes, thank you."
  },
  {
   "id": "C036",
   "beat": "reply",
   "dim": "any",
   "stage": "any",
   "choice": "listen",
   "outcome": "good",
   "personality": "hothead",
   "text": "Fine. I've said my piece. Just don't forget it."
  },
  {
   "id": "C037",
   "beat": "reply",
   "dim": "any",
   "stage": "any",
   "choice": "promise",
   "outcome": "good",
   "personality": "any",
   "text": "Alright. I'll hold you to that, {agent}."
  },
  {
   "id": "C038",
   "beat": "reply",
   "dim": "any",
   "stage": "any",
   "choice": "promise",
   "outcome": "good",
   "personality": "any",
   "text": "That's what I needed to hear. Don't let me down."
  },
  {
   "id": "C039",
   "beat": "reply",
   "dim": "any",
   "stage": "any",
   "choice": "promise",
   "outcome": "good",
   "personality": "any",
   "text": "Deal. You've never left me hanging before, so I'll trust it."
  },
  {
   "id": "C040",
   "beat": "reply",
   "dim": "any",
   "stage": "any",
   "choice": "promise",
   "outcome": "good",
   "personality": "mercenary",
   "text": "Good. Put it in writing if you have to. I'll be counting the weeks."
  },
  {
   "id": "C041",
   "beat": "reply",
   "dim": "any",
   "stage": "any",
   "choice": "promise",
   "outcome": "good",
   "personality": "loyal",
   "text": "Your word has always been enough for me. Don't make me regret that."
  },
  {
   "id": "C042",
   "beat": "reply",
   "dim": "any",
   "stage": "any",
   "choice": "pushback",
   "outcome": "good",
   "personality": "any",
   "text": "Huh. I didn't expect that answer. But maybe you're right."
  },
  {
   "id": "C043",
   "beat": "reply",
   "dim": "any",
   "stage": "any",
   "choice": "pushback",
   "outcome": "good",
   "personality": "any",
   "text": "That's hard to hear, but it's honest. Okay. I'll get my head down."
  },
  {
   "id": "C044",
   "beat": "reply",
   "dim": "any",
   "stage": "any",
   "choice": "pushback",
   "outcome": "good",
   "personality": "professional",
   "text": "That's a fair analysis. I can work with that. Thanks for being straight with me."
  },
  {
   "id": "C045",
   "beat": "reply",
   "dim": "any",
   "stage": "any",
   "choice": "pushback",
   "outcome": "good",
   "personality": "professional",
   "text": "You're right about the numbers. I'll focus on what I can control."
  },
  {
   "id": "C046",
   "beat": "reply",
   "dim": "any",
   "stage": "any",
   "choice": "pushback",
   "outcome": "bad",
   "personality": "any",
   "text": "Seriously? I come to you with a problem and you tell me I'M the problem?"
  },
  {
   "id": "C047",
   "beat": "reply",
   "dim": "any",
   "stage": "any",
   "choice": "pushback",
   "outcome": "bad",
   "personality": "any",
   "text": "Wow. Good to know where you stand. This conversation is over."
  },
  {
   "id": "C048",
   "beat": "reply",
   "dim": "any",
   "stage": "any",
   "choice": "pushback",
   "outcome": "bad",
   "personality": "hothead",
   "text": "You've got some nerve! Whose side are you even on?!"
  },
  {
   "id": "C049",
   "beat": "reply",
   "dim": "any",
   "stage": "any",
   "choice": "pushback",
   "outcome": "bad",
   "personality": "hothead",
   "text": "No. NO. You don't get to lecture me. Fix it or I find someone who will."
  },
  {
   "id": "C050",
   "beat": "reply",
   "dim": "any",
   "stage": "any",
   "choice": "deflect",
   "outcome": "bad",
   "personality": "any",
   "text": "Right. 'It'll sort itself out.' I've heard that one before."
  },
  {
   "id": "C051",
   "beat": "reply",
   "dim": "any",
   "stage": "any",
   "choice": "deflect",
   "outcome": "bad",
   "personality": "any",
   "text": "Sure, we'll see. But I won't wait forever, {agent}."
  },
  {
   "id": "C052",
   "beat": "reply",
   "dim": "any",
   "stage": "any",
   "choice": "deflect",
   "outcome": "bad",
   "personality": "any",
   "text": "Hm. That's not really an answer, is it."
  }
 ],
 "gifts": [
  {
   "id": "G001",
   "beat": "react",
   "tier": "small",
   "mood": "fresh",
   "choice": "",
   "personality": "any",
   "text": "Ah, nice one. Small things count too. Cheers, {agent}."
  },
  {
   "id": "G002",
   "beat": "react",
   "tier": "small",
   "mood": "fresh",
   "choice": "",
   "personality": "any",
   "text": "You remembered! Thanks, that's a lovely touch."
  },
  {
   "id": "G003",
   "beat": "react",
   "tier": "small",
   "mood": "fresh",
   "choice": "",
   "personality": "humble",
   "text": "You didn't have to do that. But thank you, really."
  },
  {
   "id": "G004",
   "beat": "react",
   "tier": "small",
   "mood": "fresh",
   "choice": "",
   "personality": "mercenary",
   "text": "Cute. The thought counts, I suppose."
  },
  {
   "id": "G005",
   "beat": "react",
   "tier": "medium",
   "mood": "fresh",
   "choice": "",
   "personality": "any",
   "text": "Now that's a proper gift. Thank you, seriously."
  },
  {
   "id": "G006",
   "beat": "react",
   "tier": "medium",
   "mood": "fresh",
   "choice": "",
   "personality": "any",
   "text": "Okay, you've got taste. I'll give you that."
  },
  {
   "id": "G007",
   "beat": "react",
   "tier": "medium",
   "mood": "fresh",
   "choice": "",
   "personality": "showman",
   "text": "This is class. Wait till the lads see it."
  },
  {
   "id": "G008",
   "beat": "react",
   "tier": "medium",
   "mood": "fresh",
   "choice": "",
   "personality": "homebody",
   "text": "That's really thoughtful. It'll get a good spot at home."
  },
  {
   "id": "G009",
   "beat": "react",
   "tier": "large",
   "mood": "fresh",
   "choice": "",
   "personality": "any",
   "text": "This is... wow. You really didn't have to. Thank you, {agent}."
  },
  {
   "id": "G010",
   "beat": "react",
   "tier": "large",
   "mood": "fresh",
   "choice": "",
   "personality": "any",
   "text": "Unbelievable. I don't know what to say. Thank you."
  },
  {
   "id": "G011",
   "beat": "react",
   "tier": "large",
   "mood": "fresh",
   "choice": "",
   "personality": "showman",
   "text": "THIS is how you treat a star. I love it!"
  },
  {
   "id": "G012",
   "beat": "react",
   "tier": "large",
   "mood": "fresh",
   "choice": "",
   "personality": "humble",
   "text": "It's too much, {agent}. Honestly. But I'll treasure it."
  },
  {
   "id": "G013",
   "beat": "react",
   "tier": "large",
   "mood": "fresh",
   "choice": "",
   "personality": "loyal",
   "text": "After all these years you still surprise me. Thank you."
  },
  {
   "id": "G014",
   "beat": "react",
   "tier": "any",
   "mood": "diminished",
   "choice": "",
   "personality": "any",
   "text": "Another one already? Thanks, I guess."
  },
  {
   "id": "G015",
   "beat": "react",
   "tier": "any",
   "mood": "diminished",
   "choice": "",
   "personality": "any",
   "text": "You're spoiling me lately. It loses a bit of shine, you know."
  },
  {
   "id": "G016",
   "beat": "react",
   "tier": "any",
   "mood": "diminished",
   "choice": "",
   "personality": "mercenary",
   "text": "Two gifts this close together? Now I'm wondering what the bad news is."
  },
  {
   "id": "G017",
   "beat": "close",
   "tier": "any",
   "mood": "any",
   "choice": "praise",
   "personality": "any",
   "text": "Ha! I'll take that."
  },
  {
   "id": "G018",
   "beat": "close",
   "tier": "any",
   "mood": "any",
   "choice": "praise",
   "personality": "showman",
   "text": "Say that louder next time, there's press around."
  },
  {
   "id": "G019",
   "beat": "close",
   "tier": "any",
   "mood": "any",
   "choice": "praise",
   "personality": "humble",
   "text": "I just do my job. But thanks."
  },
  {
   "id": "G020",
   "beat": "close",
   "tier": "any",
   "mood": "any",
   "choice": "modest",
   "personality": "any",
   "text": "Understood. Back to work."
  },
  {
   "id": "G021",
   "beat": "close",
   "tier": "any",
   "mood": "any",
   "choice": "modest",
   "personality": "professional",
   "text": "Exactly my plan."
  },
  {
   "id": "G022",
   "beat": "close",
   "tier": "any",
   "mood": "any",
   "choice": "modest",
   "personality": "showman",
   "text": "You're no fun. But fine."
  }
 ],
 "final": [
  {
   "id": "F001",
   "beat": "pre-open",
   "choice": "",
   "outcome": "any",
   "personality": "any",
   "text": "Big one today, {agent}. The dressing room is buzzing. Glad you came."
  },
  {
   "id": "F002",
   "beat": "pre-open",
   "choice": "",
   "outcome": "any",
   "personality": "any",
   "text": "So this is it. Ninety minutes from a medal."
  },
  {
   "id": "F003",
   "beat": "pre-open",
   "choice": "",
   "outcome": "any",
   "personality": "any",
   "text": "Never played a final with my agent in the stands before. No pressure then."
  },
  {
   "id": "F004",
   "beat": "pre-open",
   "choice": "",
   "outcome": "any",
   "personality": "hothead",
   "text": "I can't sit still, {agent}. I want to run through that wall RIGHT now."
  },
  {
   "id": "F005",
   "beat": "pre-open",
   "choice": "",
   "outcome": "any",
   "personality": "professional",
   "text": "I've done my homework on {opponent}. Set pieces will decide it, watch."
  },
  {
   "id": "F006",
   "beat": "pre-open",
   "choice": "",
   "outcome": "any",
   "personality": "showman",
   "text": "Finals are my stage, {agent}. Today they all find out."
  },
  {
   "id": "F007",
   "beat": "pre-open",
   "choice": "",
   "outcome": "any",
   "personality": "humble",
   "text": "Whatever happens out there, thanks for coming. It means a lot."
  },
  {
   "id": "F008",
   "beat": "pre-open",
   "choice": "",
   "outcome": "any",
   "personality": "homebody",
   "text": "Everyone I know is in the stands today. I just don't want to let them down."
  },
  {
   "id": "F009",
   "beat": "pre-open",
   "choice": "",
   "outcome": "any",
   "personality": "adventurer",
   "text": "This is why I play football. Days like this."
  },
  {
   "id": "F010",
   "beat": "pre-open",
   "choice": "",
   "outcome": "any",
   "personality": "loyal",
   "text": "Winning this with THIS club would mean everything to me."
  },
  {
   "id": "F011",
   "beat": "pre-open",
   "choice": "",
   "outcome": "any",
   "personality": "mercenary",
   "text": "Win bonus in my contract, cup medal on the shelf. Let's have both."
  },
  {
   "id": "F012",
   "beat": "pre-reply",
   "choice": "calm",
   "outcome": "good",
   "personality": "any",
   "text": "Yeah. Yeah, you're right. Deep breath. I'm good."
  },
  {
   "id": "F013",
   "beat": "pre-reply",
   "choice": "calm",
   "outcome": "good",
   "personality": "hothead",
   "text": "Okay. Okay. Head clear, feet loose. Thanks, {agent}."
  },
  {
   "id": "F014",
   "beat": "pre-reply",
   "choice": "calm",
   "outcome": "good",
   "personality": "professional",
   "text": "Agreed. Process over emotion. See you after."
  },
  {
   "id": "F015",
   "beat": "pre-reply",
   "choice": "calm",
   "outcome": "bad",
   "personality": "any",
   "text": "Calm? I'm fine, {agent}. Save the speech."
  },
  {
   "id": "F016",
   "beat": "pre-reply",
   "choice": "calm",
   "outcome": "bad",
   "personality": "showman",
   "text": "Calm is for the bench. I'm built for this."
  },
  {
   "id": "F017",
   "beat": "pre-reply",
   "choice": "fireup",
   "outcome": "good",
   "personality": "any",
   "text": "YES. That's what I wanted to hear!"
  },
  {
   "id": "F018",
   "beat": "pre-reply",
   "choice": "fireup",
   "outcome": "good",
   "personality": "showman",
   "text": "Watch me out there. First goal's for you."
  },
  {
   "id": "F019",
   "beat": "pre-reply",
   "choice": "fireup",
   "outcome": "bad",
   "personality": "any",
   "text": "Easy, easy. I need a clear head, not a war cry."
  },
  {
   "id": "F020",
   "beat": "pre-reply",
   "choice": "fireup",
   "outcome": "bad",
   "personality": "professional",
   "text": "I appreciate it, but I prepare my own way."
  },
  {
   "id": "F021",
   "beat": "pre-reply",
   "choice": "bonus",
   "outcome": "any",
   "personality": "any",
   "text": "Ha! Now THAT's motivation. Deal."
  },
  {
   "id": "F022",
   "beat": "pre-reply",
   "choice": "bonus",
   "outcome": "any",
   "personality": "mercenary",
   "text": "Now you're speaking my language. Consider it won."
  },
  {
   "id": "F023",
   "beat": "pre-reply",
   "choice": "bonus",
   "outcome": "any",
   "personality": "humble",
   "text": "You don't need to bribe me, {agent}. But alright, deal."
  },
  {
   "id": "F024",
   "beat": "win-open",
   "choice": "",
   "outcome": "any",
   "personality": "any",
   "text": "WE DID IT! Can you believe it?! Get in here, {agent}!"
  },
  {
   "id": "F025",
   "beat": "win-open",
   "choice": "",
   "outcome": "any",
   "personality": "any",
   "text": "Champions! I've dreamed of this since I was a kid!"
  },
  {
   "id": "F026",
   "beat": "win-open",
   "choice": "",
   "outcome": "any",
   "personality": "showman",
   "text": "Did you SEE that?! They'll be talking about this for years!"
  },
  {
   "id": "F027",
   "beat": "win-open",
   "choice": "",
   "outcome": "any",
   "personality": "humble",
   "text": "We actually did it. The whole team was incredible."
  },
  {
   "id": "F028",
   "beat": "win-open",
   "choice": "",
   "outcome": "any",
   "personality": "loyal",
   "text": "For this club. For everyone in those stands. I'm so proud, {agent}."
  },
  {
   "id": "F029",
   "beat": "win-open",
   "choice": "",
   "outcome": "any",
   "personality": "hothead",
   "text": "YEEES! Nobody believed in us! NOBODY!"
  },
  {
   "id": "F030",
   "beat": "win-reply",
   "choice": "toast",
   "outcome": "good",
   "personality": "any",
   "text": "Louder, {agent}! Tonight we celebrate!"
  },
  {
   "id": "F031",
   "beat": "win-reply",
   "choice": "toast",
   "outcome": "good",
   "personality": "showman",
   "text": "Say it again for the cameras!"
  },
  {
   "id": "F032",
   "beat": "win-reply",
   "choice": "toast",
   "outcome": "bad",
   "personality": "any",
   "text": "Ha, thanks. Bit much in front of everyone, but thanks."
  },
  {
   "id": "F033",
   "beat": "win-reply",
   "choice": "toast",
   "outcome": "bad",
   "personality": "humble",
   "text": "Please sit down, you're embarrassing me. But thank you."
  },
  {
   "id": "F034",
   "beat": "win-reply",
   "choice": "quiet",
   "outcome": "good",
   "personality": "any",
   "text": "That means more than any headline. Thank you."
  },
  {
   "id": "F035",
   "beat": "win-reply",
   "choice": "quiet",
   "outcome": "good",
   "personality": "professional",
   "text": "Appreciated. Quietly is exactly how I like it."
  },
  {
   "id": "F036",
   "beat": "win-reply",
   "choice": "quiet",
   "outcome": "bad",
   "personality": "any",
   "text": "A quiet word? Tonight? Come on, live a little!"
  },
  {
   "id": "F037",
   "beat": "win-reply",
   "choice": "tab",
   "outcome": "good",
   "personality": "any",
   "text": "Drinks on the agent! Now THAT'S service!"
  },
  {
   "id": "F038",
   "beat": "win-reply",
   "choice": "tab",
   "outcome": "good",
   "personality": "mercenary",
   "text": "Generous AND smart. The lads will remember this."
  },
  {
   "id": "F039",
   "beat": "loss-open",
   "choice": "",
   "outcome": "any",
   "personality": "any",
   "text": "So close. So, so close. I don't know what to say, {agent}."
  },
  {
   "id": "F040",
   "beat": "loss-open",
   "choice": "",
   "outcome": "any",
   "personality": "any",
   "text": "That one's going to hurt for a long time."
  },
  {
   "id": "F041",
   "beat": "loss-open",
   "choice": "",
   "outcome": "any",
   "personality": "hothead",
   "text": "Don't. Just... don't say anything yet."
  },
  {
   "id": "F042",
   "beat": "loss-open",
   "choice": "",
   "outcome": "any",
   "personality": "humble",
   "text": "Sorry. I felt like I let everyone down out there."
  },
  {
   "id": "F043",
   "beat": "loss-open",
   "choice": "",
   "outcome": "any",
   "personality": "loyal",
   "text": "The fans deserved better today. That's what kills me."
  },
  {
   "id": "F044",
   "beat": "loss-reply",
   "choice": "sit",
   "outcome": "good",
   "personality": "any",
   "text": "Thanks for staying. Most people just leave you alone with it."
  },
  {
   "id": "F045",
   "beat": "loss-reply",
   "choice": "sit",
   "outcome": "good",
   "personality": "humble",
   "text": "I'm glad you're here. Really."
  },
  {
   "id": "F046",
   "beat": "loss-reply",
   "choice": "sit",
   "outcome": "bad",
   "personality": "any",
   "text": "I appreciate it, but I kind of want to be alone right now."
  },
  {
   "id": "F047",
   "beat": "loss-reply",
   "choice": "space",
   "outcome": "good",
   "personality": "any",
   "text": "Yeah. I'll call you in a couple of days. Thanks for understanding."
  },
  {
   "id": "F048",
   "beat": "loss-reply",
   "choice": "space",
   "outcome": "good",
   "personality": "hothead",
   "text": "Good call. I'm not fit for company tonight."
  },
  {
   "id": "F049",
   "beat": "loss-reply",
   "choice": "space",
   "outcome": "bad",
   "personality": "any",
   "text": "Right. Everyone always leaves after a loss. Noted."
  },
  {
   "id": "F050",
   "beat": "loss-reply",
   "choice": "speech",
   "outcome": "good",
   "personality": "any",
   "text": "You're right. Next season starts tomorrow. We go again."
  },
  {
   "id": "F051",
   "beat": "loss-reply",
   "choice": "speech",
   "outcome": "good",
   "personality": "professional",
   "text": "Correct. Losses are data. We'll be better for it."
  },
  {
   "id": "F052",
   "beat": "loss-reply",
   "choice": "speech",
   "outcome": "bad",
   "personality": "any",
   "text": "Next season? We JUST lost, {agent}. Read the room."
  },
  {
   "id": "F090",
   "beat": "titlemiss-open",
   "choice": "",
   "outcome": "any",
   "personality": "any",
   "text": "We did everything right today, {agent}. It just wasn't enough — the title's gone on the other result."
  },
  {
   "id": "F091",
   "beat": "titlemiss-open",
   "choice": "",
   "outcome": "any",
   "personality": "any",
   "text": "We won and it still slipped away. So close. I can't believe it's over."
  },
  {
   "id": "F092",
   "beat": "titlemiss-open",
   "choice": "",
   "outcome": "any",
   "personality": "any",
   "text": "Our part's done — we did our job. It's the game we couldn't control that killed us."
  }
 ],
 "farewell": [
  {
   "id": "W001",
   "beat": "open",
   "tier": "business",
   "choice": "",
   "personality": "any",
   "text": "Well, {agent}. That's that. Boots hung up. Thanks for the work over the years."
  },
  {
   "id": "W002",
   "beat": "open",
   "tier": "business",
   "choice": "",
   "personality": "any",
   "text": "It's official then. Retirement. We had our ups and downs, but we got the job done."
  },
  {
   "id": "W003",
   "beat": "open",
   "tier": "trusted",
   "choice": "",
   "personality": "any",
   "text": "Strange feeling, {agent}. No more matchdays. I'm glad you were along for a good part of the ride."
  },
  {
   "id": "W004",
   "beat": "open",
   "tier": "trusted",
   "choice": "",
   "personality": "any",
   "text": "So that's the last whistle. Thank you for the years, {agent}. You did right by me more often than not."
  },
  {
   "id": "W005",
   "beat": "open",
   "tier": "confidant",
   "choice": "",
   "personality": "any",
   "text": "You know, of all the people in football, you're one of the few I'll actually miss. What a ride we had."
  },
  {
   "id": "W006",
   "beat": "open",
   "tier": "confidant",
   "choice": "",
   "personality": "any",
   "text": "I keep thinking about everything we went through together. Contracts, transfers, the lot. Thank you, my friend."
  },
  {
   "id": "W007",
   "beat": "open",
   "tier": "family",
   "choice": "",
   "personality": "any",
   "text": "Before anything else: my testimonial. Front row, guest of honour. No arguments. You were family through all of it."
  },
  {
   "id": "W008",
   "beat": "open",
   "tier": "family",
   "choice": "",
   "personality": "any",
   "text": "They asked me who mattered most in my career. I said my family. Then I named you in the same breath, {agent}."
  },
  {
   "id": "W009",
   "beat": "reply",
   "tier": "any",
   "choice": "career",
   "personality": "any",
   "text": "One hell of a career is right. And I couldn't have done half of it without you."
  },
  {
   "id": "W010",
   "beat": "reply",
   "tier": "any",
   "choice": "career",
   "personality": "showman",
   "text": "They'll remember the goals. Just make sure they spell my name right in the record books."
  },
  {
   "id": "W011",
   "beat": "reply",
   "tier": "any",
   "choice": "career",
   "personality": "professional",
   "text": "It was a good body of work. We can both be satisfied with that."
  },
  {
   "id": "W012",
   "beat": "reply",
   "tier": "any",
   "choice": "personal",
   "personality": "any",
   "text": "That means more than the trophies, honestly. Thank you for everything."
  },
  {
   "id": "W013",
   "beat": "reply",
   "tier": "any",
   "choice": "personal",
   "personality": "humble",
   "text": "Stop it, you'll set me off. Thank you. For all of it."
  },
  {
   "id": "W014",
   "beat": "reply",
   "tier": "any",
   "choice": "personal",
   "personality": "loyal",
   "text": "We stuck together, didn't we. Through everything. That's rare in this game."
  },
  {
   "id": "W015",
   "beat": "reply",
   "tier": "family",
   "choice": "personal",
   "personality": "any",
   "text": "You are making me cry. I am so glad to have met you!"
  },
  {
   "id": "W016",
   "beat": "reply",
   "tier": "family",
   "choice": "career",
   "personality": "any",
   "text": "It means the world to me that you have been there through it all!"
  }
 ],
 "checkin": [
  {
   "id": "K001",
   "beat": "open",
   "choice": "",
   "variant": "any",
   "personality": "any",
   "text": "Hey {agent}! Good timing, just finished training. What's on your mind?"
  },
  {
   "id": "K002",
   "beat": "open",
   "choice": "",
   "variant": "any",
   "personality": "any",
   "text": "Well, look who it is. Everything alright, or is this business?"
  },
  {
   "id": "K003",
   "beat": "open",
   "choice": "",
   "variant": "any",
   "personality": "any",
   "text": "You called, I'm here. Coffee's on you though."
  },
  {
   "id": "K004",
   "beat": "open",
   "choice": "",
   "variant": "any",
   "personality": "hothead",
   "text": "Make it quick, I've got a gym session. Kidding. Sort of. What's up?"
  },
  {
   "id": "K005",
   "beat": "open",
   "choice": "",
   "variant": "any",
   "personality": "showman",
   "text": "Here to check on your favourite client? Smart move."
  },
  {
   "id": "K006",
   "beat": "open",
   "choice": "",
   "variant": "any",
   "personality": "humble",
   "text": "Always nice when you drop by, {agent}. Really."
  },
  {
   "id": "K007",
   "beat": "open",
   "choice": "",
   "variant": "any",
   "personality": "homebody",
   "text": "Come in, come in. It's good to see a familiar face."
  },
  {
   "id": "K008",
   "beat": "reply",
   "choice": "q-life",
   "variant": "single",
   "personality": "any",
   "text": "Family? It's just me right now, honestly. Football takes everything I've got."
  },
  {
   "id": "K009",
   "beat": "reply",
   "choice": "q-life",
   "variant": "single",
   "personality": "adventurer",
   "text": "Just me, my boots and a suitcase. Suits me fine for now."
  },
  {
   "id": "K010",
   "beat": "reply",
   "choice": "q-life",
   "variant": "partner",
   "personality": "any",
   "text": "My better half keeps me sane. Couldn't do any of this alone."
  },
  {
   "id": "K011",
   "beat": "reply",
   "choice": "q-life",
   "variant": "kids",
   "personality": "any",
   "text": "The kids are everything, {agent}. Every match I play is for them."
  },
  {
   "id": "K012",
   "beat": "reply",
   "choice": "q-life",
   "variant": "kids",
   "personality": "homebody",
   "text": "The little ones rule the house. Best thing that ever happened to me."
  },
  {
   "id": "K013",
   "beat": "reply",
   "choice": "q-life",
   "variant": "hobby",
   "personality": "any",
   "text": "Lately? I'm deep into {hobby}. Keeps my head quiet between matches."
  },
  {
   "id": "K014",
   "beat": "reply",
   "choice": "q-life",
   "variant": "hobby",
   "personality": "professional",
   "text": "I make time for {hobby}. Recovery for the mind, not just the legs."
  },
  {
   "id": "K015",
   "beat": "reply",
   "choice": "q-life",
   "variant": "nothing",
   "personality": "any",
   "text": "Same old, honestly. Training, home, repeat. I'm content."
  },
  {
   "id": "K016",
   "beat": "reply",
   "choice": "q-club",
   "variant": "any",
   "personality": "any",
   "text": "Since I was a kid? {favclub}. My dad took me to a match once and that was that."
  },
  {
   "id": "K017",
   "beat": "reply",
   "choice": "q-club",
   "variant": "any",
   "personality": "any",
   "text": "Easy. {favclub}. I had the posters, the shirts, everything."
  },
  {
   "id": "K018",
   "beat": "reply",
   "choice": "q-club",
   "variant": "any",
   "personality": "loyal",
   "text": "{favclub}, always. Some things don't change, no matter where you play."
  },
  {
   "id": "K019",
   "beat": "reply",
   "choice": "q-club",
   "variant": "any",
   "personality": "hothead",
   "text": "I love {favclub}! I can't sit still when they are playing."
  },
  {
   "id": "K020",
   "beat": "reply",
   "choice": "q-club",
   "variant": "any",
   "personality": "homebody",
   "text": "It's {favclub}. My grandma has been a season ticket holder for 52 years, and she has brought the entire family into it."
  },
  {
   "id": "K021",
   "beat": "reply",
   "choice": "q-ambition",
   "variant": "any",
   "personality": "any",
   "text": "Honestly? One day, I want to {ambition}. That's the dream."
  },
  {
   "id": "K022",
   "beat": "reply",
   "choice": "q-ambition",
   "variant": "any",
   "personality": "showman",
   "text": "Between us: I want to {ambition}. And I want everyone to see it."
  },
  {
   "id": "K023",
   "beat": "reply",
   "choice": "q-ambition",
   "variant": "any",
   "personality": "professional",
   "text": "I've set myself one target: {ambition}. Everything I do points there."
  },
  {
   "id": "K024",
   "beat": "reply",
   "choice": "q-ambition",
   "variant": "any",
   "personality": "humble",
   "text": "If I could ever {ambition}, that would be an amazing achievement for me and my mates."
  },
  {
   "id": "K025",
   "beat": "reply",
   "choice": "q-ambition",
   "variant": "any",
   "personality": "hothead",
   "text": "I need to {ambition}. And I always want to be in the race for titles!"
  },
  {
   "id": "K026",
   "beat": "reply",
   "choice": "q-ambition",
   "variant": "any",
   "personality": "homebody",
   "text": "I want to {ambition}. But most importantly, I want to have my friends and family with me at every step of the way."
  },
  {
   "id": "K027",
   "beat": "reply",
   "choice": "q-room",
   "variant": "any",
   "personality": "any",
   "text": "Dressing room's good. Few big egos, but show me one without."
  },
  {
   "id": "K028",
   "beat": "reply",
   "choice": "q-room",
   "variant": "any",
   "personality": "any",
   "text": "Honestly, great group of lads. Best I've been part of."
  },
  {
   "id": "K029",
   "beat": "reply",
   "choice": "q-room",
   "variant": "any",
   "personality": "hothead",
   "text": "There's one guy who keeps nicking my parking spot. We've had words."
  },
  {
   "id": "K030",
   "beat": "reply",
   "choice": "q-room",
   "variant": "any",
   "personality": "showman",
   "text": "Honestly, I feel like my team mates don't sufficiently appreciate my excellence..."
  },
  {
   "id": "K031",
   "beat": "reply",
   "choice": "q-room",
   "variant": "any",
   "personality": "showman",
   "text": "Ha! It's a blast most of the time, and you know I'm the DJ!"
  },
  {
   "id": "K032",
   "beat": "reply",
   "choice": "q-room",
   "variant": "any",
   "personality": "homebody",
   "text": "I feel very at home here! I see no reason to ever leave at the moment."
  },
  {
   "id": "K033",
   "beat": "reply",
   "choice": "q-room",
   "variant": "any",
   "personality": "loyal",
   "text": "I feel very at home here! I see no reason to ever leave at the moment."
  },
  {
   "id": "K034",
   "beat": "reply",
   "choice": "q-room",
   "variant": "any",
   "personality": "hothead",
   "text": "We have a bunch of two-faced snakes among us... Always talking behind the others backs."
  },
  {
   "id": "K035",
   "beat": "reply",
   "choice": "q-room",
   "variant": "any",
   "personality": "any",
   "text": "We lack a real team cohesion right now... I think the manager has assembled a squad of mercenaries."
  },
  {
   "id": "K036",
   "beat": "reply",
   "choice": "q-room",
   "variant": "any",
   "personality": "humble",
   "text": "I look around at times and am just so grateful to be part of this amazing team! Thank you for making this possible for me."
  },
  {
   "id": "K037",
   "beat": "reply",
   "choice": "q-room",
   "variant": "any",
   "personality": "any",
   "text": "I have made a lot of friend in my time at this club. I really feel blessed."
  },
  {
   "id": "K038",
   "beat": "reply",
   "choice": "q-none",
   "variant": "any",
   "personality": "any",
   "text": "Ha, just checking in? Appreciated. Genuinely."
  },
  {
   "id": "K039",
   "beat": "reply",
   "choice": "q-none",
   "variant": "any",
   "personality": "any",
   "text": "No agenda? That's a first for an agent. I like it."
  },
  {
   "id": "K040",
   "beat": "reply",
   "choice": "q-none",
   "variant": "any",
   "personality": "humble",
   "text": "That's kind of you. It gets lonely out here sometimes, you know."
  },
  {
   "id": "K041",
   "beat": "open",
   "choice": "",
   "variant": "any",
   "personality": "any",
   "text": "Good to see you, {agent}! What did you want to talk about?"
  },
  {
   "id": "K042",
   "beat": "open",
   "choice": "",
   "variant": "any",
   "personality": "any",
   "text": "Hey, how are you? I hope you don't come begging for money! Kidding, of course, what's going on?"
  },
  {
   "id": "K043",
   "beat": "open",
   "choice": "",
   "variant": "any",
   "personality": "any",
   "text": "Nice of you to reach out, what did you want to speak with me about?"
  }
 ],
 "moments": [
  {
   "id": "M001",
   "kind": "debut",
   "beat": "open",
   "choice": "",
   "personality": "any",
   "text": "First senior minutes, {agent}! Did you see? I've still got the shirt on. I'm not taking it off."
  },
  {
   "id": "M002",
   "kind": "debut",
   "beat": "open",
   "choice": "",
   "personality": "humble",
   "text": "I actually played. A real senior match. I keep waiting for someone to say it was a mistake."
  },
  {
   "id": "M003",
   "kind": "firstgoal",
   "beat": "open",
   "choice": "",
   "personality": "any",
   "text": "FIRST GOAL! Did you see it?! I must have watched the clip fifty times already."
  },
  {
   "id": "M004",
   "kind": "firstgoal",
   "beat": "open",
   "choice": "",
   "personality": "humble",
   "text": "It finally went in for me. Feels unreal, honestly."
  },
  {
   "id": "M005",
   "kind": "hattrick",
   "beat": "open",
   "choice": "",
   "personality": "any",
   "text": "THREE! A hat-trick, {agent}! They gave me the match ball and everything!"
  },
  {
   "id": "M006",
   "kind": "hattrick",
   "beat": "open",
   "choice": "",
   "personality": "showman",
   "text": "A hat-trick. Match ball's getting framed. Maybe the boots too."
  },
  {
   "id": "M007",
   "kind": "milestone",
   "beat": "open",
   "choice": "",
   "personality": "any",
   "text": "{milestone}. Just saw it in the matchday programme. Time flies, doesn't it?"
  },
  {
   "id": "M008",
   "kind": "milestone",
   "beat": "open",
   "choice": "",
   "personality": "professional",
   "text": "{milestone}. A nice number. Now for the next one."
  },
  {
   "id": "M009",
   "kind": "milestone",
   "beat": "open",
   "choice": "",
   "personality": "loyal",
   "text": "{milestone}. And you were there for most of them, {agent}."
  },
  {
   "id": "M010",
   "kind": "procontract",
   "beat": "open",
   "choice": "",
   "personality": "any",
   "text": "My first professional contract, {agent}! Signed and everything. This is real now, isn't it?"
  },
  {
   "id": "M011",
   "kind": "procontract",
   "beat": "open",
   "choice": "",
   "personality": "humble",
   "text": "I keep reading the contract over and over. Me. A professional footballer."
  },
  {
   "id": "M012",
   "kind": "transfer",
   "beat": "open",
   "choice": "",
   "personality": "any",
   "text": "It's done, {agent}. {newclub}. New chapter. Thanks for getting it over the line."
  },
  {
   "id": "M013",
   "kind": "transfer",
   "beat": "open",
   "choice": "",
   "personality": "adventurer",
   "text": "{newclub}! New city, new league, new everything. This is what I live for."
  },
  {
   "id": "M014",
   "kind": "transfer",
   "beat": "open",
   "choice": "",
   "personality": "homebody",
   "text": "{newclub} it is, then. Big change for me. I trust you that it's the right one."
  },
  {
   "id": "M015",
   "kind": "dreammove",
   "beat": "open",
   "choice": "",
   "personality": "any",
   "text": "I have to tell you something. {newclub} was MY club growing up. You just made a little kid's dream come true. I won't forget this. Ever."
  },
  {
   "id": "M016",
   "kind": "dreammove",
   "beat": "open",
   "choice": "",
   "personality": "loyal",
   "text": "You knew what {newclub} meant to me. This is the biggest thing anyone has done for my career. Thank you."
  },
  {
   "id": "M017",
   "kind": "ambition",
   "beat": "open",
   "choice": "",
   "personality": "any",
   "text": "Remember what I told you I wanted? To {ambition}? ...Done. We actually did it."
  },
  {
   "id": "M018",
   "kind": "ambition",
   "beat": "open",
   "choice": "",
   "personality": "showman",
   "text": "To {ambition}. Said it, did it. And you helped, {agent}. Credit where it's due."
  },
  {
   "id": "M019",
   "kind": "injury",
   "beat": "open",
   "choice": "",
   "personality": "any",
   "text": "They say {weeks} weeks, {agent}. I can't even look at my boots right now."
  },
  {
   "id": "M020",
   "kind": "injury",
   "beat": "open",
   "choice": "",
   "personality": "hothead",
   "text": "I KNEW that tackle was coming. {weeks} weeks. I'm furious."
  },
  {
   "id": "M021",
   "kind": "injury",
   "beat": "open",
   "choice": "",
   "personality": "professional",
   "text": "{weeks} weeks out. I've already asked for the rehab plan. Still stings, though."
  },
  {
   "id": "M022",
   "kind": "any",
   "beat": "reply",
   "choice": "praise",
   "personality": "any",
   "text": "Ha, thanks. Days like this make it all worth it."
  },
  {
   "id": "M023",
   "kind": "any",
   "beat": "reply",
   "choice": "praise",
   "personality": "showman",
   "text": "Finally someone says it like it is!"
  },
  {
   "id": "M024",
   "kind": "any",
   "beat": "reply",
   "choice": "praise",
   "personality": "humble",
   "text": "Alright, alright. One night of celebrating, then back to normal."
  },
  {
   "id": "M025",
   "kind": "any",
   "beat": "reply",
   "choice": "modest",
   "personality": "any",
   "text": "You're right. Head down, next job."
  },
  {
   "id": "M026",
   "kind": "any",
   "beat": "reply",
   "choice": "modest",
   "personality": "professional",
   "text": "Agreed. Celebrate tonight, reset tomorrow."
  },
  {
   "id": "M027",
   "kind": "any",
   "beat": "reply",
   "choice": "modest",
   "personality": "showman",
   "text": "Low key? Fine. But I'm keeping the highlights on repeat."
  },
  {
   "id": "M028",
   "kind": "injury",
   "beat": "reply",
   "choice": "there",
   "personality": "any",
   "text": "You came all the way here? That... means a lot, {agent}."
  },
  {
   "id": "M029",
   "kind": "injury",
   "beat": "reply",
   "choice": "there",
   "personality": "humble",
   "text": "You didn't have to come. I'm glad you did."
  },
  {
   "id": "M030",
   "kind": "injury",
   "beat": "reply",
   "choice": "flowers",
   "personality": "any",
   "text": "The flowers arrived. Nice touch. Send me some fixtures to watch too."
  },
  {
   "id": "M031",
   "kind": "thanks",
   "beat": "open",
   "choice": "",
   "personality": "any",
   "text": "Before you go. I got you something. No arguments, it's already paid for. {thing}. You've earned it ten times over."
  },
  {
   "id": "M032",
   "kind": "thanks",
   "beat": "open",
   "choice": "",
   "personality": "loyal",
   "text": "My father always said: look after the people who look after you. So here. {thing}. Thank you, {agent}."
  },
  {
   "id": "M033",
   "kind": "thanks",
   "beat": "open",
   "choice": "",
   "personality": "showman",
   "text": "Picked it out myself. {thing}! Only the best for my agent, obviously."
  },
  {
   "id": "M034",
   "kind": "thanks",
   "beat": "open",
   "choice": "",
   "personality": "humble",
   "text": "It's not much, but... {thing}. For everything you do that nobody sees."
  },
  {
   "id": "M035",
   "kind": "thanks",
   "beat": "reply",
   "choice": "cherish",
   "personality": "any",
   "text": "Good. Every time you look at it, remember we did this together."
  },
  {
   "id": "M036",
   "kind": "thanks",
   "beat": "reply",
   "choice": "cherish",
   "personality": "loyal",
   "text": "That's all I wanted to hear. We look after each other, always."
  },
  {
   "id": "M037",
   "kind": "thanks",
   "beat": "reply",
   "choice": "banter",
   "personality": "any",
   "text": "Ha! Never change, {agent}. Never change."
  },
  {
   "id": "M038",
   "kind": "thanks",
   "beat": "reply",
   "choice": "banter",
   "personality": "showman",
   "text": "See, THIS is why we get along."
  },
  {
   "id": "M039",
   "kind": "invite",
   "beat": "open",
   "choice": "",
   "personality": "any",
   "text": "I want you there at {occasion}. Not as my agent. As a friend. Say you'll come."
  },
  {
   "id": "M040",
   "kind": "invite",
   "beat": "open",
   "choice": "",
   "personality": "homebody",
   "text": "It's {occasion} soon. Small circle only, family and the people who matter. That includes you, {agent}."
  },
  {
   "id": "M041",
   "kind": "invite",
   "beat": "open",
   "choice": "",
   "personality": "showman",
   "text": "{occasion}. It's going to be THE event of the summer. You're on the list, obviously."
  },
  {
   "id": "M042",
   "kind": "invite",
   "beat": "reply",
   "choice": "attend",
   "personality": "any",
   "text": "You're coming? That means the world. See you there!"
  },
  {
   "id": "M043",
   "kind": "invite",
   "beat": "reply",
   "choice": "attend",
   "personality": "humble",
   "text": "Really? I... thank you. It wouldn't be the same without you."
  },
  {
   "id": "M044",
   "kind": "invite",
   "beat": "reply",
   "choice": "gift",
   "personality": "any",
   "text": "You can't make it? Shame. But that's very generous, thank you."
  },
  {
   "id": "M045",
   "kind": "invite",
   "beat": "reply",
   "choice": "decline",
   "personality": "any",
   "text": "Right. Busy schedule, I get it. ...I get it."
  }
 ],
 "choices": [
  {
   "scene": "complaint",
   "choice": "listen",
   "label": "Hear him out",
   "hint": "Safe. He wants to be heard."
  },
  {
   "scene": "complaint",
   "choice": "promise",
   "label": "Make him a promise",
   "hint": "Opens a promise with a real deadline."
  },
  {
   "scene": "complaint",
   "choice": "pushback",
   "label": "Push back",
   "hint": "Tell him he's wrong. Risky, depends on the man."
  },
  {
   "scene": "complaint",
   "choice": "deflect",
   "label": "Play it down",
   "hint": "Buys time. He may resent it."
  },
  {
   "scene": "gift",
   "choice": "praise",
   "label": "You earned it",
   "hint": ""
  },
  {
   "scene": "gift",
   "choice": "modest",
   "label": "Keep your head down and play",
   "hint": ""
  },
  {
   "scene": "prematch",
   "choice": "calm",
   "label": "Keep him calm",
   "hint": "Settle the nerves before the biggest game of his year."
  },
  {
   "scene": "prematch",
   "choice": "fireup",
   "label": "Fire him up",
   "hint": "Get the blood pumping."
  },
  {
   "scene": "prematch",
   "choice": "bonus",
   "label": "Promise a win bonus",
   "hint": "Pick a gift he gets if they lift the trophy. Costs nothing if they lose."
  },
  {
   "scene": "postwin",
   "choice": "toast",
   "label": "Toast him in front of everyone",
   "hint": "Public praise. Some love it, some squirm."
  },
  {
   "scene": "postwin",
   "choice": "quiet",
   "label": "A quiet word aside",
   "hint": "Just the two of you, away from the noise."
  },
  {
   "scene": "postwin",
   "choice": "tab",
   "label": "Pick up the tab tonight",
   "hint": "Costs you, means a lot."
  },
  {
   "scene": "postloss",
   "choice": "sit",
   "label": "Sit with him",
   "hint": "Say nothing. Just stay."
  },
  {
   "scene": "postloss",
   "choice": "space",
   "label": "Give him space",
   "hint": "Some wounds close alone."
  },
  {
   "scene": "postloss",
   "choice": "speech",
   "label": "We go again next season",
   "hint": "Straight to what comes next."
  },
  {
   "scene": "farewell",
   "choice": "career",
   "label": "To one hell of a career",
   "hint": ""
  },
  {
   "scene": "farewell",
   "choice": "personal",
   "label": "To the man, not just the player",
   "hint": ""
  },
  {
   "scene": "checkin",
   "choice": "q-life",
   "label": "Ask about life outside football",
   "hint": ""
  },
  {
   "scene": "checkin",
   "choice": "q-club",
   "label": "Ask about his favourite club",
   "hint": ""
  },
  {
   "scene": "checkin",
   "choice": "q-ambition",
   "label": "Ask about his ambitions",
   "hint": ""
  },
  {
   "scene": "checkin",
   "choice": "q-room",
   "label": "Ask about the dressing room",
   "hint": ""
  },
  {
   "scene": "checkin",
   "choice": "q-none",
   "label": "Nothing in particular",
   "hint": "Sometimes that says the most."
  },
  {
   "scene": "moment",
   "choice": "praise",
   "label": "Make a fuss of him",
   "hint": ""
  },
  {
   "scene": "moment",
   "choice": "modest",
   "label": "Keep it low key",
   "hint": ""
  },
  {
   "scene": "injury",
   "choice": "there",
   "label": "Visit him in person",
   "hint": ""
  },
  {
   "scene": "injury",
   "choice": "flowers",
   "label": "Send flowers",
   "hint": ""
  },
  {
   "scene": "thanks",
   "choice": "cherish",
   "label": "I'll treasure this",
   "hint": ""
  },
  {
   "scene": "thanks",
   "choice": "banter",
   "label": "About time you paid me back",
   "hint": ""
  },
  {
   "scene": "invite",
   "choice": "attend",
   "label": "Clear the diary, you'll be there",
   "hint": "A weekend of your time. It matters more than any gift."
  },
  {
   "scene": "invite",
   "choice": "gift",
   "label": "Send a generous gift",
   "hint": "You can't make it, but the thought arrives."
  },
  {
   "scene": "invite",
   "choice": "decline",
   "label": "Politely decline",
   "hint": "He'll notice."
  }
 ]
};
if (typeof module !== 'undefined' && module.exports) module.exports = { DIALOGUE_DATA };
