// AUTO-GENERATED by scripts/parse-uefa-xlsx.mjs from uefa_access_list.xlsx on 2026-07-15.
// Do not edit by hand — edit the spreadsheet (or the structural constants in the script) and re-run
//   node scripts/parse-uefa-xlsx.mjs
// See docs/europe.md for the model.
const EUROPE_DATA = {
  "generatedFrom": "uefa_access_list.xlsx",
  "generatedAt": "2026-07-15",
  "associations": [
    {
      "rank": 1,
      "name": "England",
      "implemented": true
    },
    {
      "rank": 2,
      "name": "Spain",
      "implemented": true
    },
    {
      "rank": 3,
      "name": "Italy",
      "implemented": true
    },
    {
      "rank": 4,
      "name": "Germany",
      "implemented": true
    },
    {
      "rank": 5,
      "name": "France",
      "implemented": true
    },
    {
      "rank": 6,
      "name": "Netherlands",
      "implemented": true
    },
    {
      "rank": 7,
      "name": "Portugal",
      "implemented": true
    },
    {
      "rank": 8,
      "name": "Belgium",
      "implemented": true
    },
    {
      "rank": 9,
      "name": "Switzerland",
      "implemented": true
    },
    {
      "rank": 10,
      "name": "Türkiye",
      "implemented": false
    },
    {
      "rank": 11,
      "name": "Czechia",
      "implemented": false
    },
    {
      "rank": 12,
      "name": "Greece",
      "implemented": false
    },
    {
      "rank": 13,
      "name": "Poland",
      "implemented": false
    },
    {
      "rank": 14,
      "name": "Denmark",
      "implemented": false
    },
    {
      "rank": 15,
      "name": "Norway",
      "implemented": false
    },
    {
      "rank": 16,
      "name": "Cyprus",
      "implemented": false
    },
    {
      "rank": 17,
      "name": "Hungary",
      "implemented": false
    },
    {
      "rank": 18,
      "name": "Scotland",
      "implemented": false
    },
    {
      "rank": 19,
      "name": "Sweden",
      "implemented": false
    },
    {
      "rank": 20,
      "name": "Austria",
      "implemented": false
    },
    {
      "rank": 21,
      "name": "Romania",
      "implemented": false
    },
    {
      "rank": 22,
      "name": "Croatia",
      "implemented": false
    },
    {
      "rank": 23,
      "name": "Ukraine",
      "implemented": false
    },
    {
      "rank": 24,
      "name": "Slovenia",
      "implemented": false
    },
    {
      "rank": 25,
      "name": "Azerbaijan",
      "implemented": false
    },
    {
      "rank": 26,
      "name": "Slovakia",
      "implemented": false
    },
    {
      "rank": 27,
      "name": "Bulgaria",
      "implemented": false
    },
    {
      "rank": 28,
      "name": "Iceland",
      "implemented": false
    },
    {
      "rank": 29,
      "name": "Serbia",
      "implemented": false
    },
    {
      "rank": 30,
      "name": "Russia",
      "implemented": false
    },
    {
      "rank": 31,
      "name": "Israel",
      "implemented": false
    },
    {
      "rank": 32,
      "name": "Ireland",
      "implemented": false
    },
    {
      "rank": 33,
      "name": "Armenia",
      "implemented": false
    },
    {
      "rank": 34,
      "name": "Bosnia",
      "implemented": false
    },
    {
      "rank": 35,
      "name": "Kosovo",
      "implemented": false
    },
    {
      "rank": 36,
      "name": "Kazakhstan",
      "implemented": false
    },
    {
      "rank": 37,
      "name": "Finland",
      "implemented": false
    },
    {
      "rank": 38,
      "name": "Latvia",
      "implemented": false
    },
    {
      "rank": 39,
      "name": "Moldova",
      "implemented": false
    },
    {
      "rank": 40,
      "name": "Faroe Islands",
      "implemented": false
    },
    {
      "rank": 41,
      "name": "Liechtenstein",
      "implemented": false
    },
    {
      "rank": 42,
      "name": "North Macedonia",
      "implemented": false
    },
    {
      "rank": 43,
      "name": "Malta",
      "implemented": false
    },
    {
      "rank": 44,
      "name": "Albania",
      "implemented": false
    },
    {
      "rank": 45,
      "name": "Belarus",
      "implemented": false
    },
    {
      "rank": 46,
      "name": "Lithuania",
      "implemented": false
    },
    {
      "rank": 47,
      "name": "Gibraltar",
      "implemented": false
    },
    {
      "rank": 48,
      "name": "Andorra",
      "implemented": false
    },
    {
      "rank": 49,
      "name": "Northern Ireland",
      "implemented": false
    },
    {
      "rank": 50,
      "name": "Montenegro",
      "implemented": false
    },
    {
      "rank": 51,
      "name": "Luxembourg",
      "implemented": false
    },
    {
      "rank": 52,
      "name": "Georgia",
      "implemented": false
    },
    {
      "rank": 53,
      "name": "Estonia",
      "implemented": false
    },
    {
      "rank": 54,
      "name": "Wales",
      "implemented": false
    },
    {
      "rank": 55,
      "name": "San Marino",
      "implemented": false
    }
  ],
  "implemented": {
    "England": {
      "div": "PREM",
      "cupKey": "facup",
      "slots": [
        "U",
        "U",
        "U",
        "U",
        "U",
        "UEL",
        "UELcup",
        "UECL"
      ]
    },
    "Spain": {
      "div": "LaLiga",
      "cupKey": "cdr",
      "slots": [
        "U",
        "U",
        "U",
        "U",
        "U",
        "UEL",
        "UELcup",
        "UECL"
      ]
    },
    "Italy": {
      "div": "SerieA",
      "cupKey": "coppaitalia",
      "slots": [
        "U",
        "U",
        "U",
        "U",
        "UEL",
        "UELcup",
        "UECL"
      ]
    },
    "Germany": {
      "div": "BUNDES",
      "cupKey": "dfb",
      "slots": [
        "U",
        "U",
        "U",
        "U",
        "UEL",
        "UELcup",
        "UECL"
      ]
    },
    "France": {
      "div": "Ligue1",
      "cupKey": "coupefrance",
      "slots": [
        "U",
        "U",
        "U",
        "UEL",
        "UELcup",
        "UECL"
      ]
    },
    "Netherlands": {
      "div": "ERE",
      "cupKey": "beker",
      "slots": [
        "U",
        "U",
        "UCLq",
        "UEL",
        "UELcup",
        "UELq",
        "UECL"
      ]
    },
    "Portugal": {
      "div": "LigaPortugal",
      "cupKey": "tacaportugal",
      "slots": [
        "U",
        "U",
        "UCLq",
        "UEL",
        "UELcup",
        "UELq",
        "UECL"
      ]
    },
    "Belgium": {
      "div": "JupilerProLeague",
      "cupKey": "belgiancup",
      "slots": [
        "U",
        "UCLq",
        "UELcup",
        "UELq",
        "UECL"
      ]
    },
    "Switzerland": {
      "div": "SuperLeagueCH",
      "cupKey": "schwcup",
      "slots": [
        "U",
        "UCLq",
        "UELcup",
        "UELq",
        "UECL"
      ]
    }
  },
  "pools": {
    "Türkiye": {
      "rank": 10,
      "clubs": [
        {
          "id": "eu:turkiye:galatasaray",
          "name": "Galatasaray",
          "rep": 81,
          "likelihood": 50
        },
        {
          "id": "eu:turkiye:fenerbahce",
          "name": "Fenerbahçe",
          "rep": 78,
          "likelihood": 19
        },
        {
          "id": "eu:turkiye:trabzonspor",
          "name": "Trabzonspor",
          "rep": 77,
          "likelihood": 10
        },
        {
          "id": "eu:turkiye:besiktas",
          "name": "Beşiktaş",
          "rep": 78,
          "likelihood": 15
        },
        {
          "id": "eu:turkiye:konyaspor",
          "name": "Konyaspor",
          "rep": 72,
          "likelihood": 2
        },
        {
          "id": "eu:turkiye:istanbul-basaksehir",
          "name": "İstanbul Başakşehir",
          "rep": 72,
          "likelihood": 2
        },
        {
          "id": "eu:turkiye:samsunspor",
          "name": "Samsunspor",
          "rep": 71,
          "likelihood": 1
        },
        {
          "id": "eu:turkiye:goztepe",
          "name": "Göztepe",
          "rep": 70,
          "likelihood": 1
        }
      ],
      "entries": {
        "UCL": [
          {
            "source": "league:1",
            "round": 5,
            "seeded": true
          },
          {
            "source": "league:2",
            "round": 3,
            "seeded": true
          }
        ],
        "UEL": [
          {
            "source": "cup",
            "round": 5,
            "seeded": true
          },
          {
            "source": "league:3",
            "round": 3,
            "seeded": true
          }
        ],
        "UECL": [
          {
            "source": "league:4",
            "round": 4,
            "seeded": true
          },
          {
            "source": "league:5",
            "round": 1,
            "seeded": false
          }
        ]
      }
    },
    "Czechia": {
      "rank": 11,
      "clubs": [
        {
          "id": "eu:czechia:slavia-prague",
          "name": "Slavia Prague",
          "rep": 76,
          "likelihood": 25
        },
        {
          "id": "eu:czechia:sparta-prague",
          "name": "Sparta Prague",
          "rep": 76,
          "likelihood": 25
        },
        {
          "id": "eu:czechia:viktoria-plzen",
          "name": "Viktoria Plzeň",
          "rep": 74,
          "likelihood": 15
        },
        {
          "id": "eu:czechia:jablonec",
          "name": "Jablonec",
          "rep": 73,
          "likelihood": 15
        },
        {
          "id": "eu:czechia:banik-ostrava",
          "name": "Baník Ostrava",
          "rep": 70,
          "likelihood": 3
        },
        {
          "id": "eu:czechia:slovan-liberec",
          "name": "Slovan Liberec",
          "rep": 69,
          "likelihood": 7
        },
        {
          "id": "eu:czechia:sigma-olomouc",
          "name": "Sigma Olomouc",
          "rep": 68,
          "likelihood": 3
        },
        {
          "id": "eu:czechia:mlada-boleslav",
          "name": "Mladá Boleslav",
          "rep": 66,
          "likelihood": 3
        },
        {
          "id": "eu:czechia:bohemians-1905",
          "name": "Bohemians 1905",
          "rep": 66,
          "likelihood": 3
        },
        {
          "id": "eu:czechia:hradec-kralove",
          "name": "Hradec Králové",
          "rep": 67,
          "likelihood": 2
        }
      ],
      "entries": {
        "UCL": [
          {
            "source": "league:1",
            "round": 5,
            "seeded": true
          },
          {
            "source": "league:2",
            "round": 3,
            "seeded": true
          }
        ],
        "UEL": [
          {
            "source": "cup",
            "round": 5,
            "seeded": true
          },
          {
            "source": "league:3",
            "round": 3,
            "seeded": true
          }
        ],
        "UECL": [
          {
            "source": "league:4",
            "round": 4,
            "seeded": true
          },
          {
            "source": "league:5",
            "round": 1,
            "seeded": false
          }
        ]
      }
    },
    "Greece": {
      "rank": 12,
      "clubs": [
        {
          "id": "eu:greece:aek-athens",
          "name": "AEK Athens",
          "rep": 75,
          "likelihood": 25
        },
        {
          "id": "eu:greece:olympiacos",
          "name": "Olympiacos",
          "rep": 78,
          "likelihood": 35
        },
        {
          "id": "eu:greece:paok",
          "name": "PAOK",
          "rep": 74,
          "likelihood": 21
        },
        {
          "id": "eu:greece:panathinaikos",
          "name": "Panathinaikos",
          "rep": 72,
          "likelihood": 15
        },
        {
          "id": "eu:greece:aris",
          "name": "Aris",
          "rep": 71,
          "likelihood": 3
        },
        {
          "id": "eu:greece:levadiakos",
          "name": "Levadiakos",
          "rep": 70,
          "likelihood": 1
        },
        {
          "id": "eu:greece:ofi",
          "name": "OFI",
          "rep": 69,
          "likelihood": 1
        },
        {
          "id": "eu:greece:volos",
          "name": "Volos",
          "rep": 69,
          "likelihood": 1
        }
      ],
      "entries": {
        "UCL": [
          {
            "source": "league:1",
            "round": 5,
            "seeded": true
          },
          {
            "source": "league:2",
            "round": 3,
            "seeded": true
          }
        ],
        "UEL": [
          {
            "source": "cup",
            "round": 5,
            "seeded": true
          },
          {
            "source": "league:3",
            "round": 3,
            "seeded": true
          }
        ],
        "UECL": [
          {
            "source": "league:4",
            "round": 4,
            "seeded": true
          },
          {
            "source": "league:5",
            "round": 1,
            "seeded": false
          }
        ]
      }
    },
    "Poland": {
      "rank": 13,
      "clubs": [
        {
          "id": "eu:poland:lech-poznan",
          "name": "Lech Poznań",
          "rep": 75,
          "likelihood": 35
        },
        {
          "id": "eu:poland:gornik-zabrze",
          "name": "Górnik Zabrze",
          "rep": 71,
          "likelihood": 10
        },
        {
          "id": "eu:poland:jagiellonia",
          "name": "Jagiellonia",
          "rep": 71,
          "likelihood": 10
        },
        {
          "id": "eu:poland:legia-warsaw",
          "name": "Legia Warsaw",
          "rep": 71,
          "likelihood": 10
        },
        {
          "id": "eu:poland:rakow",
          "name": "Raków",
          "rep": 71,
          "likelihood": 10
        },
        {
          "id": "eu:poland:pogon-szczecin",
          "name": "Pogoń Szczecin",
          "rep": 71,
          "likelihood": 10
        },
        {
          "id": "eu:poland:slask-wroc-aw",
          "name": "Śląsk Wrocław",
          "rep": 71,
          "likelihood": 10
        },
        {
          "id": "eu:poland:piast-gliwice",
          "name": "Piast Gliwice",
          "rep": 71,
          "likelihood": 5
        }
      ],
      "entries": {
        "UCL": [
          {
            "source": "league:1",
            "round": 5,
            "seeded": true
          },
          {
            "source": "league:2",
            "round": 3,
            "seeded": true
          }
        ],
        "UEL": [
          {
            "source": "cup",
            "round": 5,
            "seeded": true
          },
          {
            "source": "league:3",
            "round": 3,
            "seeded": true
          }
        ],
        "UECL": [
          {
            "source": "league:4",
            "round": 4,
            "seeded": true
          },
          {
            "source": "league:5",
            "round": 1,
            "seeded": false
          }
        ]
      }
    },
    "Denmark": {
      "rank": 14,
      "clubs": [
        {
          "id": "eu:denmark:agf",
          "name": "AGF",
          "rep": 73,
          "likelihood": 10
        },
        {
          "id": "eu:denmark:fc-k-benhavn",
          "name": "F.C. København",
          "rep": 78,
          "likelihood": 35
        },
        {
          "id": "eu:denmark:fc-midtjylland",
          "name": "FC Midtjylland",
          "rep": 76,
          "likelihood": 20
        },
        {
          "id": "eu:denmark:br-ndby",
          "name": "Brøndby",
          "rep": 74,
          "likelihood": 15
        },
        {
          "id": "eu:denmark:fc-nordsj-lland",
          "name": "FC Nordsjælland",
          "rep": 73,
          "likelihood": 10
        },
        {
          "id": "eu:denmark:viborg",
          "name": "Viborg",
          "rep": 70,
          "likelihood": 4
        },
        {
          "id": "eu:denmark:randers-fc",
          "name": "Randers FC",
          "rep": 70,
          "likelihood": 3
        },
        {
          "id": "eu:denmark:odense-boldklub",
          "name": "Odense Boldklub",
          "rep": 70,
          "likelihood": 3
        }
      ],
      "entries": {
        "UCL": [
          {
            "source": "league:1",
            "round": 5,
            "seeded": true
          },
          {
            "source": "league:2",
            "round": 3,
            "seeded": true
          }
        ],
        "UEL": [
          {
            "source": "cup",
            "round": 5,
            "seeded": true
          },
          {
            "source": "league:3",
            "round": 3,
            "seeded": true
          }
        ],
        "UECL": [
          {
            "source": "league:4",
            "round": 4,
            "seeded": true
          }
        ]
      }
    },
    "Norway": {
      "rank": 15,
      "clubs": [
        {
          "id": "eu:norway:viking-fk",
          "name": "Viking FK",
          "rep": 72,
          "likelihood": 10
        },
        {
          "id": "eu:norway:bod-glimt",
          "name": "Bodø/Glimt",
          "rep": 78,
          "likelihood": 25
        },
        {
          "id": "eu:norway:troms",
          "name": "Tromsø",
          "rep": 71,
          "likelihood": 15
        },
        {
          "id": "eu:norway:brann",
          "name": "Brann",
          "rep": 71,
          "likelihood": 10
        },
        {
          "id": "eu:norway:molde",
          "name": "Molde",
          "rep": 73,
          "likelihood": 15
        },
        {
          "id": "eu:norway:rosenborg",
          "name": "Rosenborg",
          "rep": 72,
          "likelihood": 10
        },
        {
          "id": "eu:norway:valerenga",
          "name": "Vålerenga",
          "rep": 70,
          "likelihood": 5
        },
        {
          "id": "eu:norway:sarpsborg-08",
          "name": "Sarpsborg 08",
          "rep": 68,
          "likelihood": 5
        },
        {
          "id": "eu:norway:odds-ballklubb",
          "name": "Odds Ballklubb",
          "rep": 67,
          "likelihood": 5
        }
      ],
      "entries": {
        "UCL": [
          {
            "source": "league:1",
            "round": 4,
            "seeded": true
          }
        ],
        "UEL": [
          {
            "source": "cup",
            "round": 5,
            "seeded": true
          },
          {
            "source": "league:3",
            "round": 3,
            "seeded": true
          }
        ],
        "UECL": [
          {
            "source": "league:4",
            "round": 3,
            "seeded": true
          }
        ]
      }
    },
    "Cyprus": {
      "rank": 16,
      "clubs": [
        {
          "id": "eu:cyprus:omonia",
          "name": "Omonia",
          "rep": 75,
          "likelihood": 20
        },
        {
          "id": "eu:cyprus:pafos",
          "name": "Pafos",
          "rep": 74,
          "likelihood": 15
        },
        {
          "id": "eu:cyprus:apoel",
          "name": "APOEL",
          "rep": 76,
          "likelihood": 30
        },
        {
          "id": "eu:cyprus:aris-limassol",
          "name": "Aris Limassol",
          "rep": 74,
          "likelihood": 15
        },
        {
          "id": "eu:cyprus:apollon-limassol",
          "name": "Apollon Limassol",
          "rep": 74,
          "likelihood": 15
        },
        {
          "id": "eu:cyprus:aek-larnaca",
          "name": "AEK Larnaca",
          "rep": 72,
          "likelihood": 4
        },
        {
          "id": "eu:cyprus:anorthosis-famagusta",
          "name": "Anorthosis Famagusta",
          "rep": 70,
          "likelihood": 1
        }
      ],
      "entries": {
        "UCL": [
          {
            "source": "league:1",
            "round": 4,
            "seeded": true
          }
        ],
        "UEL": [
          {
            "source": "cup",
            "round": 5,
            "seeded": true
          },
          {
            "source": "league:3",
            "round": 3,
            "seeded": true
          }
        ],
        "UECL": [
          {
            "source": "league:4",
            "round": 3,
            "seeded": true
          }
        ]
      }
    },
    "Hungary": {
      "rank": 17,
      "clubs": [
        {
          "id": "eu:hungary:ferencvaros",
          "name": "Ferencváros",
          "rep": 76,
          "likelihood": 50
        },
        {
          "id": "eu:hungary:puskas-akademia",
          "name": "Puskás Akadémia",
          "rep": 74,
          "likelihood": 10
        },
        {
          "id": "eu:hungary:gyor",
          "name": "Győr",
          "rep": 73,
          "likelihood": 10
        },
        {
          "id": "eu:hungary:paks",
          "name": "Paks",
          "rep": 72,
          "likelihood": 10
        },
        {
          "id": "eu:hungary:debrecen",
          "name": "Debrecen",
          "rep": 72,
          "likelihood": 10
        },
        {
          "id": "eu:hungary:ujpest",
          "name": "Újpest",
          "rep": 70,
          "likelihood": 2
        },
        {
          "id": "eu:hungary:kecskemet",
          "name": "Kecskemét",
          "rep": 70,
          "likelihood": 2
        },
        {
          "id": "eu:hungary:kisvarda",
          "name": "Kisvárda",
          "rep": 70,
          "likelihood": 2
        },
        {
          "id": "eu:hungary:fehervar",
          "name": "Fehérvár",
          "rep": 70,
          "likelihood": 2
        },
        {
          "id": "eu:hungary:videoton",
          "name": "Videoton",
          "rep": 70,
          "likelihood": 2
        }
      ],
      "entries": {
        "UCL": [
          {
            "source": "league:1",
            "round": 4,
            "seeded": true
          }
        ],
        "UEL": [
          {
            "source": "league:2",
            "round": 4,
            "seeded": true
          }
        ],
        "UECL": [
          {
            "source": "league:3",
            "round": 3,
            "seeded": true
          }
        ]
      }
    },
    "Scotland": {
      "rank": 18,
      "clubs": [
        {
          "id": "eu:scotland:celtic",
          "name": "Celtic",
          "rep": 79,
          "likelihood": 65
        },
        {
          "id": "eu:scotland:rangers",
          "name": "Rangers",
          "rep": 77,
          "likelihood": 25
        },
        {
          "id": "eu:scotland:heart-of-midlothian",
          "name": "Heart of Midlothian",
          "rep": 72,
          "likelihood": 2
        },
        {
          "id": "eu:scotland:hibernian",
          "name": "Hibernian",
          "rep": 72,
          "likelihood": 2
        },
        {
          "id": "eu:scotland:aberdenn",
          "name": "Aberdenn",
          "rep": 72,
          "likelihood": 2
        },
        {
          "id": "eu:scotland:motherwell",
          "name": "Motherwell",
          "rep": 72,
          "likelihood": 2
        },
        {
          "id": "eu:scotland:kilmarnock",
          "name": "Kilmarnock",
          "rep": 72,
          "likelihood": 2
        }
      ],
      "entries": {
        "UCL": [
          {
            "source": "league:1",
            "round": 4,
            "seeded": true
          }
        ],
        "UEL": [
          {
            "source": "league:2",
            "round": 4,
            "seeded": true
          }
        ],
        "UECL": [
          {
            "source": "league:3",
            "round": 3,
            "seeded": true
          }
        ]
      }
    },
    "Sweden": {
      "rank": 19,
      "clubs": [
        {
          "id": "eu:sweden:malmo-ff",
          "name": "Malmö FF",
          "rep": 77,
          "likelihood": 30
        },
        {
          "id": "eu:sweden:hammarby-if",
          "name": "Hammarby IF",
          "rep": 74,
          "likelihood": 14
        },
        {
          "id": "eu:sweden:if-elfsborg",
          "name": "IF Elfsborg",
          "rep": 74,
          "likelihood": 14
        },
        {
          "id": "eu:sweden:bk-hacken",
          "name": "BK Häcken",
          "rep": 74,
          "likelihood": 14
        },
        {
          "id": "eu:sweden:djurgardens-if",
          "name": "Djurgårdens IF",
          "rep": 74,
          "likelihood": 14
        },
        {
          "id": "eu:sweden:aik",
          "name": "AIK",
          "rep": 72,
          "likelihood": 7
        },
        {
          "id": "eu:sweden:ifk-norrkoping",
          "name": "IFK Norrköping",
          "rep": 72,
          "likelihood": 6
        },
        {
          "id": "eu:sweden:mjallby-aif",
          "name": "Mjällby AIF",
          "rep": 70,
          "likelihood": 1
        }
      ],
      "entries": {
        "UCL": [
          {
            "source": "league:1",
            "round": 4,
            "seeded": true
          }
        ],
        "UEL": [
          {
            "source": "league:2",
            "round": 3,
            "seeded": true
          }
        ],
        "UECL": [
          {
            "source": "league:3",
            "round": 3,
            "seeded": true
          }
        ]
      }
    },
    "Austria": {
      "rank": 20,
      "clubs": [
        {
          "id": "eu:austria:lask",
          "name": "LASK",
          "rep": 75,
          "likelihood": 15
        },
        {
          "id": "eu:austria:sturm-graz",
          "name": "Sturm Graz",
          "rep": 76,
          "likelihood": 20
        },
        {
          "id": "eu:austria:red-bull-salzburg",
          "name": "Red Bull Salzburg",
          "rep": 76,
          "likelihood": 25
        },
        {
          "id": "eu:austria:rapid-wien",
          "name": "Rapid Wien",
          "rep": 74,
          "likelihood": 15
        },
        {
          "id": "eu:austria:austria-wien",
          "name": "Austria Wien",
          "rep": 73,
          "likelihood": 15
        },
        {
          "id": "eu:austria:wolfsberg-ac",
          "name": "Wolfsberg AC",
          "rep": 71,
          "likelihood": 10
        }
      ],
      "entries": {
        "UCL": [
          {
            "source": "league:1",
            "round": 4,
            "seeded": true
          }
        ],
        "UEL": [
          {
            "source": "league:2",
            "round": 3,
            "seeded": true
          }
        ],
        "UECL": [
          {
            "source": "league:3",
            "round": 2,
            "seeded": true
          }
        ]
      }
    },
    "Romania": {
      "rank": 21,
      "clubs": [
        {
          "id": "eu:romania:universitatea-craiova",
          "name": "Universitatea Craiova",
          "rep": 74,
          "likelihood": 22
        },
        {
          "id": "eu:romania:fcsb",
          "name": "FCSB",
          "rep": 74,
          "likelihood": 25
        },
        {
          "id": "eu:romania:universitatea-cluj",
          "name": "Universitatea Cluj",
          "rep": 70,
          "likelihood": 12
        },
        {
          "id": "eu:romania:cft-cluj",
          "name": "CFT Cluj",
          "rep": 74,
          "likelihood": 25
        },
        {
          "id": "eu:romania:farul-constanta",
          "name": "Farul Constanța",
          "rep": 70,
          "likelihood": 11
        },
        {
          "id": "eu:romania:astra-giurgiu",
          "name": "Astra Giurgiu",
          "rep": 65,
          "likelihood": 5
        }
      ],
      "entries": {
        "UCL": [
          {
            "source": "league:1",
            "round": 4,
            "seeded": true
          }
        ],
        "UEL": [
          {
            "source": "league:2",
            "round": 3,
            "seeded": true
          }
        ],
        "UECL": [
          {
            "source": "league:3",
            "round": 2,
            "seeded": true
          }
        ]
      }
    },
    "Croatia": {
      "rank": 22,
      "clubs": [
        {
          "id": "eu:croatia:dinamo-zagreb",
          "name": "Dinamo Zagreb",
          "rep": 78,
          "likelihood": 55
        },
        {
          "id": "eu:croatia:hajduk-split",
          "name": "Hajduk Split",
          "rep": 75,
          "likelihood": 15
        },
        {
          "id": "eu:croatia:hnk-rijeka",
          "name": "HNK Rijeka",
          "rep": 73,
          "likelihood": 10
        },
        {
          "id": "eu:croatia:nk-varazdin",
          "name": "NK Varaždin",
          "rep": 71,
          "likelihood": 5
        },
        {
          "id": "eu:croatia:nk-osijek",
          "name": "NK Osijek",
          "rep": 73,
          "likelihood": 10
        },
        {
          "id": "eu:croatia:nk-lokomotiva",
          "name": "NK Lokomotiva",
          "rep": 71,
          "likelihood": 5
        }
      ],
      "entries": {
        "UCL": [
          {
            "source": "league:1",
            "round": 4,
            "seeded": true
          }
        ],
        "UEL": [
          {
            "source": "league:2",
            "round": 3,
            "seeded": true
          }
        ],
        "UECL": [
          {
            "source": "league:3",
            "round": 2,
            "seeded": true
          }
        ]
      }
    },
    "Ukraine": {
      "rank": 23,
      "clubs": [
        {
          "id": "eu:ukraine:shakhtar-donetsk",
          "name": "Shakhtar Donetsk",
          "rep": 78,
          "likelihood": 35
        },
        {
          "id": "eu:ukraine:dynamo-kyiv",
          "name": "Dynamo Kyiv",
          "rep": 75,
          "likelihood": 25
        },
        {
          "id": "eu:ukraine:lnz-cherkasy",
          "name": "LNZ Cherkasy",
          "rep": 69,
          "likelihood": 10
        },
        {
          "id": "eu:ukraine:oleksandriya",
          "name": "Oleksandriya",
          "rep": 69,
          "likelihood": 10
        },
        {
          "id": "eu:ukraine:polissya-zhytomyr",
          "name": "Polissya Zhytomyr",
          "rep": 69,
          "likelihood": 10
        },
        {
          "id": "eu:ukraine:zorya-luhansk",
          "name": "Zorya Luhansk",
          "rep": 69,
          "likelihood": 10
        }
      ],
      "entries": {
        "UCL": [
          {
            "source": "league:1",
            "round": 4,
            "seeded": true
          }
        ],
        "UEL": [
          {
            "source": "league:2",
            "round": 2,
            "seeded": true
          }
        ],
        "UECL": [
          {
            "source": "league:3",
            "round": 2,
            "seeded": true
          }
        ]
      }
    },
    "Slovenia": {
      "rank": 24,
      "clubs": [
        {
          "id": "eu:slovenia:nk-celje",
          "name": "NK Celje",
          "rep": 73,
          "likelihood": 25
        },
        {
          "id": "eu:slovenia:fc-koper",
          "name": "FC Koper",
          "rep": 68,
          "likelihood": 15
        },
        {
          "id": "eu:slovenia:olimpija-ljubljana",
          "name": "Olimpija Ljubljana",
          "rep": 71,
          "likelihood": 25
        },
        {
          "id": "eu:slovenia:nk-maribor",
          "name": "NK Maribor",
          "rep": 71,
          "likelihood": 25
        },
        {
          "id": "eu:slovenia:ns-mura",
          "name": "NŠ Mura",
          "rep": 65,
          "likelihood": 5
        },
        {
          "id": "eu:slovenia:gorica",
          "name": "Gorica",
          "rep": 65,
          "likelihood": 5
        }
      ],
      "entries": {
        "UCL": [
          {
            "source": "league:1",
            "round": 3,
            "seeded": true
          }
        ],
        "UEL": [
          {
            "source": "league:2",
            "round": 2,
            "seeded": true
          }
        ],
        "UECL": [
          {
            "source": "league:3",
            "round": 2,
            "seeded": true
          }
        ]
      }
    },
    "Azerbaijan": {
      "rank": 25,
      "clubs": [
        {
          "id": "eu:azerbaijan:sabah",
          "name": "Sabah",
          "rep": 71,
          "likelihood": 15
        },
        {
          "id": "eu:azerbaijan:qarabag",
          "name": "Qarabağ",
          "rep": 75,
          "likelihood": 60
        },
        {
          "id": "eu:azerbaijan:zira",
          "name": "Zira",
          "rep": 69,
          "likelihood": 10
        },
        {
          "id": "eu:azerbaijan:turan-tovuz",
          "name": "Turan Tovuz",
          "rep": 67,
          "likelihood": 9
        },
        {
          "id": "eu:azerbaijan:araz-naxc-van",
          "name": "Araz-Naxçıvan",
          "rep": 65,
          "likelihood": 3
        },
        {
          "id": "eu:azerbaijan:neftci",
          "name": "Neftçi",
          "rep": 65,
          "likelihood": 3
        }
      ],
      "entries": {
        "UCL": [
          {
            "source": "league:1",
            "round": 3,
            "seeded": true
          }
        ],
        "UEL": [
          {
            "source": "league:2",
            "round": 2,
            "seeded": true
          }
        ],
        "UECL": [
          {
            "source": "league:3",
            "round": 2,
            "seeded": true
          }
        ]
      }
    },
    "Slovakia": {
      "rank": 26,
      "clubs": [
        {
          "id": "eu:slovakia:slovan-bratislava",
          "name": "Slovan Bratislava",
          "rep": 75,
          "likelihood": 60
        },
        {
          "id": "eu:slovakia:fc-dac-1904",
          "name": "FC DAC 1904",
          "rep": 69,
          "likelihood": 15
        },
        {
          "id": "eu:slovakia:spartak-trnava",
          "name": "Spartak Trnava",
          "rep": 69,
          "likelihood": 10
        },
        {
          "id": "eu:slovakia:msk-zilina",
          "name": "MŠK Žilina",
          "rep": 68,
          "likelihood": 9
        },
        {
          "id": "eu:slovakia:ruzomberok",
          "name": "Ružomberok",
          "rep": 64,
          "likelihood": 3
        },
        {
          "id": "eu:slovakia:as-trencin",
          "name": "AS Trenčín",
          "rep": 64,
          "likelihood": 3
        }
      ],
      "entries": {
        "UCL": [
          {
            "source": "league:1",
            "round": 3,
            "seeded": true
          }
        ],
        "UEL": [
          {
            "source": "league:2",
            "round": 2,
            "seeded": true
          }
        ],
        "UECL": [
          {
            "source": "league:3",
            "round": 2,
            "seeded": true
          }
        ]
      }
    },
    "Bulgaria": {
      "rank": 27,
      "clubs": [
        {
          "id": "eu:bulgaria:ludogorets-razgrad",
          "name": "Ludogorets Razgrad",
          "rep": 75,
          "likelihood": 45
        },
        {
          "id": "eu:bulgaria:levski-sofia",
          "name": "Levski Sofia",
          "rep": 68,
          "likelihood": 15
        },
        {
          "id": "eu:bulgaria:cska-1948",
          "name": "CSKA 1948",
          "rep": 68,
          "likelihood": 15
        },
        {
          "id": "eu:bulgaria:cska-sofia",
          "name": "CSKA Sofia",
          "rep": 71,
          "likelihood": 20
        },
        {
          "id": "eu:bulgaria:cherno-more",
          "name": "Cherno More",
          "rep": 64,
          "likelihood": 3
        },
        {
          "id": "eu:bulgaria:botev-plovdiv",
          "name": "Botev Plovdiv",
          "rep": 64,
          "likelihood": 2
        }
      ],
      "entries": {
        "UCL": [
          {
            "source": "league:1",
            "round": 3,
            "seeded": true
          }
        ],
        "UEL": [
          {
            "source": "league:2",
            "round": 2,
            "seeded": true
          }
        ],
        "UECL": [
          {
            "source": "league:3",
            "round": 1,
            "seeded": false
          }
        ]
      }
    },
    "Iceland": {
      "rank": 28,
      "clubs": [
        {
          "id": "eu:iceland:vikingur",
          "name": "Víkingur",
          "rep": 70,
          "likelihood": 30
        },
        {
          "id": "eu:iceland:brei-ablik",
          "name": "Breiðablik",
          "rep": 70,
          "likelihood": 30
        },
        {
          "id": "eu:iceland:valur",
          "name": "Valur",
          "rep": 68,
          "likelihood": 20
        },
        {
          "id": "eu:iceland:kr",
          "name": "KR",
          "rep": 67,
          "likelihood": 10
        },
        {
          "id": "eu:iceland:fh",
          "name": "FH",
          "rep": 66,
          "likelihood": 7
        },
        {
          "id": "eu:iceland:stjarnan",
          "name": "Stjarnan",
          "rep": 65,
          "likelihood": 3
        }
      ],
      "entries": {
        "UCL": [
          {
            "source": "league:1",
            "round": 2,
            "seeded": true
          }
        ],
        "UEL": [
          {
            "source": "league:2",
            "round": 2,
            "seeded": true
          }
        ],
        "UECL": [
          {
            "source": "league:3",
            "round": 1,
            "seeded": false
          }
        ]
      }
    },
    "Serbia": {
      "rank": 29,
      "clubs": [
        {
          "id": "eu:serbia:crvena-zvezda",
          "name": "Crvena zvezda",
          "rep": 77,
          "likelihood": 60
        },
        {
          "id": "eu:serbia:fk-partizan",
          "name": "FK Partizan",
          "rep": 74,
          "likelihood": 20
        },
        {
          "id": "eu:serbia:fk-vojvodina",
          "name": "FK Vojvodina",
          "rep": 72,
          "likelihood": 8
        },
        {
          "id": "eu:serbia:fk-novi-pazar",
          "name": "FK Novi Pazar",
          "rep": 65,
          "likelihood": 4
        },
        {
          "id": "eu:serbia:fk-tsc",
          "name": "FK TSC",
          "rep": 65,
          "likelihood": 4
        },
        {
          "id": "eu:serbia:fk-cukaricki",
          "name": "FK Čukarički",
          "rep": 68,
          "likelihood": 4
        }
      ],
      "entries": {
        "UCL": [
          {
            "source": "league:1",
            "round": 2,
            "seeded": true
          }
        ],
        "UEL": [
          {
            "source": "league:2",
            "round": 2,
            "seeded": true
          }
        ],
        "UECL": [
          {
            "source": "league:3",
            "round": 1,
            "seeded": false
          }
        ]
      }
    },
    "Russia": {
      "rank": 30,
      "clubs": [
        {
          "id": "eu:russia:zenit",
          "name": "Zenit",
          "rep": 74,
          "likelihood": 55
        },
        {
          "id": "eu:russia:fc-krasnodar",
          "name": "FC Krasnodar",
          "rep": 70,
          "likelihood": 14
        },
        {
          "id": "eu:russia:lokomotiv-moscow",
          "name": "Lokomotiv Moscow",
          "rep": 70,
          "likelihood": 14
        },
        {
          "id": "eu:russia:cska-moscow",
          "name": "CSKA Moscow",
          "rep": 70,
          "likelihood": 14
        },
        {
          "id": "eu:russia:dynamo-moscow",
          "name": "Dynamo Moscow",
          "rep": 68,
          "likelihood": 8
        },
        {
          "id": "eu:russia:spartak-moscow",
          "name": "Spartak Moscow",
          "rep": 67,
          "likelihood": 3
        },
        {
          "id": "eu:russia:fc-sochi",
          "name": "FC Sochi",
          "rep": 66,
          "likelihood": 2
        }
      ],
      "entries": {
        "UCL": [
          {
            "source": "league:1",
            "round": 2,
            "seeded": true
          }
        ],
        "UEL": [
          {
            "source": "league:2",
            "round": 2,
            "seeded": true
          }
        ],
        "UECL": [
          {
            "source": "league:3",
            "round": 1,
            "seeded": false
          }
        ]
      }
    },
    "Israel": {
      "rank": 31,
      "clubs": [
        {
          "id": "eu:israel:hapoel-beer-scheva",
          "name": "Hapoel Be’er Scheva",
          "rep": 67,
          "likelihood": 25
        },
        {
          "id": "eu:israel:maccabi-tel-aviv",
          "name": "Maccabi Tel Aviv",
          "rep": 67,
          "likelihood": 25
        },
        {
          "id": "eu:israel:maccabi-haifa",
          "name": "Maccabi Haifa",
          "rep": 67,
          "likelihood": 25
        },
        {
          "id": "eu:israel:beitar-jerusalem",
          "name": "Beitar Jerusalem",
          "rep": 62,
          "likelihood": 15
        },
        {
          "id": "eu:israel:fc-ashdod",
          "name": "FC Ashdod",
          "rep": 59,
          "likelihood": 5
        },
        {
          "id": "eu:israel:ironi-kiryat-shmona",
          "name": "Ironi Kiryat Shmona",
          "rep": 59,
          "likelihood": 5
        }
      ],
      "entries": {
        "UCL": [
          {
            "source": "league:1",
            "round": 2,
            "seeded": true
          }
        ],
        "UEL": [
          {
            "source": "league:2",
            "round": 2,
            "seeded": true
          }
        ],
        "UECL": [
          {
            "source": "league:3",
            "round": 1,
            "seeded": false
          }
        ]
      }
    },
    "Ireland": {
      "rank": 32,
      "clubs": [
        {
          "id": "eu:ireland:shamrock-rovers",
          "name": "Shamrock Rovers",
          "rep": 70,
          "likelihood": 55
        },
        {
          "id": "eu:ireland:shelbourne-fc",
          "name": "Shelbourne FC",
          "rep": 65,
          "likelihood": 10
        },
        {
          "id": "eu:ireland:derry-city-fc",
          "name": "Derry City FC",
          "rep": 63,
          "likelihood": 10
        },
        {
          "id": "eu:ireland:st-patricks-athletic",
          "name": "St. Patrick's Athletic",
          "rep": 60,
          "likelihood": 10
        },
        {
          "id": "eu:ireland:dundalk-fc",
          "name": "Dundalk FC",
          "rep": 60,
          "likelihood": 10
        },
        {
          "id": "eu:ireland:bohemians-fc",
          "name": "Bohemians FC",
          "rep": 60,
          "likelihood": 5
        }
      ],
      "entries": {
        "UCL": [
          {
            "source": "league:1",
            "round": 2,
            "seeded": true
          }
        ],
        "UEL": [
          {
            "source": "league:2",
            "round": 2,
            "seeded": true
          }
        ],
        "UECL": [
          {
            "source": "league:3",
            "round": 1,
            "seeded": false
          }
        ]
      }
    },
    "Armenia": {
      "rank": 33,
      "clubs": [
        {
          "id": "eu:armenia:fc-ararat-armenia",
          "name": "FC Ararat-Armenia",
          "rep": 69,
          "likelihood": 30
        },
        {
          "id": "eu:armenia:fc-noah",
          "name": "FC Noah",
          "rep": 69,
          "likelihood": 30
        },
        {
          "id": "eu:armenia:fc-pyunik",
          "name": "FC Pyunik",
          "rep": 67,
          "likelihood": 20
        },
        {
          "id": "eu:armenia:fc-urartu",
          "name": "FC Urartu",
          "rep": 63,
          "likelihood": 10
        },
        {
          "id": "eu:armenia:fc-alashkert",
          "name": "FC Alashkert",
          "rep": 58,
          "likelihood": 8
        },
        {
          "id": "eu:armenia:fc-gandzasar",
          "name": "FC Gandzasar",
          "rep": 55,
          "likelihood": 2
        }
      ],
      "entries": {
        "UCL": [
          {
            "source": "league:1",
            "round": 2,
            "seeded": true
          }
        ],
        "UEL": [
          {
            "source": "league:2",
            "round": 2,
            "seeded": true
          }
        ],
        "UECL": [
          {
            "source": "league:3",
            "round": 1,
            "seeded": false
          }
        ]
      }
    },
    "Bosnia": {
      "rank": 34,
      "clubs": [
        {
          "id": "eu:bosnia:fk-borac",
          "name": "FK Borac",
          "rep": 67,
          "likelihood": 30
        },
        {
          "id": "eu:bosnia:hsk-zrinjski",
          "name": "HŠK Zrinjski",
          "rep": 69,
          "likelihood": 35
        },
        {
          "id": "eu:bosnia:fk-sarajevo",
          "name": "FK Sarajevo",
          "rep": 66,
          "likelihood": 20
        },
        {
          "id": "eu:bosnia:fk-velez",
          "name": "FK Velež",
          "rep": 63,
          "likelihood": 10
        },
        {
          "id": "eu:bosnia:fk-zeljeznicar",
          "name": "FK Željezničar",
          "rep": 62,
          "likelihood": 3
        },
        {
          "id": "eu:bosnia:fk-tuzla-city",
          "name": "FK Tuzla City",
          "rep": 59,
          "likelihood": 2
        }
      ],
      "entries": {
        "UCL": [
          {
            "source": "league:1",
            "round": 2,
            "seeded": true
          }
        ],
        "UEL": [
          {
            "source": "league:2",
            "round": 1,
            "seeded": false
          }
        ],
        "UECL": [
          {
            "source": "league:3",
            "round": 1,
            "seeded": false
          }
        ]
      }
    },
    "Kosovo": {
      "rank": 35,
      "clubs": [
        {
          "id": "eu:kosovo:fc-drita",
          "name": "FC Drita",
          "rep": 65,
          "likelihood": 35
        },
        {
          "id": "eu:kosovo:fc-ballkani",
          "name": "FC Ballkani",
          "rep": 63,
          "likelihood": 30
        },
        {
          "id": "eu:kosovo:fc-prishtina",
          "name": "FC Prishtina",
          "rep": 62,
          "likelihood": 20
        },
        {
          "id": "eu:kosovo:fc-feronikeli-74",
          "name": "FC Feronikeli 74",
          "rep": 62,
          "likelihood": 10
        },
        {
          "id": "eu:kosovo:kf-trepca-89",
          "name": "KF Trepça '89",
          "rep": 60,
          "likelihood": 3
        },
        {
          "id": "eu:kosovo:fc-vushtrria",
          "name": "FC Vushtrria",
          "rep": 58,
          "likelihood": 2
        }
      ],
      "entries": {
        "UCL": [
          {
            "source": "league:1",
            "round": 2,
            "seeded": true
          }
        ],
        "UEL": [
          {
            "source": "league:2",
            "round": 1,
            "seeded": false
          }
        ],
        "UECL": [
          {
            "source": "league:3",
            "round": 1,
            "seeded": false
          }
        ]
      }
    },
    "Kazakhstan": {
      "rank": 36,
      "clubs": [
        {
          "id": "eu:kazakhstan:kairat-almaty",
          "name": "Kairat Almaty",
          "rep": 69,
          "likelihood": 30
        },
        {
          "id": "eu:kazakhstan:astana-fk",
          "name": "Astana FK",
          "rep": 66,
          "likelihood": 30
        },
        {
          "id": "eu:kazakhstan:fc-ordabasy",
          "name": "FC Ordabasy",
          "rep": 62,
          "likelihood": 20
        },
        {
          "id": "eu:kazakhstan:fc-tobol",
          "name": "FC Tobol",
          "rep": 62,
          "likelihood": 10
        },
        {
          "id": "eu:kazakhstan:fc-aktobe",
          "name": "FC Aktobe",
          "rep": 60,
          "likelihood": 7
        },
        {
          "id": "eu:kazakhstan:fc-irtysh",
          "name": "FC Irtysh",
          "rep": 57,
          "likelihood": 3
        }
      ],
      "entries": {
        "UCL": [
          {
            "source": "league:1",
            "round": 2,
            "seeded": true
          }
        ],
        "UEL": [
          {
            "source": "league:2",
            "round": 1,
            "seeded": false
          }
        ],
        "UECL": [
          {
            "source": "league:3",
            "round": 1,
            "seeded": false
          }
        ]
      }
    },
    "Finland": {
      "rank": 37,
      "clubs": [
        {
          "id": "eu:finland:kups",
          "name": "KuPS",
          "rep": 64,
          "likelihood": 35
        },
        {
          "id": "eu:finland:hjk",
          "name": "HJK",
          "rep": 62,
          "likelihood": 30
        },
        {
          "id": "eu:finland:ilves",
          "name": "Ilves",
          "rep": 60,
          "likelihood": 20
        },
        {
          "id": "eu:finland:fc-inter-turku",
          "name": "FC Inter Turku",
          "rep": 59,
          "likelihood": 10
        },
        {
          "id": "eu:finland:vps",
          "name": "VPS",
          "rep": 56,
          "likelihood": 3
        },
        {
          "id": "eu:finland:fc-honka",
          "name": "FC Honka",
          "rep": 52,
          "likelihood": 2
        }
      ],
      "entries": {
        "UCL": [
          {
            "source": "league:1",
            "round": 1,
            "seeded": false
          }
        ],
        "UEL": [
          {
            "source": "league:2",
            "round": 1,
            "seeded": false
          }
        ],
        "UECL": [
          {
            "source": "league:3",
            "round": 1,
            "seeded": false
          }
        ]
      }
    },
    "Latvia": {
      "rank": 38,
      "clubs": [
        {
          "id": "eu:latvia:riga-fc",
          "name": "Riga FC",
          "rep": 61,
          "likelihood": 35
        },
        {
          "id": "eu:latvia:fk-rfs",
          "name": "FK RFS",
          "rep": 59,
          "likelihood": 30
        },
        {
          "id": "eu:latvia:valmiera-fc",
          "name": "Valmiera FC",
          "rep": 56,
          "likelihood": 20
        },
        {
          "id": "eu:latvia:fk-spartans",
          "name": "FK Spartans",
          "rep": 53,
          "likelihood": 10
        },
        {
          "id": "eu:latvia:fk-ventspils",
          "name": "FK Ventspils",
          "rep": 52,
          "likelihood": 3
        },
        {
          "id": "eu:latvia:fk-liepaja",
          "name": "FK Liepaja",
          "rep": 51,
          "likelihood": 2
        }
      ],
      "entries": {
        "UCL": [
          {
            "source": "league:1",
            "round": 1,
            "seeded": false
          }
        ],
        "UEL": [
          {
            "source": "league:2",
            "round": 1,
            "seeded": false
          }
        ],
        "UECL": [
          {
            "source": "league:3",
            "round": 1,
            "seeded": false
          }
        ]
      }
    },
    "Moldova": {
      "rank": 39,
      "clubs": [
        {
          "id": "eu:moldova:petrocub-hincesti",
          "name": "Petrocub Hîncești",
          "rep": 62,
          "likelihood": 25
        },
        {
          "id": "eu:moldova:sheriff-tiraspol",
          "name": "Sheriff Tiraspol",
          "rep": 68,
          "likelihood": 45
        },
        {
          "id": "eu:moldova:milsami-orhei",
          "name": "Milsami Orhei",
          "rep": 58,
          "likelihood": 15
        },
        {
          "id": "eu:moldova:zimbru-chisinau",
          "name": "Zimbru Chișinău",
          "rep": 54,
          "likelihood": 10
        },
        {
          "id": "eu:moldova:sfantul-gheorghe",
          "name": "Sfântul Gheorghe",
          "rep": 50,
          "likelihood": 5
        }
      ],
      "entries": {
        "UCL": [
          {
            "source": "league:1",
            "round": 1,
            "seeded": false
          }
        ],
        "UEL": [
          {
            "source": "league:2",
            "round": 1,
            "seeded": false
          }
        ],
        "UECL": [
          {
            "source": "league:3",
            "round": 1,
            "seeded": false
          }
        ]
      }
    },
    "Faroe Islands": {
      "rank": 40,
      "clubs": [
        {
          "id": "eu:faroe-islands:ki-klaksvik",
          "name": "KÍ Klaksvík",
          "rep": 63,
          "likelihood": 50
        },
        {
          "id": "eu:faroe-islands:vikingur",
          "name": "Víkingur",
          "rep": 58,
          "likelihood": 20
        },
        {
          "id": "eu:faroe-islands:havnar-boltfelag",
          "name": "Havnar Bóltfelag",
          "rep": 53,
          "likelihood": 20
        },
        {
          "id": "eu:faroe-islands:nsi-runavik",
          "name": "NSÍ Runavík",
          "rep": 50,
          "likelihood": 5
        },
        {
          "id": "eu:faroe-islands:b36-torshavn",
          "name": "B36 Tórshavn",
          "rep": 52,
          "likelihood": 5
        }
      ],
      "entries": {
        "UCL": [
          {
            "source": "league:1",
            "round": 1,
            "seeded": false
          }
        ],
        "UEL": [
          {
            "source": "league:2",
            "round": 1,
            "seeded": false
          }
        ],
        "UECL": [
          {
            "source": "league:3",
            "round": 1,
            "seeded": false
          }
        ]
      }
    },
    "Liechtenstein": {
      "rank": 41,
      "clubs": [
        {
          "id": "Vaduz",
          "name": "FC Vaduz",
          "rep": 62,
          "likelihood": 82,
          "real": true
        },
        {
          "id": "Eschen/Mauren",
          "name": "USV Eschen/Mauren",
          "rep": 24,
          "likelihood": 18,
          "real": true
        }
      ],
      "entries": {
        "UCL": [],
        "UEL": [
          {
            "source": "cup",
            "round": 1,
            "seeded": false
          }
        ],
        "UECL": []
      }
    },
    "North Macedonia": {
      "rank": 42,
      "clubs": [
        {
          "id": "eu:north-macedonia:vardar-skopje",
          "name": "Vardar Skopje",
          "rep": 57,
          "likelihood": 30
        },
        {
          "id": "eu:north-macedonia:kf-shkendija",
          "name": "KF Shkëndija",
          "rep": 55,
          "likelihood": 30
        },
        {
          "id": "eu:north-macedonia:fc-struga",
          "name": "FC Struga",
          "rep": 52,
          "likelihood": 20
        },
        {
          "id": "eu:north-macedonia:fc-shkupi",
          "name": "FC Shkupi",
          "rep": 50,
          "likelihood": 15
        },
        {
          "id": "eu:north-macedonia:akademija-pandev",
          "name": "Akademija Pandev",
          "rep": 48,
          "likelihood": 5
        }
      ],
      "entries": {
        "UCL": [
          {
            "source": "league:1",
            "round": 1,
            "seeded": false
          }
        ],
        "UEL": [
          {
            "source": "league:2",
            "round": 1,
            "seeded": false
          }
        ],
        "UECL": [
          {
            "source": "league:3",
            "round": 1,
            "seeded": false
          }
        ]
      }
    },
    "Malta": {
      "rank": 43,
      "clubs": [
        {
          "id": "eu:malta:amrun-spartans",
          "name": "Ħamrun Spartans",
          "rep": 52,
          "likelihood": 30
        },
        {
          "id": "eu:malta:fc-floriana",
          "name": "FC Floriana",
          "rep": 55,
          "likelihood": 30
        },
        {
          "id": "eu:malta:hibernians-paopla",
          "name": "Hibernians Paopla",
          "rep": 50,
          "likelihood": 20
        },
        {
          "id": "eu:malta:fc-valletta",
          "name": "FC Valletta",
          "rep": 48,
          "likelihood": 15
        },
        {
          "id": "eu:malta:fc-birkirkara",
          "name": "FC Birkirkara",
          "rep": 45,
          "likelihood": 5
        }
      ],
      "entries": {
        "UCL": [
          {
            "source": "league:1",
            "round": 1,
            "seeded": false
          }
        ],
        "UEL": [
          {
            "source": "league:2",
            "round": 1,
            "seeded": false
          }
        ],
        "UECL": [
          {
            "source": "league:3",
            "round": 1,
            "seeded": false
          }
        ]
      }
    },
    "Albania": {
      "rank": 44,
      "clubs": [
        {
          "id": "eu:albania:kf-egnatia",
          "name": "KF Egnatia",
          "rep": 59,
          "likelihood": 20
        },
        {
          "id": "eu:albania:kf-vllaznia",
          "name": "KF Vllaznia",
          "rep": 57,
          "likelihood": 20
        },
        {
          "id": "eu:albania:fk-partizani",
          "name": "FK Partizani",
          "rep": 56,
          "likelihood": 20
        },
        {
          "id": "eu:albania:kf-skenderbeu",
          "name": "KF Skënderbeu",
          "rep": 55,
          "likelihood": 20
        },
        {
          "id": "eu:albania:kf-tirana",
          "name": "KF Tirana",
          "rep": 53,
          "likelihood": 20
        }
      ],
      "entries": {
        "UCL": [
          {
            "source": "league:1",
            "round": 1,
            "seeded": false
          }
        ],
        "UEL": [
          {
            "source": "league:2",
            "round": 1,
            "seeded": false
          }
        ],
        "UECL": [
          {
            "source": "league:3",
            "round": 1,
            "seeded": false
          }
        ]
      }
    },
    "Belarus": {
      "rank": 45,
      "clubs": [
        {
          "id": "eu:belarus:dinamo-minsk",
          "name": "Dinamo Minsk",
          "rep": 68,
          "likelihood": 30
        },
        {
          "id": "eu:belarus:fk-maxline-wizebsk",
          "name": "FK Maxline Wizebsk",
          "rep": 57,
          "likelihood": 15
        },
        {
          "id": "eu:belarus:bate-borisov",
          "name": "BATE Borisov",
          "rep": 64,
          "likelihood": 30
        },
        {
          "id": "eu:belarus:fc-shakhtyor-soligorsk",
          "name": "FC Shakhtyor Soligorsk",
          "rep": 51,
          "likelihood": 15
        },
        {
          "id": "eu:belarus:fk-njoman-hrodna",
          "name": "FK Njoman Hrodna",
          "rep": 50,
          "likelihood": 10
        }
      ],
      "entries": {
        "UCL": [
          {
            "source": "league:1",
            "round": 1,
            "seeded": false
          }
        ],
        "UEL": [
          {
            "source": "league:2",
            "round": 1,
            "seeded": false
          }
        ],
        "UECL": [
          {
            "source": "league:3",
            "round": 1,
            "seeded": false
          }
        ]
      }
    },
    "Lithuania": {
      "rank": 46,
      "clubs": [
        {
          "id": "eu:lithuania:fk-kauno-zalgiris",
          "name": "FK Kauno Žalgiris",
          "rep": 58,
          "likelihood": 25
        },
        {
          "id": "eu:lithuania:fk-zalgiris",
          "name": "FK Žalgiris",
          "rep": 55,
          "likelihood": 30
        },
        {
          "id": "eu:lithuania:fc-hegelmann",
          "name": "FC Hegelmann",
          "rep": 50,
          "likelihood": 10
        },
        {
          "id": "eu:lithuania:fk-panevezys",
          "name": "FK Panevėžys",
          "rep": 49,
          "likelihood": 15
        },
        {
          "id": "eu:lithuania:fk-suduva",
          "name": "FK Sūduva",
          "rep": 47,
          "likelihood": 10
        },
        {
          "id": "eu:lithuania:fa-siauliai",
          "name": "FA Šiauliai",
          "rep": 46,
          "likelihood": 10
        }
      ],
      "entries": {
        "UCL": [
          {
            "source": "league:1",
            "round": 1,
            "seeded": false
          }
        ],
        "UEL": [
          {
            "source": "league:2",
            "round": 1,
            "seeded": false
          }
        ],
        "UECL": [
          {
            "source": "league:3",
            "round": 1,
            "seeded": false
          }
        ]
      }
    },
    "Gibraltar": {
      "rank": 47,
      "clubs": [
        {
          "id": "eu:gibraltar:lincoln-red-imps-fc",
          "name": "Lincoln Red Imps FC",
          "rep": 50,
          "likelihood": 80
        },
        {
          "id": "eu:gibraltar:st-josephs-fc",
          "name": "St Joseph’s FC",
          "rep": 48,
          "likelihood": 10
        },
        {
          "id": "eu:gibraltar:europa-fc",
          "name": "Europa FC",
          "rep": 47,
          "likelihood": 5
        },
        {
          "id": "eu:gibraltar:mons-calpe-sc",
          "name": "Mons Calpe SC",
          "rep": 45,
          "likelihood": 3
        },
        {
          "id": "eu:gibraltar:manchester-62-fc",
          "name": "Manchester 62 FC",
          "rep": 42,
          "likelihood": 2
        }
      ],
      "entries": {
        "UCL": [
          {
            "source": "league:1",
            "round": 1,
            "seeded": false
          }
        ],
        "UEL": [
          {
            "source": "league:2",
            "round": 1,
            "seeded": false
          }
        ],
        "UECL": [
          {
            "source": "league:3",
            "round": 1,
            "seeded": false
          }
        ]
      }
    },
    "Andorra": {
      "rank": 48,
      "clubs": [
        {
          "id": "eu:andorra:inter-club-descaldes",
          "name": "Inter Club d’Escaldes",
          "rep": 51,
          "likelihood": 33
        },
        {
          "id": "eu:andorra:ue-santa-coloma",
          "name": "UE Santa Coloma",
          "rep": 50,
          "likelihood": 27
        },
        {
          "id": "eu:andorra:atletic-club-descaldes",
          "name": "Atlètic Club d’Escaldes",
          "rep": 49,
          "likelihood": 20
        },
        {
          "id": "eu:andorra:fc-santa-coloma",
          "name": "FC Santa Coloma",
          "rep": 48,
          "likelihood": 15
        },
        {
          "id": "eu:andorra:fc-rangers",
          "name": "FC Rànger’s",
          "rep": 45,
          "likelihood": 5
        }
      ],
      "entries": {
        "UCL": [
          {
            "source": "league:1",
            "round": 1,
            "seeded": false
          }
        ],
        "UEL": [
          {
            "source": "league:2",
            "round": 1,
            "seeded": false
          }
        ],
        "UECL": [
          {
            "source": "league:3",
            "round": 1,
            "seeded": false
          }
        ]
      }
    },
    "Northern Ireland": {
      "rank": 49,
      "clubs": [
        {
          "id": "eu:northern-ireland:linfield-fc",
          "name": "Linfield FC",
          "rep": 52,
          "likelihood": 40
        },
        {
          "id": "eu:northern-ireland:larne-fc",
          "name": "Larne FC",
          "rep": 51,
          "likelihood": 30
        },
        {
          "id": "eu:northern-ireland:crusaders-fc",
          "name": "Crusaders FC",
          "rep": 48,
          "likelihood": 15
        },
        {
          "id": "eu:northern-ireland:cliftonville-fc",
          "name": "Cliftonville FC",
          "rep": 47,
          "likelihood": 10
        },
        {
          "id": "eu:northern-ireland:glentoran-fc",
          "name": "Glentoran FC",
          "rep": 46,
          "likelihood": 5
        }
      ],
      "entries": {
        "UCL": [
          {
            "source": "league:1",
            "round": 1,
            "seeded": false
          }
        ],
        "UEL": [
          {
            "source": "league:2",
            "round": 1,
            "seeded": false
          }
        ],
        "UECL": [
          {
            "source": "league:3",
            "round": 1,
            "seeded": false
          }
        ]
      }
    },
    "Montenegro": {
      "rank": 50,
      "clubs": [
        {
          "id": "eu:montenegro:fk-buducnost-podgorica",
          "name": "FK Budućnost Podgorica",
          "rep": 51,
          "likelihood": 40
        },
        {
          "id": "eu:montenegro:fk-decic-tuzi",
          "name": "FK Dečić Tuzi",
          "rep": 48,
          "likelihood": 15
        },
        {
          "id": "eu:montenegro:fk-sutjeska-niksic",
          "name": "FK Sutjeska Nikšić",
          "rep": 50,
          "likelihood": 25
        },
        {
          "id": "eu:montenegro:fk-mogren-budva",
          "name": "FK Mogren Budva",
          "rep": 46,
          "likelihood": 10
        },
        {
          "id": "eu:montenegro:fk-rudar-pljevlja",
          "name": "FK Rudar Pljevlja",
          "rep": 45,
          "likelihood": 10
        }
      ],
      "entries": {
        "UCL": [
          {
            "source": "league:1",
            "round": 1,
            "seeded": false
          }
        ],
        "UEL": [
          {
            "source": "league:2",
            "round": 1,
            "seeded": false
          }
        ],
        "UECL": [
          {
            "source": "league:3",
            "round": 1,
            "seeded": false
          }
        ]
      }
    },
    "Luxembourg": {
      "rank": 51,
      "clubs": [
        {
          "id": "eu:luxembourg:swift-hesperange",
          "name": "Swift Hesperange",
          "rep": 52,
          "likelihood": 25
        },
        {
          "id": "eu:luxembourg:fc-differdingen-03",
          "name": "FC Differdingen 03",
          "rep": 52,
          "likelihood": 25
        },
        {
          "id": "eu:luxembourg:f91-dudelingen",
          "name": "F91 Düdelingen",
          "rep": 52,
          "likelihood": 25
        },
        {
          "id": "eu:luxembourg:jeunesse-esch",
          "name": "Jeunesse Esch",
          "rep": 49,
          "likelihood": 15
        },
        {
          "id": "eu:luxembourg:cs-fola-esch",
          "name": "CS Fola Esch",
          "rep": 49,
          "likelihood": 5
        },
        {
          "id": "eu:luxembourg:atert-bissen",
          "name": "Atert Bissen",
          "rep": 47,
          "likelihood": 5
        }
      ],
      "entries": {
        "UCL": [
          {
            "source": "league:1",
            "round": 1,
            "seeded": false
          }
        ],
        "UEL": [
          {
            "source": "league:2",
            "round": 1,
            "seeded": false
          }
        ],
        "UECL": [
          {
            "source": "league:3",
            "round": 1,
            "seeded": false
          }
        ]
      }
    },
    "Georgia": {
      "rank": 52,
      "clubs": [
        {
          "id": "eu:georgia:iberia-1999",
          "name": "Iberia 1999",
          "rep": 50,
          "likelihood": 30
        },
        {
          "id": "eu:georgia:dinamo-batumi",
          "name": "Dinamo Batumi",
          "rep": 50,
          "likelihood": 25
        },
        {
          "id": "eu:georgia:dinamo-tbilisi",
          "name": "Dinamo Tbilisi",
          "rep": 53,
          "likelihood": 37
        },
        {
          "id": "eu:georgia:dila-gori",
          "name": "Dila Gori",
          "rep": 48,
          "likelihood": 8
        }
      ],
      "entries": {
        "UCL": [
          {
            "source": "league:1",
            "round": 1,
            "seeded": false
          }
        ],
        "UEL": [
          {
            "source": "league:2",
            "round": 1,
            "seeded": false
          }
        ],
        "UECL": [
          {
            "source": "league:3",
            "round": 1,
            "seeded": false
          }
        ]
      }
    },
    "Estonia": {
      "rank": 53,
      "clubs": [
        {
          "id": "eu:estonia:fc-flora",
          "name": "FC Flora",
          "rep": 53,
          "likelihood": 60
        },
        {
          "id": "eu:estonia:fci-levadia",
          "name": "FCI Levadia",
          "rep": 51,
          "likelihood": 25
        },
        {
          "id": "eu:estonia:nomme-kalju-fc",
          "name": "Nõmme Kalju FC",
          "rep": 47,
          "likelihood": 10
        },
        {
          "id": "eu:estonia:paide-linnameeskond",
          "name": "Paide Linnameeskond",
          "rep": 47,
          "likelihood": 5
        }
      ],
      "entries": {
        "UCL": [
          {
            "source": "league:1",
            "round": 1,
            "seeded": false
          }
        ],
        "UEL": [
          {
            "source": "league:2",
            "round": 1,
            "seeded": false
          }
        ],
        "UECL": [
          {
            "source": "league:3",
            "round": 1,
            "seeded": false
          }
        ]
      }
    },
    "Wales": {
      "rank": 54,
      "clubs": [
        {
          "id": "eu:wales:the-new-saints-fc",
          "name": "The New Saints FC",
          "rep": 52,
          "likelihood": 70
        },
        {
          "id": "eu:wales:connahs-quay-nomads",
          "name": "Connah's Quay Nomads",
          "rep": 50,
          "likelihood": 24
        },
        {
          "id": "eu:wales:penybont-fc",
          "name": "Penybont FC",
          "rep": 49,
          "likelihood": 5
        },
        {
          "id": "eu:wales:barry-town-united",
          "name": "Barry Town United",
          "rep": 45,
          "likelihood": 1
        }
      ],
      "entries": {
        "UCL": [
          {
            "source": "league:1",
            "round": 1,
            "seeded": false
          }
        ],
        "UEL": [
          {
            "source": "league:2",
            "round": 1,
            "seeded": false
          }
        ],
        "UECL": [
          {
            "source": "league:3",
            "round": 1,
            "seeded": false
          }
        ]
      }
    },
    "San Marino": {
      "rank": 55,
      "clubs": [
        {
          "id": "eu:san-marino:tre-fiori-fc",
          "name": "Tre Fiori FC",
          "rep": 52,
          "likelihood": 50
        },
        {
          "id": "eu:san-marino:ac-virtus",
          "name": "AC Virtus",
          "rep": 51,
          "likelihood": 20
        },
        {
          "id": "eu:san-marino:tre-penne",
          "name": "Tre Penne",
          "rep": 52,
          "likelihood": 20
        },
        {
          "id": "eu:san-marino:la-fiorita",
          "name": "La Fiorita",
          "rep": 50,
          "likelihood": 10
        }
      ],
      "entries": {
        "UCL": [
          {
            "source": "league:1",
            "round": 1,
            "seeded": false
          }
        ],
        "UEL": [
          {
            "source": "league:2",
            "round": 1,
            "seeded": false
          }
        ],
        "UECL": [
          {
            "source": "league:3",
            "round": 1,
            "seeded": false
          }
        ]
      }
    }
  },
  "qualifying": {
    "UCL": {
      "rounds": [
        {
          "round": 1,
          "week": 1
        },
        {
          "round": 2,
          "week": 2
        },
        {
          "round": 3,
          "week": 3,
          "losersTo": {
            "comp": "UECL",
            "round": 2
          }
        },
        {
          "round": 4,
          "week": 4,
          "losersTo": {
            "comp": "UEL",
            "round": 4
          }
        },
        {
          "round": 5,
          "week": 5,
          "losersTo": {
            "comp": "UEL",
            "phase": "league"
          }
        }
      ],
      "winnersTo": "league"
    },
    "UEL": {
      "rounds": [
        {
          "round": 1,
          "week": 2
        },
        {
          "round": 2,
          "week": 3
        },
        {
          "round": 3,
          "week": 4,
          "losersTo": {
            "comp": "UECL",
            "round": 3
          }
        },
        {
          "round": 4,
          "week": 5,
          "losersTo": {
            "comp": "UECL",
            "round": 4
          }
        },
        {
          "round": 5,
          "week": 6,
          "losersTo": {
            "comp": "UECL",
            "phase": "league"
          }
        }
      ],
      "winnersTo": "league"
    },
    "UECL": {
      "rounds": [
        {
          "round": 1,
          "week": 3
        },
        {
          "round": 2,
          "week": 4
        },
        {
          "round": 3,
          "week": 5
        },
        {
          "round": 4,
          "week": 6
        }
      ],
      "winnersTo": "league"
    }
  },
  "calendar": {
    "leaguePhase": [
      11,
      16,
      17,
      19,
      22,
      24,
      29,
      31
    ],
    "knockoutPO": [
      34,
      35
    ],
    "R16": [
      37,
      38
    ],
    "QF": [
      41,
      42
    ],
    "SF": [
      44,
      45
    ],
    "final": 47
  },
  "leaguePhase": {
    "size": 36,
    "pots": 4,
    "potSize": 9,
    "matchesPerTeam": 8,
    "maxPerAssocPerPot": 3,
    "maxSameAssocOpponents": 2,
    "directToR16": 8,
    "playoffFrom": 9,
    "playoffTo": 24
  }
};
if (typeof module !== 'undefined' && module.exports) module.exports = EUROPE_DATA;
