// GENERATED by scripts/parse-injuries-xlsx.mjs from injuries.xlsx. Do not edit by hand:
// edit the workbook, then re-run the parser. Each entry: { id, name, weight (likelihood), minWeeks, maxWeeks, category }.
const INJURIES = [
 {
  "id": "knock",
  "name": "Dead leg",
  "weight": 18,
  "minWeeks": 1,
  "maxWeeks": 2,
  "category": "Bruise"
 },
 {
  "id": "bruise",
  "name": "Deep bruise",
  "weight": 15,
  "minWeeks": 1,
  "maxWeeks": 1,
  "category": "Bruise"
 },
 {
  "id": "ankle1",
  "name": "Ankle sprain",
  "weight": 12,
  "minWeeks": 1,
  "maxWeeks": 5,
  "category": "Ligament"
 },
 {
  "id": "ankle2",
  "name": "Ankle ligament tear",
  "weight": 5,
  "minWeeks": 6,
  "maxWeeks": 9,
  "category": "Ligament"
 },
 {
  "id": "ham1",
  "name": "Hamstring strain",
  "weight": 12,
  "minWeeks": 1,
  "maxWeeks": 3,
  "category": "Muscle"
 },
 {
  "id": "ham2",
  "name": "Hamstring strain",
  "weight": 10,
  "minWeeks": 3,
  "maxWeeks": 7,
  "category": "Muscle"
 },
 {
  "id": "ham3",
  "name": "Hamstring tear",
  "weight": 4,
  "minWeeks": 8,
  "maxWeeks": 24,
  "category": "Muscle"
 },
 {
  "id": "groin",
  "name": "Groin strain",
  "weight": 9,
  "minWeeks": 2,
  "maxWeeks": 6,
  "category": "Muscle"
 },
 {
  "id": "calf",
  "name": "Calf strain",
  "weight": 8,
  "minWeeks": 2,
  "maxWeeks": 6,
  "category": "Muscle"
 },
 {
  "id": "hip",
  "name": "Hip flexor strain",
  "weight": 6,
  "minWeeks": 2,
  "maxWeeks": 5,
  "category": "Muscle"
 },
 {
  "id": "illness",
  "name": "Illness",
  "weight": 6,
  "minWeeks": 1,
  "maxWeeks": 2,
  "category": "Illness"
 },
 {
  "id": "appendicitis",
  "name": "Appendicitis",
  "weight": 3,
  "minWeeks": 3,
  "maxWeeks": 5,
  "category": "Illness"
 },
 {
  "id": "back",
  "name": "Back spasm",
  "weight": 5,
  "minWeeks": 1,
  "maxWeeks": 3,
  "category": "Muscle"
 },
 {
  "id": "lower_back",
  "name": "Lower back injury",
  "weight": 5,
  "minWeeks": 2,
  "maxWeeks": 5,
  "category": "Muscle"
 },
 {
  "id": "diskhernia",
  "name": "Herniated disc",
  "weight": 2,
  "minWeeks": 12,
  "maxWeeks": 36,
  "category": "Cartilage"
 },
 {
  "id": "toe",
  "name": "Bruised foot",
  "weight": 5,
  "minWeeks": 1,
  "maxWeeks": 3,
  "category": "Bone"
 },
 {
  "id": "thigh",
  "name": "Thigh strain",
  "weight": 5,
  "minWeeks": 2,
  "maxWeeks": 5,
  "category": "Muscle"
 },
 {
  "id": "concussion",
  "name": "Concussion",
  "weight": 4,
  "minWeeks": 1,
  "maxWeeks": 3,
  "category": "Head"
 },
 {
  "id": "shoulder",
  "name": "Shoulder sprain",
  "weight": 4,
  "minWeeks": 3,
  "maxWeeks": 6,
  "category": "Joint"
 },
 {
  "id": "knee-mcl",
  "name": "Knee ligament (MCL)",
  "weight": 4,
  "minWeeks": 5,
  "maxWeeks": 10,
  "category": "Ligament"
 },
 {
  "id": "jumpers-knee",
  "name": "Jumper's knee",
  "weight": 4,
  "minWeeks": 4,
  "maxWeeks": 10,
  "category": "Ligament"
 },
 {
  "id": "wrist",
  "name": "Wrist sprain",
  "weight": 3,
  "minWeeks": 2,
  "maxWeeks": 4,
  "category": "Joint"
 },
 {
  "id": "meniscus",
  "name": "Knee cartilage (meniscus)",
  "weight": 3,
  "minWeeks": 8,
  "maxWeeks": 18,
  "category": "Cartilage"
 },
 {
  "id": "face",
  "name": "Facial fracture",
  "weight": 2,
  "minWeeks": 2,
  "maxWeeks": 4,
  "category": "Bone"
 },
 {
  "id": "metatarsal",
  "name": "Broken metatarsal",
  "weight": 2,
  "minWeeks": 8,
  "maxWeeks": 14,
  "category": "Bone"
 },
 {
  "id": "dislocation",
  "name": "Dislocated shoulder",
  "weight": 1,
  "minWeeks": 6,
  "maxWeeks": 12,
  "category": "Joint"
 },
 {
  "id": "dislocation-finger",
  "name": "Dislocated finger",
  "weight": 2,
  "minWeeks": 3,
  "maxWeeks": 8,
  "category": "Joint"
 },
 {
  "id": "fracture",
  "name": "Fractured leg",
  "weight": 1,
  "minWeeks": 16,
  "maxWeeks": 28,
  "category": "Bone"
 },
 {
  "id": "achilles",
  "name": "Achilles rupture",
  "weight": 1,
  "minWeeks": 32,
  "maxWeeks": 46,
  "category": "Tendon"
 },
 {
  "id": "acl",
  "name": "Cruciate ligament (ACL)",
  "weight": 1,
  "minWeeks": 36,
  "maxWeeks": 52,
  "category": "Ligament"
 },
 {
  "id": "broken-hand",
  "name": "Broken hand",
  "weight": 1,
  "minWeeks": 6,
  "maxWeeks": 8,
  "category": "Bone"
 },
 {
  "id": "broken-collarbone",
  "name": "Clavicle fracture",
  "weight": 3,
  "minWeeks": 8,
  "maxWeeks": 12,
  "category": "Bone"
 },
 {
  "id": "broken-nose",
  "name": "Broken nose",
  "weight": 3,
  "minWeeks": 3,
  "maxWeeks": 6,
  "category": "Bone"
 },
 {
  "id": "broken-coccyx",
  "name": "Broken tailbone",
  "weight": 2,
  "minWeeks": 8,
  "maxWeeks": 13,
  "category": "Bone"
 },
 {
  "id": "broken-heel",
  "name": "Broken heel bone",
  "weight": 2,
  "minWeeks": 20,
  "maxWeeks": 44,
  "category": "Bone"
 }
];

// Injury names are translated at DISPLAY time, never at creation. `p.injury.type` holds the
// English name and is written into the save (and into injuryHistory, which is kept for the life
// of a career), so translating on the way in would bake one language into the save and leave a
// player who switches language with a mixed-language history.
//
// New injuries also carry `id`; anything from an older save has only the English name, so that is
// mapped back to an id here. Two entries share the name "Hamstring strain", which is harmless:
// they translate to the same words.
const _INJ_BY_NAME = {};
const _INJ_BY_ID = {};
for (const i of INJURIES) {
    _INJ_BY_ID[i.id] = i;
    if (!(i.name.toLowerCase() in _INJ_BY_NAME)) _INJ_BY_NAME[i.name.toLowerCase()] = i;
}
// Accepts an injury object ({id, type}), an id, or the raw English name an old save stored.
function injuryName(x) {
    if (x == null) return '';
    const id = (typeof x === 'object') ? (x.id || null) : null;
    const raw = (typeof x === 'object') ? (x.type || x.name || '') : String(x);
    const inj = (id && _INJ_BY_ID[id]) || _INJ_BY_NAME[String(raw).toLowerCase()] || null;
    if (!inj) return raw;                       // an injury from a future/edited data file
    if (typeof I18n === 'undefined' || !I18n.t) return inj.name;
    const key = 'inj.' + inj.id;
    const out = I18n.t(key);
    return (out && out !== key) ? out : inj.name;   // untranslated -> the English name, never the key
}
if (typeof module !== 'undefined' && module.exports) module.exports = { INJURIES, injuryName };
