// GENERATED by scripts/parse-injuries-xlsx.mjs from injuries.xlsx. Do not edit by hand:
// edit the workbook, then re-run the parser. Each entry: { id, name, weight (likelihood), minWeeks, maxWeeks, category }.
const INJURIES = [
 {
  "id": "knock",
  "name": "Dead leg",
  "weight": 18,
  "minWeeks": 1,
  "maxWeeks": 2,
  "category": "Bruise"
 },
 {
  "id": "bruise",
  "name": "Deep bruise",
  "weight": 15,
  "minWeeks": 1,
  "maxWeeks": 1,
  "category": "Bruise"
 },
 {
  "id": "ankle",
  "name": "Ankle sprain",
  "weight": 12,
  "minWeeks": 2,
  "maxWeeks": 5,
  "category": "Ligament"
 },
 {
  "id": "ham",
  "name": "Hamstring strain",
  "weight": 11,
  "minWeeks": 3,
  "maxWeeks": 6,
  "category": "Muscle"
 },
 {
  "id": "groin",
  "name": "Groin strain",
  "weight": 9,
  "minWeeks": 2,
  "maxWeeks": 5,
  "category": "Muscle"
 },
 {
  "id": "calf",
  "name": "Calf strain",
  "weight": 8,
  "minWeeks": 2,
  "maxWeeks": 4,
  "category": "Muscle"
 },
 {
  "id": "hip",
  "name": "Hip flexor strain",
  "weight": 6,
  "minWeeks": 2,
  "maxWeeks": 4,
  "category": "Muscle"
 },
 {
  "id": "illness",
  "name": "Illness",
  "weight": 6,
  "minWeeks": 1,
  "maxWeeks": 2,
  "category": "Illness"
 },
 {
  "id": "back",
  "name": "Back spasm",
  "weight": 5,
  "minWeeks": 1,
  "maxWeeks": 3,
  "category": "Muscle"
 },
 {
  "id": "toe",
  "name": "Bruised foot",
  "weight": 5,
  "minWeeks": 1,
  "maxWeeks": 3,
  "category": "Bone"
 },
 {
  "id": "thigh",
  "name": "Thigh strain",
  "weight": 5,
  "minWeeks": 2,
  "maxWeeks": 4,
  "category": "Muscle"
 },
 {
  "id": "concussion",
  "name": "Concussion",
  "weight": 4,
  "minWeeks": 1,
  "maxWeeks": 3,
  "category": "Head"
 },
 {
  "id": "shoulder",
  "name": "Shoulder sprain",
  "weight": 4,
  "minWeeks": 3,
  "maxWeeks": 6,
  "category": "Joint"
 },
 {
  "id": "knee-mcl",
  "name": "Knee ligament (MCL)",
  "weight": 4,
  "minWeeks": 5,
  "maxWeeks": 9,
  "category": "Ligament"
 },
 {
  "id": "wrist",
  "name": "Wrist sprain",
  "weight": 3,
  "minWeeks": 2,
  "maxWeeks": 4,
  "category": "Joint"
 },
 {
  "id": "meniscus",
  "name": "Knee cartilage (meniscus)",
  "weight": 3,
  "minWeeks": 8,
  "maxWeeks": 14,
  "category": "Cartilage"
 },
 {
  "id": "face",
  "name": "Facial fracture",
  "weight": 2,
  "minWeeks": 1,
  "maxWeeks": 3,
  "category": "Bone"
 },
 {
  "id": "metatarsal",
  "name": "Broken metatarsal",
  "weight": 2,
  "minWeeks": 8,
  "maxWeeks": 14,
  "category": "Bone"
 },
 {
  "id": "dislocation",
  "name": "Dislocated shoulder",
  "weight": 1,
  "minWeeks": 6,
  "maxWeeks": 12,
  "category": "Joint"
 },
 {
  "id": "fracture",
  "name": "Fractured leg",
  "weight": 1,
  "minWeeks": 16,
  "maxWeeks": 28,
  "category": "Bone"
 },
 {
  "id": "achilles",
  "name": "Achilles rupture",
  "weight": 1,
  "minWeeks": 22,
  "maxWeeks": 36,
  "category": "Tendon"
 },
 {
  "id": "acl",
  "name": "Cruciate ligament (ACL)",
  "weight": 1,
  "minWeeks": 24,
  "maxWeeks": 40,
  "category": "Ligament"
 }
];
if (typeof module !== 'undefined' && module.exports) module.exports = { INJURIES };
